### ISSUE TITLE
Correct uuid on README.MD

### ISSUE THREAD

**Issue by returntrip** [gTile/gTile#10]
I think you need to correct the following:

from: `git clone https://github.com/gTile/gTile.git ~/.local/share/gnome-shell/extensions/gTile`
to `git clone https://github.com/gTile/gTile.git ~/.local/share/gnome-shell/extensions/gTile@gTile.github.com`

In my case, if the destination directory does not match the UUID `gtile@gTile.github.com` then I am not able to "start2 gTile (not available on Gnome Tweaks Extensions).

**Comment by scherepanov** [comment]
Thanks for pointing it out. That is a valid point.
I tried to tweak metadata.json. And it does not help! I am on Ubuntu 17.04
I tried:
1) Copy into directory xxxx/gTile@gTile.github.com (or with all small letters). Restart gnome-shell. gtile is not active.
2) Create zip file (zip -r gTile@gtile.github.com.zip *). Use tweak tool to install extension from zip file. Got popup message "your session need to be restarted for changes to be active". 
3) Modify metadata.json - adding various fields, do all lowercase etc. Same effect on attempt to copy directory/restart Gnome-shell, or use tweak tool.

On session restart, Gnome-shell correctly determine and activate gTile with current metadata.json (and with all my modifications).

I checked other extension, too Google Earth wallpaper. I downloaded zip file, and tried to install it by both methods. And it shows exactly same behavior. You need to logout/login to have it enabled/tweak tool to see new extension.
I used gnome-shell restart to develop/debug extension. It appears installation require login/logout.
I will do PR with docs correction and some changes to metadata.json.

**Comment by severoraz** [comment]
I didn't need to logout/login, I just renamed the directory and restarted the shell, so that's weird

**Comment by returntrip** [comment]
Maybe @scherepanov is using wayland instead of Xorg? Restart is not possible on wayland.

**Comment by returntrip** [comment]
@scherepanov just to be sure I have deleted gTile. I have cloned using `git clone https://github.com/gTile/gTile.git ~/.local/share/gnome-shell/extensions/gTile@gTile.github.com`. After which I have restarted `gnome-shell` by `Alt-f2  > r` and gTile has loaded correctly.

**Comment by severoraz** [comment]
Nice input @returntrip! It always seemed odd to me not being able to restart Wayland.

**Comment by scherepanov** [comment]
OK, now it is more clear why I cannot restart.
There is one more pull request with corrected docs, I will ask to add those changes there.

**Comment by StuntsPT** [comment]
#15 should take care of this.

**Comment by scherepanov** [comment]
Well.. not so easy.
Yesterday I uploaded gTile to extensions.gnome.org, and got response from @maweki stating that uuid should remain same after ownership transfer. We changed uuid from gTile@vibou to gTile@gtile.github.com, keeping "name" filed same.
It appears this creates new extension on e.g.o.
I will wait confirmation from @maweki, but seems to be we need to change uuid to original gTile@vibou. Will be one more PR.

**Comment by maweki** [comment]
Exactly. The goal of the whole exercise was that existing users get your upgrades and there are no two extensions with that name. We identify extensions by uuid and the ownership transfer now allows you to upload to the previous uuid. You could have uploaded with a new uuid the whole time.

But that was exactly what we didn't want. The uuid is not that important and not really visible or exposed to the user's anyways. You can change the project URL and description etc. To fit your new upstream project.
