### ISSUE TITLE
Can't save any sessions

### ISSUE THREAD

**Issue by finnmerlett** [gTile/gTile#102]
Whenever I try and save a session I get a load of errors:

`me@my-computer:~$ lwsm save`

`findDesktopFile cant find file; searched patterns []`
`findDesktopFile cant find file; searched patterns []`
`Generic Error in Meta Wrapper findDesktopFile cant find file; searched patterns undefined`
`Generic Error in Meta Wrapper findDesktopFile cant find file; searched patterns undefined`
`Generic Error in Meta Wrapper findDesktopFile cant find file; searched patterns undefined`
`Generic Error in Meta Wrapper findDesktopFile cant find file; searched patterns undefined`
`Generic Error in Meta Wrapper findDesktopFile cant find file; searched patterns undefined`
`Generic Error in Meta Wrapper findDesktopFile cant find file; searched patterns undefined`
`Generic Error in Meta Wrapper findDesktopFile cant find file; searched patterns undefined`
`(node:6126) UnhandledPromiseRejectionWarning: findDesktopFile cant find file; searched patterns`
`(node:6126) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)`
`(node:6126) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

`wlsm list` returns nothing after attempted saving of session. This occurs with both save to default and save specific session.

**Comment by scherepanov** [comment]
What makes you think it is related to gTile?
