### ISSUE TITLE
Port to ElementaryOS

### ISSUE THREAD

**Issue by murbanowicz** [gTile/gTile#103]
Thanks for great tool.
Do you think you could port it to ElementaryOS somehow?

**Comment by scherepanov** [comment]
ElementaryOS is quite different beast, no full-fledged gnome-shell. It looks by far more for complete rewrite, then port.
Also, current code structure is bad. At least gTile have to be 100% rewritten in TypeScript. Then, at least in theory it is possible to talk about some kind of port.
Anyway, I am way too busy and cannot get even little time to implement some ideas/bug fixes in current codebase. That is the largest problem.

**Comment by murbanowicz** [comment]
Do you need help with TypeScript?

**Comment by scherepanov** [comment]
Yes, gTile need to be moved to TypeScript.
There is almost working port to TypeScript, if you can complete it would be of a huge help.
It is #93 
If you can join efforts with @JMurph2015  and complete it, would be a huge deal.

**Comment by scherepanov** [comment]
After reading about Elementary OS, I have an impression that very few changes needed to have gTile working there.
May be we should consider port to Elementary OS in a future.
Will return to this topic after finishing rewriting in typescript.

**Comment by murbanowicz** [comment]
Oh! Great! I have already left the message on the TS migration with asking for branch etc. I will try to help!

**Comment by murbanowicz** [comment]
Hi!
Any plans for doing that? It did sound promising, but looks like you didn't/don't have time for that?

**Comment by scherepanov** [comment]
Sorry, had no time to actually do anything.
Your fate is in your hands. Create port, submit PR, or make your own repo.

**Comment by JMurph2015** [comment]
Hi @murbanowicz! I've been pretty busy with some personal life stuff recently so the full rewrite port to TS has been on hold, but recently the project has been incrementally converting files to Typescript it seems, so it may be possible when more of that refactoring is done.  However since this is a all-volunteer project, the best way to ensure something happens is to pitch in.

**Comment by scherepanov** [comment]
Port to TS pretty much done.
Now, feel free to port to Elementary OS!

**Comment by scherepanov** [comment]
Sweet dreams...
