### ISSUE TITLE
Mark GDK windows as tiled (Would fix gnome terminal)

### ISSUE THREAD

**Issue by jcsanyi** [gTile/gTile#104]
There's been several issues raised and dismissed here complaining about Gnome Terminal and how it forces its window to a multiple of the font grid resulting in extra padding on the right and bottom of any tiled windows.

However - Gnome Terminal only does this when the window is not fullscreen, not maximized, **and not tiled**... specifically for this reason.

From gnome-terminal/src/terminal-window.c
```
  if (gdk_window != NULL &&
      (gdk_window_get_state (gdk_window) &
       (GDK_WINDOW_STATE_MAXIMIZED | WINDOW_STATE_TILED | GDK_WINDOW_STATE_FULLSCREEN)))
    {
      /* Don't adjust the size of maximized or tiled (snapped, half-maximized)
       * windows: if we do, there will be ugly gaps of up to 1 character cell
       * around otherwise tiled windows. */
      return;
    }
```

Can we properly mark GDK windows as being tiled when gTile positions them? This is how gnome-shell's built-in tiling to the right and left edges works and why it doesn't result in the same margin issues.

I don't know enough about mutter and gdk/gtk to know if this is possible or what's involved - but it seems like this should be something we can and should support.

**Comment by scherepanov** [comment]
I would be glad to mark tiled window as GTK tiled, but do not know how.
If you will find how, please post here.
I will try to search in gnome code how left/right screen half is done, but in past I made several attempts to find this piece of code and failed.
Obviously, gnome is marking tiled windows as GTK tiled.
I was interested to find this piece of code, as gnome on window move do more smooth transition effect than gTile does, and I would like to have it in gTile too.
And generally, lack of gnome docs is a very big issue. recently I tried to catch monitor-changed signal in gTile, spent a lot of time, and it still does not work.

**Comment by scherepanov** [comment]
OK, did some digging.
GDK window do have state. One of flags is GDK_WINDOW_STATE_TILED, but it is marked as deprecated.
There are flages that show tiling state for each edge of windows.
And there is a c methods get_state in GDK and gdk_window_state that allow to access it.
Unfortunately, neither GDK or GTK have methods to set them. I do not know how to mark window as tiled or tiled on one of borders.
Now, GJS (Gnome Javascript) docs does not show binding for GDK.get_state and for GTK.gdk_window_get_state.

It means, there is not enough docs to write this in c, and even less for writing in Javascript.
Even if in Javascript I will access GDK directly, there are no description of "set_window_state" to mark window as tiled.
No luck.

**Comment by jcsanyi** [comment]
Thanks for investigating - that's about as much as I was able to find, and you've actually gone a bit further than I was able to. I don't know enough about GDK or GTK (or how they interact with other systems, like gnome-shell or mutter) myself to go any further than this, but it might be worth leaving the issue open to see if somebody else can contribute their expertise.

**Comment by scherepanov** [comment]
After more digging... GTK have method
static void
update_edge_constraints (GtkWindow      *window,
                         GdkSurfaceState  state)
that allow to set tiling.
gdk_window_get_state is extracting tiling state.
So, it is doable.
Now last but not least thing left - both functions update_edge_constraints and gdk_window_get_state do not have JavaScript bindings.
Do  you know how to add JavaScript bindings to arbitrary c function?

**Comment by scherepanov** [comment]
So...
Looks like JavaScript binding to GDK is a "fixed" thing.
I cannot call from JavaScript arbitrary c function.
That quite complicate stuff... now someone who maintains JavaScript - GDK binding should add several calls.
No idea who is doing this integration and where to start.

**Comment by schnz** [comment]
Going to close this for now.

1. [Gnome Console](https://apps.gnome.org/de/Console/) no longer has this behavior. 
2. gTile cannot circumvent the behavior of applications that forces the windows to grow in multiples of some base value (e.g. 5px). The only way to avoid that is when the window is half-maximized. See my comment here for further information on why I don't believe that this is something that gTile should support:  https://github.com/gTile/gTile/issues/336#issuecomment-1836116641
