### ISSUE TITLE
Tiling fullscreen applications?

### ISSUE THREAD

**Issue by different55** [gTile/gTile#105]
Is it possible to block applications from actually becoming fullscreen? Or maybe go at it the reverse direction, don't alert fullscreen applications when they become tiled?

When watching pretty much any web video, the web browser will hide its UI only if it's fullscreened. But that's not very handy if you're trying to do other things at the same time, which is usually where a tiling WM comes in and saves the day.

I think some dedicated tiling WMs handle this situation. Searching the internet I found a [forum post](https://bbs.archlinux.org/viewtopic.php?pid=1080338#p1080338) that seems relevant, says if you block or unset the "_NET_WM_FULLSCREEN atom" then the window won't be fullscreen anymore. That sounds pretty low level though, is that even something we can deal with on the level of an extension?

**Comment by scherepanov** [comment]
Seems to be possible to do it.
But, well out of gTile scope.

**Comment by different55** [comment]
Why would that be out of scope? That's not an uncommon thing for tiling WMs, and it's very handy.

**Comment by scherepanov** [comment]
gTile is not a WM. It is an extension that sit on top of gnome-shell WM.
To implement windowing of a fullscreen, you need to dig rather deep into gnome-shell WM.
If you really want to try, submit a PR with your code changes. Will gladly accept.

**Comment by different55** [comment]
I am making an attempt but so far failing horribly. Wouldn't happen to know the direction of a tree to bark up would you?

**Comment by scherepanov** [comment]
My big guess, it is somewhere inside c library.
gnome-shell is merely a javascript wrapper around c libraries
I remember there is an API call to maximize window.... in theory you should intercept it. Which is done not on Java Script layer but by modifying core c library.

May be, you need to overwrite JavaScript maximizing function. You need to track all windows in application and for each window overwrite maximize call. And,I do not know how to overwrite this call.
The more I think how to do it, the more I convinced it is not possible to do on gnome-shell extension level.
May be, you can trick app to think it is in full screen mode, while in reality it is in window. That probably is a correct direction to go.

**Comment by different55** [comment]
Well darn. Bashing my head against GJS til something good happens is one thing but patching core bits of GNOME or Mutter is sadly probably not worth the effort. :/
