### ISSUE TITLE
Keyboard shortcut for "snap to neighbors"

### ISSUE THREAD

**Issue by SaswatPadhi** [gTile/gTile#106]
A keyboard shortcut to snap a window to fill the space between its neighboring windows would be very useful. The [gssnaptoneighbors](https://github.com/tpyl/gssnaptoneighbors) extension provides this functionality, but it would be nice if gTile supported this as well.

**Comment by scherepanov** [comment]
Nice idea, seems to be not hard to implement.

**Comment by scherepanov** [comment]
Stars aligned... this feature is submitted for merge into master.
Can you:
1)Try and see if this actually works, and is what you want
2)Create smallish animated picture that show how to use this feature, and add it to README.md
3) Submit PR with picture and your changes to README.md
That would help a lot

**Comment by SaswatPadhi** [comment]
Awesome! Thanks for the super quick addition.

I will try to test it out and create a PR within the next day or two.

**Comment by scherepanov** [comment]
It appears, extension Snapshot Window Sizer is using same shortcut `<Alt><Ctrl>s` as snap-to-neighbors.
That is causing problem with gTile.
Snapshot Window Sizer is a system extension and cannot be (easily) deleted.
You can disable Snapshot Window Sizer, or re-assign shortcut in preferences.
