### ISSUE TITLE
Images in Readme are white on white

### ISSUE THREAD

**Issue by lightonflux** [gTile/gTile#107]
The images (e.g. for the animation toggle) are display white when rendered by github. This means they are not visible at all and need to be opened in another tab. 

Please add black variants for the README, as it appears to be the only online documentation for gTile. 

For the extension itself it would be nice to have a tool tip when hovering the button. Because it is almost impossible to find out their function by trial and error. 

![Bildschirmfoto von 2020-02-08 14-18-57](https://user-images.githubusercontent.com/1377943/74085884-fa5d3000-4a7d-11ea-8207-20fd22ec1528.png)

**Comment by scherepanov** [comment]
Yes image is white on white.
Can you submit PR with a fix?

**Comment by lightonflux** [comment]
MR created.

**Comment by scherepanov** [comment]
Thanks!
I am on Mac right now, will review and merge as soon as will get to linux box.
