### ISSUE TITLE
Multiple shortcuts for actions

### ISSUE THREAD

**Issue by OmerSakar** [gTile/gTile#114]
In the settings, under the Accelerators tab, a shortcut can be set to do a certain action (e.g. _Preset resize 1_). Currently, only one shortcut can be set for each action. It would be great if we could have at least two possible shortcuts.

My use case for this is that I normally have actions mapped to the Numpad. When I use a keyboard without a Numpad (e.g. a TKL or 65%), I cannot perform these actions. It would be a possibility to have at least two shortcuts (maybe three but that is debatable) to allow flexibility for multiple setups.

**Comment by scherepanov** [comment]
As you mention, this can be done with several configs, and you can choose one for your setup.
Each config will have it's own set of shortcuts.
Will nicely solve your problem.
If stars will align, this functionality will be in master shortly. I will invite you to test.

**Comment by schnz** [comment]
Latest version supports multiple shortcuts per action.
