### ISSUE TITLE
A notation addition for "Resize presets"

### ISSUE THREAD

**Issue by mkerrisk** [gTile/gTile#115]
I find gTile very nice. I have one suggestion. The current notation used in "Resize presets" is overly hard to grok: one must do a moderate amount of mental math in order to work out what the set of tile positions mean. However, typically, one is wanting to orient windows with respect to an edge or a corner of the screen and all one really wants to specify is screen position and the window sizes. So I suggest the addition of a further notation:

[compass dir] [tile grid size] [window-size]...

Thus, for example, instead of the following present notation for the top right corner of the screen:

14x6 8:0 13:2, 7:0 13:2, 10:0 13:1, 10:0 13:2, 10:0 13:3

it would be considerably easier if one could write something like:

NE 14x6 6x3 7x3 4x2 4x3 4x4

And natuarally there would be NW, SE and SW. For N, S, E, and W, the window position would be such that the midpoint of the corresponding window edge would be placed at the midpoint of the screen edge.

**Comment by scherepanov** [comment]
As you correctly noticed, syntax for defining tiling is not easy.
I do not think that adding more complexity will make it easier for users.
Looks like best solution would be to make visual editor that allow save current window position as preset. Or any other interactive visual editor.
Can you do some coding and submit PR? I would be very useful.

**Comment by mkerrisk** [comment]
Thanks for your response. For what it's worth, I think the notation I'm proposing would make life less complicated for users (as I think my example shows)), but you seem to disagree.

I'm open minded about the idea of a visual editor, but that would surely much more complexity in the code than what I propose, which I imagine would be a relatively small code change. However, I'm not a JS programmer.

**Comment by scherepanov** [comment]
Yes, I am not inclined to extend syntax for tiling definition. Preference is for visual editor. It is possible editor can be very simple.
