### ISSUE TITLE
Avoid resize handles

### ISSUE THREAD

**Issue by madprops** [gTile/gTile#116]
Hi, this is a pretty cool extension. I just have this slight problem when I make a layout. I have a 1-(1/1) layout, that is, 1 window in the left, full height, and on the right 1 top and 1 bottom, half height each. The problem I have is that the window in the bottom right, which happens to be Hexchat, shows the resize handles when I hover the bottom edge with my mouse. I would prefer there were no resize handles since that's where I keep my tabs. Actually if I just move the window a bit manually, and place it there again, the resize handles are gone, which is weird

**Comment by madprops** [comment]
Here's an illustration. The red part is what I mean 
![2020-02-27_16-44](https://user-images.githubusercontent.com/206498/75493870-7f9e7b00-5980-11ea-9fa9-b6db2c780a47.png)

**Comment by scherepanov** [comment]
I suspect that hexchat intercept events on window move and do some action (show handles)
It is definitely not gTile that shows handles.

**Comment by madprops** [comment]
The handles appear are "activated" after tiling. It happens with Rhythmbox too. It's normal window resizing, but if I move the windows (hexchat and rhythmbox) this is disabled (I can move the mouse to the bottom and I can click the windows instead of initiating resize).

**Comment by madprops** [comment]
What I'm thinking is maybe gtile is not fully attaching the windows (or at least the bottom right window) correctly to the edges due to wrong pixel calculation?

**Comment by scherepanov** [comment]
Probably you are talking about two different issues.
It was a fix for correct pixel calculation recently, I think this fix is only on github master - try to install from github.
I am looking at your picture, and it is not clear what you are talking about - can you provide clear picture

**Comment by madprops** [comment]
Yes sorry for being confusing. I just mean that after I do the tiling, and afterwards I want to interact with the bottom right window, which has a tab bar at the bottom, the edge will be used for resizing, I can't click the tabs. I'll try the one on master.

**Comment by madprops** [comment]
Seems the same happens with the master version. Here's a pic of when I move the mouse to the bottom
![IMG_20200227_203931463](https://user-images.githubusercontent.com/206498/75505752-bb960800-59a1-11ea-8765-067ba410f2eb.jpg)

**Comment by madprops** [comment]
And like I said, moving the window and manually placing it on the corner, removes the handles problem.
