### ISSUE TITLE
Clutter.TableLayout is not a constructor

### ISSUE THREAD

**Issue by murbanowicz** [gTile/gTile#117]
Hi,
after today's updates of OS I ran into this error with the gTile. 
The extension won't load because of that.

**Comment by scherepanov** [comment]
What upgrade you had, OS or gTile. What was upgraded.
What versions was before and after.

**Comment by murbanowicz** [comment]
I have now GNOME 3.35.91, maybe that's the case?

**Comment by scherepanov** [comment]
I still have 3.34 that came with Fedora.
Will check this on next version of Fedora

**Comment by murbanowicz** [comment]
I will appreciate it. May I help in any way? I have to say gTile made my productivity on my ultrawide so much better and now I feel like I would lost my hand as tiling in 2 halves is ridicolous on such big screen...

**Comment by scherepanov** [comment]
Of course you can help, and your help would be appreciated.
Find what is wrong, issue a code fix, submit a PR, test changes in your version of Gnome and past versions, make sure it works everywhere.
Easy.

**Comment by murbanowicz** [comment]
Not that easy I am afraid... This area of development is like black box for me...

**Comment by scherepanov** [comment]
Sorry, now you will have to wait till gnome 3.35.91 or above will be incorporated into next stable release of Fedora.

**Comment by ejemba** [comment]
"Clutter.TableLayout is not a constructor" 
I have this same error in gnome-shell 3.36

**Comment by ricab** [comment]
Fails to install here too.

```console
$ gnome-shell --version
GNOME Shell 3.35.91
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu Focal Fossa (development branch)
Release:	20.04
Codename:	focal
```

**Comment by scherepanov** [comment]
This is now tracked in #118
