### ISSUE TITLE
Option to remove titlebar with min/max/close when tiled

### ISSUE THREAD

**Issue by skewty** [gTile/gTile#120]
The code for this goes like this:
```bash
#!/bin/bash

#
# This script will toggle the active window's decorations
#

WIN_ID=`xprop -root _NET_ACTIVE_WINDOW | cut -d ' ' -f 5`
DECORATED="0x2,0x0,0x1,0x0,0x0"
UNDECORATED="0x2,0x0,0x0,0x0,0x0"

if [[ $(xprop -id "$WIN_ID" _MOTIF_WM_HINTS | cut -d ' ' -f 5 | cut -c 1) = "1" ]]; then
  xprop -id "$WIN_ID" -f _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS "$UNDECORATED"  
else
  xprop -id "$WIN_ID" -f _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS "$DECORATED"
fi

WIN_NAME=`wmctrl -l | grep "0x[0]*${WIN_ID:2}" | cut -d ' ' -f 5-`

wmctrl -a "$WIN_NAME"  # re-activate the window
```

**Comment by scherepanov** [comment]
Script is nice, but not really translates into JavaScript code that calls various Gnome libraries

I think it would not be very disruptive for all users, if it will be additional keyboard shortcut to toggle focused window toolbar. On other side, making all tiled windows would be way too disruptive.

Also, you can easily create separate gnome-shell extension that will remove toolbar, on keyboard shortcut.

**Comment by skewty** [comment]
> Script is nice, but not really translates into JavaScript code that calls various Gnome libraries
This is how extensions like [No Title Bar](https://github.com/franglais125/no-title-bar) work.  The JS code can be looked up there.

> I think it would not be very disruptive for all users, if it will be additional keyboard shortcut to toggle focused window toolbar. On other side, making all tiled windows would be way too disruptive.

The idea would be that when a window becomes "tiled" it is locked into place.  It can behave differently.   See #104 for how this already happening at a native gnome shell level.  Modern gtk apps have a header bar and not a title bar so they are not affected.  So really we are talking about legacy gtk and qt apps.  Even modern Electron apps are doing away with the conventional title bar (see Mattermost and Chrome for examples).

What use, other than showing title, does the title bar have once a window becomes tiled / locked in?  The user knows what the app is based on window contents.  They no longer require the title to drag it around..  it is now sized and positioned correctly.

gTile's user base is a keyboard friendly group so closing the app without [X] shouldn't be an issue.  Windows can still be moved with Super-Left Mouse drag and resized with Super-Right Mouse drag.

This auto-remove the title bar is attempted by several add-ons like "No Title Bar" (above) and "Unite".  They don't have any knowledge of when a window is "tiled" though so they could at best solve it nicely for maximized windows only.

The tiler really is the only place this can be fully solved and the reason I am creating the issue here.  If you would accept the feature as a default to off checkbox, I could likely put the PR together myself (likely with some help from others).

**Comment by scherepanov** [comment]
OK, go ahead and submit PR
This functionality should be disabled by default. Advanced users should have ability to enable it.
Make a checkbox - remove toolbar when tiled, default off.
Add a keyboard shortcut to toggle toolbar on focused window, default disabled.
If you can also implement #104, would be nice. I look on it, there are some Clutter functions that are not in GJS, I do not know how to work around it.

**Comment by scherepanov** [comment]
Not an easy to do
