### ISSUE TITLE
gui window "auto closes" when switching to certain applications

### ISSUE THREAD

**Issue by bradleyJohnson55** [gTile/gTile#127]
Using Ubuntu 18.04 LTS, I have "auto close" unchecked. 
When I switch from Chrome window to PyCharm, the gui disappears. I can switch to terminal or settings or any other window without problem. But it's closing when you try to switch to a pycharm window.

**Comment by cwh1te** [comment]
Do the shortcut keys (m, 1, 2, 3, etc.) still work after switching to PyCharm? I kind of wonder if PyCharm might be drawing over top of it.

**Comment by scherepanov** [comment]
Yes it's known problem
gTile cannot find focus window for some app. I have CLion, PyCharms, IntelliJ from Jetbrains, they all behave same way
Apr 02 12:12:28 chi-fed26-scherepanov gnome-shell[563675]: gTile _onFocus 
Apr 02 12:12:28 chi-fed26-scherepanov gnome-shell[563675]: gTile resetFocusMetaWindow
Apr 02 12:12:28 chi-fed26-scherepanov gnome-shell[563675]: gTile No focus window, hide tiling
Apr 02 12:12:28 chi-fed26-scherepanov gnome-shell[563675]: gTile hideTiling

Problem is that function getFocusApp cannot find focused app:

/**
 * Get focused window by iterating though the windows on the active workspace.
 * @returns {Object} The focussed window object. False if no focussed window was found.
 */
function getFocusApp() {
    if (tracker.focus_app == null) {
        return false;
    }

    let focusedAppName = tracker.focus_app.get_name();

    if (contains(excludedApplications, focusedAppName)) {
        return false;
    }

    let windows = WorkspaceManager.get_active_workspace().list_windows();
    let focusedWindow = false;
    for (let i = 0; i < windows.length; ++i) {
        let metaWindow = windows[i];
        if (metaWindow.has_focus()) {
            focusedWindow = metaWindow;
            break;
        }
    }

    return focusedWindow;
}

If you can find what is wrong, please submit PR

**Comment by scherepanov** [comment]
I did little investigation.
It appears when PyCharm is clicked, OnFocus event raised, but window is not in focus.
Shell.WindowTracker.get_default().focus_app is null.
I modified code to check all windows, and no window has focus.
If I am trying to open gTile when PyCharm is in focus, it is being detected properly.
It appears to be a bug in gnome-shell. OnFocus event is issued, but no window has focus.
I do not see how you can work around this problem.
Closing this, seems to be easy solution is not possible.
