### ISSUE TITLE
Accelerator shortcuts not being saved in Gnome 3.36.1

### ISSUE THREAD

**Issue by robertofarrell** [gTile/gTile#129]
Changing an Accelerator shortcut seems to work without issue and will persist between tab changes in the gTile configuration but once the configuration window is closed and opened again the Accelerator shortcuts revert to their previous settings.

**Comment by flomax** [comment]
I know this is closed, but I'm finding the same results.. changes to accelerators do not persist past closing the config window.
3.36.1 on Arch.

**Comment by scherepanov** [comment]
This bug is fixed on master. I will roll out master to EGO, and you will get update with a fix.
Meantime, you can install directly from git master, as described in README

**Comment by flomax** [comment]
> This bug is fixed on master. I will roll out master to EGO, and you will get update with a fix.
> Meantime, you can install directly from git master, as described in README

I can confirm git version is working as expected.
Many thanks to you, dude ! Your efforts here are greatly appreciated :)
