### ISSUE TITLE
After resizing, windows are 1px off the bottom of the screen

### ISSUE THREAD

**Issue by Ashley-Upson** [gTile/gTile#130]
Hello

I've only recently started using your extension, and I have to say, THANK YOU

I spent months and months manually resizing windows to get them into the corners!

I have noticed a small issue - when I resize a window to 3 or 5 blocks high, and align it to the bottom, the window appears 1px off the bottom of the screen

It's by no means a major bug of course, just a minor annoyance

My question for you - is there a way I can fix this, say with a config edit?

I can provide system specs/versions if you need them

Thanks again for your work!

**Comment by Ashley-Upson** [comment]
It also has the same behaviour for the 8x6, 6x4 and 4x4 configurations when aligning/resizing to a bottom corner

**Comment by scherepanov** [comment]
Yes, you can show where calculations of window position is wrong.
Enable debugging in gTile preferences, then disable/enable gTile.
Do window resize.
Look on journalctl, see what gTile caclulated for window position.
If you spot wrong calculation, post it here, and explain what it should be.

**Comment by Ashley-Upson** [comment]
Thanks for that, I'll post results later tonight

**Comment by scherepanov** [comment]
Ashley?

**Comment by Ashley-Upson** [comment]
Hello

My apologies for the delay in my response

Please see the following gist for the logs
https://gist.github.com/Ashley-Upson/4e4a2bf6059677a52df87db7f78bbf11

I believe the x.5's on line 48 are causing the issue, as it's always one pixel out (as below)
![image](https://user-images.githubusercontent.com/19336594/81001281-6661f100-8e3f-11ea-9233-f5ae0c911ff8.png)
![image](https://user-images.githubusercontent.com/19336594/81001353-7f6aa200-8e3f-11ea-86c7-6022f7806a33.png)

**Comment by scherepanov** [comment]
You are right!
It is a rounding error. Window position should be integer, should not be float with .5
Will check when I will have time.
