### ISSUE TITLE
Ubuntu 20.04 > Settings: Animation off > Dialog does not appear

### ISSUE THREAD

**Issue by DT0815** [gTile/gTile#131]
hi, first of all thnx for your genius tool - i absolutely love it.

Maybe short minor issue: I've installed freshly Ubuntu 20.04. Seems that when deactivating animations the dialog UI does not show up anymore. When I activate it again (using gnome-tweaks > extensions > gtile: settings) it pops up again. 

Can someone reproduce?

**Comment by JackVoo** [comment]
Hi, yes. Same machine. Ubuntu 20.04.
When deactivate animation from the UI, it will no appear.

**Comment by scherepanov** [comment]
Yes, I can reproduce. Thanks for reporting.
Will check what is wrong.
