### ISSUE TITLE
Respect margins for maximized windows

### ISSUE THREAD

**Issue by derykfoote** [gTile/gTile#133]
Is it possible to maximize a window using gTile while respecting the margins configured in the extension preferences? ('Maximize' might not be the right word for what I'm trying to do!)

For example, I have the following configuration:
![Screenshot from 2020-05-04 15-50-12](https://user-images.githubusercontent.com/3356332/80979287-0c513380-8e1f-11ea-9603-47de9dd523a0.png)

I would like the end result to look like this:
![Screenshot from 2020-05-04 15-55-41](https://user-images.githubusercontent.com/3356332/80979857-c9439000-8e1f-11ea-95ce-f28a85ea9b53.png)

I like the appearance this creates, because it allows some visibility of the desktop wallpaper and provides some spacing between the title bar of maximized windows and the main top bar.

Is this supported by gTile?

**Comment by scherepanov** [comment]
Yes, you can do it
You can do it using mouse interface - just select all squares
You can do it using interactive interface - again, select all squares
Or, you can define full screen window for keyboard shortcut. 
Everything will work

**Comment by derykfoote** [comment]
If I use either interface and select all squares in the grid:
![Screenshot from 2020-05-06 14-22-07](https://user-images.githubusercontent.com/3356332/81181955-169d3a00-8fa5-11ea-9700-66d4bbb46a87.png)
then the window maximizes all the way to the screen edge, with no margin:
![Screenshot from 2020-05-06 14-23-39](https://user-images.githubusercontent.com/3356332/81182030-32a0db80-8fa5-11ea-8370-235642fd69ac.png)

**Comment by scherepanov** [comment]
That is not how it should work.
Will check when will get a minute.

**Comment by derykfoote** [comment]
@scherepanov Thanks! Let me know if there's any info I can provide to help. FWIW I've disabled the edge tiling feature just in case this was interfering:
![Screenshot from 2020-05-09 15-27-51](https://user-images.githubusercontent.com/3356332/81476414-bbb84c80-9209-11ea-9857-d4ad2bd42224.png)

**Comment by sorin-davidoi** [comment]
> That is not how it should work.

Looks like there is an exception for this case: https://github.com/gTile/gTile/blob/48b40dbb9943e639149cdfbd36b7e4b8936deeb1/extension.js#L1925:L1930

Using `move_resize_window_with_margins` when `this._allSelected()` is `true` seems to work,

**Comment by sorin-davidoi** [comment]
> Using `move_resize_window_with_margins` when `this._allSelected()` is true seems to work.

I have been running with this patch for 10 days, didn't notice any issues. Let me know if this is the right fix and I'll open a pull request.

**Comment by scherepanov** [comment]
Please submit PR, in a week I will be able to review and test.

**Comment by scherepanov** [comment]
I closed PR for now.
Feel free to submit it again. Keep current behaviour, add settings in prefs for new behaviour.

**Comment by sorin-davidoi** [comment]
@derykfoote The version published at https://extensions.gnome.org now has an options for this:

<img src="https://user-images.githubusercontent.com/2109702/97892935-f5898c00-1d30-11eb-8b72-d4dc14b4d3fa.png" alt="Preference window showing checkbox for applying margin to maximized windows" width=400>
