### ISSUE TITLE
Pop up placed incorrectly when using multiple monitors

### ISSUE THREAD

**Issue by K1kk3rt** [gTile/gTile#134]
I'm happily using this extension. But ever so often the pop up in in a whole different place as to where it is supposed to be. See the image below.

I have no problems at all using this extension on my laptop, with just one screen. But on my desktop is looks like this:

![Screenshot from 2020-05-14 11-28-04](https://user-images.githubusercontent.com/37216006/81917954-2684d180-95d6-11ea-80b3-e0b679dfe98c.png)

Here I wanted to rearrange the spotify window on the second screen. It displays two pop ups, but in the wrong place. It should be over the spotify window. Sometimes the pop up is outside of the screen and I cannot use it at all. The most right pop up is used to arrange on the left screen. The top left pop up is used on the main screen.
If I would want to rearrange chrome on the main screen, I only get one pop up which is in the center this time.

My system:
Ubuntu version: 19.10
Kernel: x86_64 Linux 5.3.0-51-generic
DE: Gnome 3.34.2

**Comment by scherepanov** [comment]
It appears your monitor settings is not very standard.
Looks like you have two screens combined into one. 
gTile on start determine number and size of monitors. On each monitor there is a single popup.
If you have more than one popup, most likely your system is reporting two monitors.
You can display check in settings->display

**Comment by K1kk3rt** [comment]
Would gTile display the popups correctly if my screen to the left would be horizontal?

![image](https://user-images.githubusercontent.com/37216006/82301663-d97b7380-99b8-11ea-9ff1-e67fe18a82d5.png)

![image](https://user-images.githubusercontent.com/37216006/82301708-eac48000-99b8-11ea-82b5-d02340b8974a.png)


Above are my display settings.

**Comment by scherepanov** [comment]
I have one horizontal and two vertical monitors, works fine.

**Comment by MaxSagebaum** [comment]
I have a similar problem. The gTile window is not centered on my main screen. So reaching it with 
the cursor is quite cumbersome. Please see the picture.

![Screenshot from 2020-06-02 17-13-54](https://user-images.githubusercontent.com/12955649/83537679-28ff8a80-a4f5-11ea-8c88-7b847185c4be.jpg)

Since it is my laptop and I restart it only every one or two month. The monitor setup ist changed quite often.

Since the focus of the user is usually on the window he/she wants to resize, would it not be better to have the gtile popup in the center of the window which should be resized?

**Comment by scherepanov** [comment]
This is different problem. gTile defines screens on enabling, which happens on session login. When you add/remove monitors, screens are not recaclulated.
For permanent fix, you need to catch on-monitor-change event and do screen recaclulation. That requires some research and digging into gnome-shell code. See #57 
For temp workaround, you can install gnome-shell extension "Extensions", and manually disable/enable gTile each time you monitor configuration changed. That should make your life easier.
Meantime, you can do some research, dig into gnome-shell code, find how to correctly catch on-monitor-change event, and submit PR. I will gladly accept.

**Comment by scherepanov** [comment]
That should be permanently fixed by #57
Workaround is to disable/enable gTile each time monitor changed. Quickest way to do is with "Extension" extension.
