### ISSUE TITLE
TypeError: Utils.getSettings is not a function

### ISSUE THREAD

**Issue by con-f-use** [gTile/gTile#135]
With the latest version from the repo, I get

```
Extension "gTile@vibou" had error: TypeError: Utils.getSettings is not a function
```

if I revert `settings.js` to 73789809a47, it works just fine:

![image](https://user-images.githubusercontent.com/11145016/82120882-5e804600-9789-11ea-81fe-f0a322e61ce6.png)

This is on stock Ubuntu 18.04.4 (GNOME Shell 3.28.4) and 19.10.

**Comment by feedingaliencat** [comment]
Same here:
```
TypeError: Utils.getSettings is not a function

Stack trace:
  get@/home/emilio/.local/share/gnome-shell/extensions/gTile@vibou/settings.js:10
  basics_tab@/home/emilio/.local/share/gnome-shell/extensions/gTile@vibou/prefs.js:221
  buildPrefsWidget@/home/emilio/.local/share/gnome-shell/extensions/gTile@vibou/prefs.js:349
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:239
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:377
  @<main>:1
  ```
with Debian GNU/Linux 9, GNOME 3.22.2

**Comment by scherepanov** [comment]
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/misc/extensionUtils.js
function getSettings is there...
Seems to be it is only in recent gnome-shell version.
To support gnome-shell 3.22, I will have to revert to old code

**Comment by con-f-use** [comment]
Thanks for your efforts, scherepanov!
