### ISSUE TITLE
No keyboard way to move between multiple monitors

### ISSUE THREAD

**Issue by wispfrog** [gTile/gTile#136]
Unless I am missing something obvious, there seems to be no keyboard accelerator for moving a window to another monitor. Using the mouse works, though. Maybe tab or pageup/pagedown would be nice.

BTW, it is annoying that unrecognised keys get passed through rather than swallowed.

**Comment by scherepanov** [comment]
Gnome-shell already has functionality to move windows between monitors - Shift-Super-Arrows
Works just fine, I am using it a lot.
