### ISSUE TITLE
Ubuntu 20.04 does not lock the screen on suspend

### ISSUE THREAD

**Issue by alexsmartens** [gTile/gTile#139]
My Ubuntu 20.04 stopped locking the screen on suspend at some point. A web search showed that [disabling gnome extensions ](https://askubuntu.com/questions/1252125/ubuntu-20-04-lts-screen-lock-not-working-randomly/1255771#1255771) solves the problem. In my case, disabling Gtile solved the problem. 
Have you seen anything similar before? 
I've been enjoying using Gtile, can you help with resolving the issue?

**Comment by scherepanov** [comment]
Yes known issue #124 
gnome-shell bug, upgrade gnome-shell to at least 3.36.3-1
