### ISSUE TITLE
discrepancy between git-created directory name and name in metadata.json

### ISSUE THREAD

**Issue by severoraz** [gTile/gTile#14]
I just installed gTile from this repository and found out it wasn't being loaded because the directory was not named gTile@gTile.github.com. I'm using gnome-shell version 3.26.1-1.

I would think this bug would be solved by matching the name in the metadata.json and the README.md files.

**Comment by returntrip** [comment]
see https://github.com/gTile/gTile/issues/10

**Comment by severoraz** [comment]
this bug is a duplicate of #10
