### ISSUE TITLE
Resize windows manually

### ISSUE THREAD

**Issue by farefernandez** [gTile/gTile#140]
Hi, thanks for gTile, I recently started using it.

Is it possible to manually (ie dragging their borders with a mouse) resize windows to adjust their dimensions, after resizing it with gTile?

I usually run a 3x3 grid, and most of the times I have 3 windows maximized vertically (runs well with an ultrawide monitor). 
Sometimes, I want to adjust the size of one of these 3 windows manually, without resorting to a more complex grid.

It would be great if the other two windows adjusted their size accordingly as I resize the one that I want.

Thanks!

**Comment by scherepanov** [comment]
Coordinated resize of several windows with mouse is not easy and should be part of gnome-shell.
Also, using mouse is counterproductive, at least I am trying to stay with keyboard whenever possible.
I would suggest you will define one more grid, something like 9x9, in addition to your 3x3 grid. Your resize workflow would be:
1) Focus on window you want to resize Alt-Tab
2) activate gTile Super-Enter
3) Now Space is switching grids. Hit Space once to go to 9x9 grid
4) Shift-Arrow will resize your window
5) Switch to next window Alt-Tab
6) Shift-Arrow resize border
7) Switch back to 3x3 grid, hit Space
8) Escape to close gTile
That would be rather quick. You are adding Space for switching between grids.
Of course, it is contrary to your desire not to resort to additional grid.
I do have plans to make coordinated window move, incorporating similar workflow in some keyboard shortcut.
Will do sometimes in a future, when will have some spare time. 
As for moving border of two windows with mouse, no plans for gTile.

**Comment by farefernandez** [comment]
Thanks, I'm going to give this workflow a try!

FWIW, I found this example of "resize multiple windows with mouse", I don't actually understand the implementation, however I thought it was worth dropping a link here:

[https://extensions.gnome.org/review/7877](https://extensions.gnome.org/review/7877
)

Thanks!
