### ISSUE TITLE
Why Gtile on LInux mint has less features than Gtile on Ubuntu?

### ISSUE THREAD

**Issue by Tapyu** [gTile/gTile#141]
Hello, I'm a beginner on Linux. Since I started on Mint, I have delved for a good window tilling. I found [Gtile](https://cinnamon-spices.linuxmint.com/extensions/view/21), but even so, it just has the basic function of shift+arrows to adjust the window on my screen, It is not enough.

To my surprise, I found out that Ubuntu has this extension too, but with a lot of functions. So, what the difference between these two projects? Is it possible to install this gnome extension on Mint.

Thanks in advance.

**Comment by scherepanov** [comment]
Looking at this extension. It appears to be a minimalistic heavily modified fork of gTile, with removed all possible functions except few.
Interestingly, it is exactly subset of features that I am using in my everyday work, and it is enough for me. May be it is a really good approach.

Only problem with this extension is that it is named Gtile, way too similar to gTile, confusing users like you. 

Anyway, extra functionality in gTile does not hurt, I found there are always people who are using most weird functionality and happy.

gTile should be installable on Gnome desktop for any distribution. Just go to extensions.gnome.org and install from there.

**Comment by Tapyu** [comment]
So it is possible to install gtile gnome extension on Linux Mint? How can I do it?

1. I tried to download gnome tweaks: `sudo apt install gnome-tweak-tool`
2. Then I installed the gnome-shell-extensions: `sudo apt install gnome-shell-extensions`
1. Finally, I installed the native host connector: `sudo apt-get install chrome-gnome-shell`

But when to go to the website, It appears the following message:
`Unable to locate GNOME Shell settings or version. Make sure it is installed and running.`

How can I handle this?

**Comment by Tapyu** [comment]
I think it is not possible to get the gnome gtile on Linux Mint

**Comment by scherepanov** [comment]
If Linux Mint is running regular gnome-shell, it should be possible to run extensions for gnome-shell.
Can you do manual install, as described in README.md?

**Comment by Tapyu** [comment]
> If Linux Mint is running regular gnome-shell, it should be possible to run extensions for gnome-shell.
> Can you do manual install, as described in README.md?

Yes, I tried. But I couldn't run this extension properly on Mint.

**Comment by scherepanov** [comment]
Sorry to hear. Most likely you need to do some digging to find what is linux Mint, and why it does not run properly gnome-shell extensions.
Post your findings here.

**Comment by Tapyu** [comment]
Sure, thanks for the responsiveness.
