### ISSUE TITLE
"Error loading extension" on Ubuntu Groovy Gorilla 20.10

### ISSUE THREAD

**Issue by Gustl22** [gTile/gTile#151]
Can't enable the plugin in Ubuntu Groovy Gorilla 20.10. (preview) via Tweaks.
Any ideas? Or how to help :D
Best regards.

**Comment by scherepanov** [comment]
I suspect this is due to changes to new version of gnome-shell.
It is fixed on master.
Please install from github master, instructions are in README.
Let me know if it fix problem.

**Comment by Gustl22** [comment]
Works flawlessly. Thank you!
