### ISSUE TITLE
Not working with GNOME 3.38

### ISSUE THREAD

**Issue by tanrax** [gTile/gTile#152]
Unfortunately it does not work with this version

**Comment by jens-st** [comment]
I can confirm that using Debian Sid.
GNOME Shell 3.38.0

**Comment by tanrax** [comment]
Not in https://extensions.gnome.org/

**Comment by scherepanov** [comment]
Bug is fixed on master.
Will roll out to EGO today.

**Comment by scherepanov** [comment]
Bug is fixed on master.
New version of extension is pending review on EGO.
You can wait till review will complete, or you can install from master.
Most likely review on EGO will complete in a week.

**Comment by tanrax** [comment]
Thanks!!

**Comment by scherepanov** [comment]
EGO reviewer rejected new version of gTile.
He is saying that signal is not being disposed correctly.
Will take some time to figure out.
Meanwhile, master in github works fine
