### ISSUE TITLE
Gnome 3.38.1 Arch Linux

### ISSUE THREAD

**Issue by tomWhilbert** [gTile/gTile#153]
Will not load.  Receive 'ERROR` when I attempt to enable it from [Gnome Extensions](https://extensions.gnome.org/extension/28/gtile/l)

Any logs you may need?

Cheers

**Comment by SR-G** [comment]
Same problem for me. Maybe it's linked to https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/issues/260

**Comment by scherepanov** [comment]
Bug is fixed on master. Install from github, follow instructions in README
Version with bug fix is pending review on EGO.

**Comment by tomWhilbert** [comment]
Works perfect! You rock.
