### ISSUE TITLE
gTile on gnome-shell 3.38 not working - no tweener

### ISSUE THREAD

**Issue by scherepanov** [gTile/gTile#156]
Issue is fixed on master, and new version is on extensions.gnome.org - upgrade gTile!
Note that gnome-shell is not restartable, to have new gTile code running, you need to login/logout.
Or, you can install from github according to README.

**Comment by cryptoquick** [comment]
@scherepanov lol, glad you mentioned! I'll be patient. Thanks for working on this, gTile is amazing.

**Comment by cryptoquick** [comment]
Can confirm, the update is released and the issue is fixed. I would recommend uninstalling the extension, rebooting, and reinstalling the extension. Originally, it upgraded successfully, and the config window could start, but the extension itself didn't start. My settings thankfully persisted.

**Comment by scherepanov** [comment]
Fixed
