### ISSUE TITLE
export config from ui

### ISSUE THREAD

**Issue by Hkyx** [gTile/gTile#157]
Hi, nice tool !
Got some question:
I try to put the config manually  in the preset but it seem not working easily but the ui is correctly working with clic and size.
Is there a option after setting my ui with a mouse to export that to get the value or set it directly as specific present ?

thanks,

ty

**Comment by scherepanov** [comment]
Not currently, though users do requested it in past.
But, it will be there, if you will do coding and will submit PR. I will gladly add it there.
