### ISSUE TITLE
gTile dialog not displaying on gnome-shell 3.28 and below

### ISSUE THREAD

**Issue by Andrea-Augello** [gTile/gTile#158]
After the latest update, the usual pop-up dialog one would see with `Super`+`Enter` or by clicking the icon on the toolbar does not show up. Instead, if I enable debugging, I see the following error messages:

* Keyboard shortcut
``` 
 gTile showTiling
JS ERROR: TypeError: this.actor.ease is not a function
Grid.prototype.show@/home/$USER/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:1797:13
showTiling@/home/$USER/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:915:13
toggleTiling@/home/$USER/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:942:9
keyBindings["show-toggle-tiling"]@/home/$USER/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:407:41
```

* Icon
```
gTile _onButtonPress Click Toggle Status on system panel
gTile showTiling
JS ERROR: TypeError: this.actor.ease is not a function
Grid.prototype.show@/home/$USER/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:1797:13
showTiling@/home/$USER/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:915:13
toggleTiling@/home/$USER/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:942:9
GTileStatusButton<._onButtonPress@/home/$USER/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:541:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
```
After some poking around I discovered that disabling animations and autoclose the dialog pops up, but it cannot be used. Moreover, all other gTile shortcuts work as expected.

I am experiencing this issue on Ubuntu 18.04 LTS with GNOME 3.28.2

**Comment by scherepanov** [comment]
Yes, that is a gnome-shell version compatibility  issue. New version of gnome-shell remove tweener, old versions require it.
I will put a lower limit on gnome-shell version for new versions of gTile.
Meanwhile, you do found a good workaround. May be, I will incorporate it in code, when will have a moment.
Can you submit PR with a fix? On enabling, you need to check gnome-shell version, and disable animations if 3.28 and lower.

**Comment by Andrea-Augello** [comment]
Unfortunately, my workaround only allows mouse inputs, and even those sometimes fail. 
If I try to use the popup dialog's keyboard shortcuts or to resize a window using the arrow keys, the input goes straight to the window I am trying to resize.

**Comment by scherepanov** [comment]
It means, you should not upgrade.
Please try to poke around, and see if you can find a working config.
I do not have gnome-shell 3.28 and cannot really test...
If you cannot find working config, I will limit gnome-shell version fo rnew version of gTile, starting from 3.30.

**Comment by AlexFalappa** [comment]
Can confirm this, I am on Ubuntu 18.04 too.

Where can I find the previous version?

**Comment by scherepanov** [comment]
Yes, there is no way to roll back to previous version.
I will upload current version of gTile to EGO, and will limit gnome-shell version to 3.30 and above.
But, there is no way to get older version.
I will ask around, how to remove previous version from EGO, then you will be able to select your gnome-shell version and download corresponding version of gTile.
Meantime, you can checkout from git, get previous commit, before removing tweener.
Yes, it is a nasty problem with previous gnome-shell versions compatibility. We did some checks... and it was working properly.

**Comment by JoelRSimpson** [comment]
Installing from commit d7aa9ff fixed it for me on Ubuntu 18.04.LTS with Gnome 3.28.4

**Comment by Sam-Jarvis** [comment]
@JoelRSimpson Thanks for this! Worked for me.

**Comment by sethgoldin** [comment]
From the [GNOME Extensions page](https://extensions.gnome.org/extension/28/gtile/), I found this thread. Confirming that this also seems broken with CentOS 7.8 with GNOME 3.28.2. Please advise.

**Comment by Purg** [comment]
I'm on Centos 8 with gnome-shell 3.32.2-14. A manual install v35 (tag) of gTile into `~/.local/share/gnome-shell/extensions/gTile@vibou` worked for me (follow instructions in top-level README).

**Comment by onlycparra** [comment]
I did this in my machine, and it worked:

## Check that you have the same version as me:

```
cat /etc/os-release | grep 'VERSION='
VERSION="18.04.5 LTS (Bionic Beaver)"
```

```
gnome-shell --version
GNOME Shell 3.28.4
```

## Install Bazel (needed for building gTile):

```
sudo apt install curl gnupg
curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
sudo apt update && sudo apt install bazel
```
## Then Install gTile:

```
git clone https://github.com/gTile/gTile.git
cd gTile
git checkout d7aa9ff 
bazel run :install-extension
```
Press `Alt + R` to reload Gnome-Shell. Done :smirk:

**Comment by Andrade** [comment]
I'm in Ubuntu 18.04 with GNOME Shell 3.28.4 and using Firefox with [GNOME Shell integration](https://addons.mozilla.org/en-US/firefox/addon/gnome-shell-integration/) (that's how I updated gTile by the way; and broke my installation).

1. I went to https://extensions.gnome.org/extension/28/gtile/ and removed gTile by pressing the red cross: this removes directory `~/.local/share/gnome-shell/extensions/gTile@vibou`. My gTile tray icon disappeared immediately. I suppose if you remove the directory manually it will work as well, but not sure since I haven't tried it.

2. Still at https://extensions.gnome.org/extension/28/gtile/ I selected shell version 3.28 (where it says _Download_) and then _extension version_ **35**. This downloads `gTilevibou.v35.shell-extension.zip`. Warning: it's 35, not 37.

3. Then unzipped the contents of the download zip into `~/.local/share/gnome-shell/extensions/` and renamed the directory `gTilevibou.v35.shell-extension` to `gTile@vibou`. So now I have `...../extensions/gTile@vibou/<bunch of files>`.

4. Finally log out and then log in. gTile now works without having to do it from GitHub.

After logging back in I got a message saying _gTile can be upgraded_ and ignored the message.

**Comment by scherepanov** [comment]
Right fix would be to remove v36 and v37 from EGO.
But, my emails to gnome-shell list are being ignored, and EGO does not have interface to remove old version of extension.
If anybody knows how to remove old version of extension from EGO, please advice.

**Comment by scherepanov** [comment]
I removed toxic version of gTile from EGO.
Now, regular install from EGO will produce a working version of gTile for gnome-shell v 3.28 and below.

**Comment by fpl** [comment]
Hi, I can confirm this issue even with 3.30.2 (as for Debian buster/stable). The previous .35 version of gTile still works.

**Comment by lweberk** [comment]
Same here. Debian 10.x (buster), stable as of writing this. 3.30.x should probably also be limited to .35.

**Comment by Purg** [comment]
I can confirm that the latest version, 42, functions for me (gnome shell v3.32.2).
