### ISSUE TITLE
Circular reference in docs

### ISSUE THREAD

**Issue by bmn001** [gTile/gTile#159]
I'm trying to find gTile's debug log to track down a problem.

README.md says "See gTile help in Preferences for info on development and debugging."

When I go to Help in gTile's Preferences, it's just a link that takes me to this github page.  The same page that tells me to visit the Help section in gTile's preferences.  :)

**Comment by scherepanov** [comment]
That is very true.... it is missed with last README update.
Will fix when will have time...
You need to enable debug in preferences, then tail logs
