### ISSUE TITLE
gTile not opening on Gnome 3.38.1

### ISSUE THREAD

**Issue by agners** [gTile/gTile#160]
After updating to Gnome 3.38.1 on ArchLinux gTile stopped working, e.g. it doesn't show up using the key bindings. I upgraded to the [latest version](https://github.com/gTile/gTile/commit/a4f8000a943f90699b592a4189ee704314a821e6) from master with the installation instructions in the README.md. However, I do get the following error message whenever I try to open gTile (enabled Debugging in settings):

```
Okt 12 14:43:41 hostname gnome-shell[4556]: gTile showTiling
Okt 12 14:43:41 hostname gnome-shell[4556]: JS ERROR: TypeError: grid is undefined
                                               showTiling@/home/user/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:897:29
                                               toggleTiling@/home/user/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:942:9
                                               show-toggle-tiling-alt@/home/user/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:408:45
```

As I am on master I think this is not the same as #156.

**Comment by agners** [comment]
Before that gTile seems to startup succesfully:

```
gTile Enabling begin
gTile Init gnome-shell version 3.38.1 major 3 minor 38
gTile Init settings
gTile grid-sizes set to 4x2, 8x4, 12x2
gTile Starting...
gTile initGrids
gTile New Grid for monitor 0
gTile ToggleSettingsButton _update event animation
gTile ToggleSettingsButton Connect button-press-event
gTile ToggleSettingsButton Connect update-toggle
gTile ToggleSettingsButtonListener Connect update-toggle
gTile ToggleSettingsButton _update event auto-close
gTile ToggleSettingsButton Connect button-press-event
gTile ToggleSettingsButton Connect update-toggle
gTile ToggleSettingsButtonListener Connect update-toggle
gTile ActionButton Connect button-press-event
gTile AutoTileMainAndList connect button-press-event
gTile ActionButton Connect button-press-event
gTile AutoTileTwoList connect button-press-event
gTile hide true
gTile Connect hide-tiling for monitor 0
gTile Init grid done
gTile Create Button
gTile GTileStatusButton _init done
gTile Binding keys
gTile Binding keys
gTile Binding keys
gTile Extention Enabled!
```

**Comment by TyrelCB** [comment]
Seeing the same on Gnome 3.36.6

**Comment by agners** [comment]
@TyrelCB that is not the case for me, reboot/logging in and out seems not to help.

**Comment by scherepanov** [comment]
It is very strange. Backtrace seems to be correctly showing line numbers in most recent code.
Works just fine for me on 3.36-4-1, cannot reproduce.

**Comment by javs** [comment]
Manual installed master on ubuntu 20.04 (gnome 3.30+2)
`Oct 12 10:25:39 a gnome-shell[1588]: JS ERROR: TypeError: grid is undefined
                                                     showTiling@/home/a/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:897:29
                                                     toggleTiling@/home/a/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:942:9
                                                     _onButtonPress@/home/a/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:541:9
                                                     wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
`
Is there something I could maybe debug/add logs for?

**Comment by agners** [comment]
@scherepanov I do have a second Arch Linux installation, and use the very same package version, yet I don't see it there. I think it has to do with settings stored. Where are the settings stored and can I clear them?

**Comment by agustingomes** [comment]
I see the same sometimes, especially when using `xrandr` to set my viewport.

I can provide more info, but i need some guidance as I don't know where I can find specific logs for gTile

**Comment by agners** [comment]
I added some debugging output, and it seems that [grids on line 695](https://github.com/gTile/gTile/blob/62f1754711b20882cd641cf1d00162a709c6a098/app.ts#L695) is empty:

```
gTile showTiling
gTile Monitors: [object Object]
gTile Key: 0:2560:0:1440
gTile grids: 
gTile grid: undefined
```

**Comment by agners** [comment]
It seems that the global variable `grids` survives a reload, and stays "invalid". This then leads to `disable()` not working, and therefore also `changed_settings()`. gTile does not recover from that state.

With #161 we ignore non-existing grid on `disable()`, with that rebuilding `grids` should work. In my case I had to open the configuration dialog once, but then it worked again.

**Comment by agners** [comment]
FWIW, this is the error on settings change, before #161. With #161 this is fixed, which then makes grids being properly setup again.

```
gnome-shell[37178]: gTile changed_settings
gnome-shell[37178]: gTile Extension start disabling
gnome-shell[37178]: gTile Unbinding keys
gnome-shell[37178]: gTile Unbinding keys
gnome-shell[37178]: gTile Unbinding keys
gnome-shell[37178]: JS ERROR: TypeError: grid is undefined
                    destroyGrids@/home/user/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:701:9
                    disable@/home/user/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:667:5
                    changed_settings@/home/user/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:493:9
```

**Comment by scherepanov** [comment]
Nice find, will check today.

**Comment by bmn001** [comment]
Seeing similar behavior here.  I updated gtile and now it won't launch.  I'm running updated ubuntu with gnome 3.36.3.

Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile Enabling begin
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile Init gnome-shell version 3.36.4 major 3 minor 36
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile Init settings
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile grid-sizes set to 8x6,6x4,4x4
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile Starting...
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile initGrids
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile New Grid for monitor 0
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ToggleSettingsButton _update event animation
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ToggleSettingsButton Connect button-press-event
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ToggleSettingsButton Connect update-toggle
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ToggleSettingsButtonListener Connect update-toggle
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ToggleSettingsButton _update event auto-close
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ToggleSettingsButton Connect button-press-event
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ToggleSettingsButton Connect update-toggle
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ToggleSettingsButtonListener Connect update-toggle
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ActionButton Connect button-press-event
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile AutoTileMainAndList connect button-press-event
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ActionButton Connect button-press-event
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile AutoTileTwoList connect button-press-event
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile hide true
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile Connect hide-tiling for monitor 0
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile Init grid done
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile Create Button
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile GTileStatusButton _init done
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: JS ERROR: Extension gTile@vibou: Error: Extension point conflict: there is already a status indicator for role GTileStatusButton
                                                     addToStatusArea@resource:///org/gnome/shell/ui/panel.js:1111:19
                                                     enable@/home/user/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:645:22
                                                     _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
                                                     loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:349:26
                                                     callback@resource:///org/gnome/shell/ui/extensionDownloader.js:234:39
                                                     gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

**Comment by agners** [comment]
@bmn001 hm, does not really look like the same issue, probably deserves a new issue.
