### ISSUE TITLE
gTile key presses are sent to the active window

### ISSUE THREAD

**Issue by behrangsa** [gTile/gTile#164]
Hi,

Here's a screen recording that shows the problem:

[bug-2020-10-18_15.08.05.zip](https://github.com/gTile/gTile/files/5397044/bug-2020-10-18_15.08.05.zip)

As you can see, whenever arrow keys are pressed to modify tiling, the Firefox address bar blinks.

**Comment by scherepanov** [comment]
Apparently, firefox grab all keyboard shortcuts.
It is hard to troubleshoot.

**Comment by stecenator** [comment]
Same with other apps: Chrome, Slack, IBM Notes... on F32 so far. This week I'm gonna try F33 with it's default Gnome.

**Comment by scherepanov** [comment]
This appears to be a bug in gnome-shell. I do not see it happens any more after recent upgrade to gnome-shell.
Hopefully, it is fixed.
I am closing htis ticket, please reopen if you will see it again.
