### ISSUE TITLE
Stopped working on Ubuntu 20.04 after latest updated

### ISSUE THREAD

**Issue by nkoroste** [gTile/gTile#172]

**Comment by beevabeeva** [comment]
Please fix. Upgrading or installing via Gnome website results in error.
![image](https://user-images.githubusercontent.com/19332617/99041155-15237e80-2593-11eb-84d6-09bb9f44bffa.png)

**Comment by scherepanov** [comment]
That is a gnome-shell feature - it has a very questionable implementation of extension upgrade.
Login/logout, error should be gone.

**Comment by beevabeeva** [comment]
Worked. Thank you!
