### ISSUE TITLE
gTile doesn't move gnome-terminal windows

### ISSUE THREAD

**Issue by jshack88** [gTile/gTile#176]
After a recent update, I noticed that all of my windows would properly resize, except gnome-terminal.
gnome-terminal would resize properly, but not move.
Examining the logs for gTile, the coordinates looked correct. There weren't any errors printing out.

After experimenting in Looking Glass for a bit it, I found that when following this same flow, (get windows from `active_workspace`, iterate to find the `has_focus`, and `move_resize_frame`), the window would resize but wouldn't always move. However, running `move_frame`, before or after always worked.
I added `move_frame` before the `move_resize_frame` locally, restarted my session, and it fixed the issue with gnome-shell.
I'll open a PR in a moment so I can link it to this issue.
(I know I could probably dig deeper into why `move_resize_frame` is inconsistent with gnome-terminal and maybe open a PR with gnome-terminal or gnome or whoever, but this was relatively quick and fairly minimal.)

I'm running:
Debian 5.9.1-1kali2
GNOME Shell 3.38.1
gtk-launch --version: 3.24.23
version number:    11.0
X.Org version: 1.20.8
GNOME Terminal 3.38.1 using VTE 0.62.1 +BIDI +GNUTLS +ICU  +SYSTEMD

**Comment by scherepanov** [comment]
Fixed in PR #177

**Comment by scherepanov** [comment]
Now official gTile from EGO contain this fix.
gnome-terminal move/resize works fine for me.
Thanks for contribution!
