### ISSUE TITLE
Windows tile under bottom-placed GNOME dock

### ISSUE THREAD

**Issue by James-G-Hill** [gTile/gTile#18]
Using Ubuntu 17.10.  I've positioned my GNOME dock at the bottom of the screen and modified the icon size.  When I use a gTile position where the bottom of the window should meet the top of the GNOME dock (eg. preset 1, 2, or 3), the bottom of the window is actually underneath the GNOME dock (which can be seen due to transparency)

See the screenshot below:

![gtile problem screenshot](https://user-images.githubusercontent.com/2002036/32418597-da8dddc2-c264-11e7-946c-3ae84cdab8b6.png)
.

**Comment by scherepanov** [comment]
Right now intended workaround is to set in preferences top/bottom panel present and change sizeof  bottom/up/left/right inset height. That is rather awkward settings, though it works.
Looks like I got information how to address this problem in more smooth way, will try to look on it how it will work.

**Comment by JMurph2015** [comment]
@James-G-Hill Also, just out of curiosity, what dock/icon theme are you using?  That looks awesome.  And yes the bottom panel workaround isn't great right now; we'll look at how it could be improved.

**Comment by James-G-Hill** [comment]
@JMurph2015 Hello, I'm using Ubuntu 17.10 with the GNOME desktop.  I have global dark theme on.  For Applications and Shell I'm using [Adapta-Nokto-Eta](https://github.com/adapta-project/adapta-gtk-theme) theme (you may need to download the 'User themes' GNOME extension then turn it on). For Icons I'm using the [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) icon set and specifically Papirus-Adapta-Nokto. As you can see I've moved the dock to the bottom; I only recently moved from Windows so I really wasn't feeling good with the dock on the left.  Hope that helps.

**Comment by JMurph2015** [comment]
@James-G-Hill Cool! I just had never seen the circular highlighting on Ubuntu dock before.  Guess I'll have to check for updates.

**Comment by dxm99** [comment]
Fedora 27 Gnome 3.26.2

After selecting bottom panel option I had to restart Gnome shell (Alt+F2 R) to make it work.

**Comment by scherepanov** [comment]
That is right, you have to restart Gnome-shell. This is limitation of current design.

**Comment by scherepanov** [comment]
Please install from my branch scherepanov/gTile and check if this issue is fixed
