### ISSUE TITLE
gtile looses ability to place correctly windows when new displayport screen is attached

### ISSUE THREAD

**Issue by ilippert** [gTile/gTile#180]
I occasionally activate an additional displayport powered screen. When I add it to the gnome-session, then gtile does not seem to update its coordinates from the new display configuration.

I wonder whether this is related to the older issue https://github.com/gTile/gTile/issues/55

**Comment by scherepanov** [comment]
That should be fixed in PR #161, #166, #167 
Unfortunately, I cannot test/verify/fix - I am working from home with only one gigantic 43'' monitor.

**Comment by ilippert** [comment]
Thanks for the note. Sorry to ask - wrong place, but in case you know: how long should it take for a version that includes these PRs on extensions.gnome.org? Cheers.
I cannot see within the gtile preferences which version I have installed.

**Comment by scherepanov** [comment]
Current EGO version is V41, V42 is pending.
V41 has all commits from master except last two.
If you have current version from EGO, those PR already in code.
This is why your problems are very strange, should be already fixed

**Comment by ilippert** [comment]
I think I do not experience the issue anymore. Thanks
