### ISSUE TITLE
Reset default shortcuts

### ISSUE THREAD

**Issue by anthony-761** [gTile/gTile#182]
How to reset the default shortcuts ?
Thanks

**Comment by scherepanov** [comment]
Good question.
I think re-installing from master would do.

**Comment by anthony-761** [comment]
I tried to uninstall and reinstall from https://extensions.gnome.org/, not working...
And I also tried to suppress directly the repertory ~/.local/share/gnome-shell/extensions/gTile@vibou and reinstall from https://extensions.gnome.org/, not working... and it is worse. Gtile windows doesn't close.

**Comment by scherepanov** [comment]
No clue why.
gnome-shell store all settings somewhere.
Should be an utility to edit settings, drop all settings for gTile and reinstall.

**Comment by snrkl** [comment]
I have the exact same issue...

**Comment by PietroMB** [comment]
me too

**Comment by omersi** [comment]
same :/

**Comment by benintech** [comment]
install dconf editor, org → gnome → shell → extensions → gtile

**Comment by schnz** [comment]
I am gonna close this, resetting shortcuts became very easy with the new preference dialog. Resetting everything to factory settings is possible via the following command:

```
dconf reset -f /org/gnome/shell/extensions/gtile/
````
