### ISSUE TITLE
config file like slate

### ISSUE THREAD

**Issue by antonio24073** [gTile/gTile#183]
Hi, happy new year,
Maybe create a config file like slate.
I wanted to add shortcuts like:

shift+super+3+6
shift+super+2+6
etc...

alt+super+3+6
alt+super+2+6
etc...

to fill multiple blocks

and replace this ctrl+super by 4x4 division like:

ctrl+super+enter
ctrl+super+ +
ctrl+super+ -
ctrl+super+ .

ctrl+super+3
ctrl+super+ 6
ctrl+super+ 9
ctrl+super+ *

ctrl+super+2
ctrl+super+ 5
ctrl+super+ 8
ctrl+super+ /

ctrl+super+Num Lock
ctrl+super+ 7
ctrl+super+ 4
ctrl+super+ 1

and 

ctrl+super+enter+ .
ctrl+super+ enter + 6
etc...

I think it would be cool

**Comment by scherepanov** [comment]
Yeah... that would be really cool.
Please submit PR with your code changes. Do not forget to keep compatibility with current functionality.
I will review, test and merge.

**Comment by antonio24073** [comment]
I think there is a better solution than slate and my configuration. 
UbuntuBudgie/window-shuffler
It has simple cli commands like 

`shuffler_nogui 2 2 0 1`
will place the active window in the bottom left cell in a grid of 2 x 2.

maybe create a keyboard shortcut for "shuffler_nogui" (opening a gtile window with coordinates) and pass the missing numbers.
That would be more powerful.

I don't know how to implement this in gtile, but it is a suggestion.

**Comment by antonio24073** [comment]
I already don't konw what I wanted.
I think gtile is the best. 
I didn't know how it works. Sorry.
