### ISSUE TITLE
no js module 'tweener' found in search path

### ISSUE THREAD

**Issue by josephhyatt** [gTile/gTile#184]
Getting error "no js module 'tweener' found in search path".. On Arch Linux.. When I try to install from gnome extensions I just get an error. Same when I try to install through Github. I love this extension, any help would be much appreciated to get it working again. Thank you.

**Comment by josephhyatt** [comment]
I've tried uninstalling and reinstalling the extension, but it did not help.

**Comment by scherepanov** [comment]
tweener is part of js environment from gnome-shell. 
Something is broken,  and broken outside of gTile.
May be, you need to wait a little, someone will push a fix and Arch linux will pick it up. It is the best I can think of.

**Comment by josephhyatt** [comment]
k, thanks

**Comment by josephhyatt** [comment]
hoping Arch Linux fixes the tweener issue so I can use gTile again
