### ISSUE TITLE
Can't position/resize a window on my second monitor using the keyboard

### ISSUE THREAD

**Issue by luizferreira** [gTile/gTile#186]
Hey guys, thanks for this outstanding project!

I'm using two monitors. If I try to use the keyboard arrows to position/resize a window in my second monitor, as soon as I press the arrow it moves the "positioner" to the first monitor:

![GTILE](https://user-images.githubusercontent.com/1700463/104714019-6a028300-5703-11eb-91fd-d8ee3f7884b0.png)

The result is I can't position/resize any window on my second monitor using the keyboard.

My OS: Linux Mint 20.04 (Cinnamon 4.6.6)
gtile: Version 1.0.0 (2021-01-12 17:11:18)

**Comment by scherepanov** [comment]
Cannot reproduce.. do not have a second monitor :-)

**Comment by scherepanov** [comment]
Finally got second monitor...
gTile can move window to second monitor with help of mouse. Select part of a grid on required monitor, and window will be positioned there.
gTile do not have keyboard shortcut to move window to other monitor. You need to use Gnome built-in <Super><Shift>-Arrows. It will move window to other monitor.
And, then you can use regular gTile keyboard shortcuts to resize window.
Using combination of Gnome and gTile keyboard shortcuts, you can move window to another monitor, and move/resize there, using only keyboard.
