### ISSUE TITLE
gTile does not work with GNOME 40 alpha

### ISSUE THREAD

**Issue by sgallagher** [gTile/gTile#187]
Fedora 34 will be shipping with the latest GNOME 40. When running Fedora Rawhide (or Fedora 33 with [this COPR](https://copr.fedorainfracloud.org/coprs/haeckerfelix/gnome-shell-40/) enabled), gTile fails to start with the error message: `invalid version supplied: 40.alpha.1; got major = 40, minor = NaN`

It would be great if gTile could support GNOME 40 when it's released.

**Comment by scherepanov** [comment]
That is fixable
Will issue a fix when will have a minute

**Comment by scherepanov** [comment]
Can you install from master and tell me if gTile will work

**Comment by sgallagher** [comment]
It fails to start and generates the following error:

```
Error: No property margin on GtkGrid

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:63:40
  basics_tab@/home/sgallagh/.local/share/gnome-shell/extensions/gTile@vibou/prefs.js:221:19
  buildPrefsWidget@/home/sgallagh/.local/share/gnome-shell/extensions/gTile@vibou/prefs.js:348:15
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```

**Comment by sgallagher** [comment]
Sorry, that was a different error; that was when trying to display the settings dialog.

The real error appears to still be: "invalid version supplied: 40.beta; got major = 40, minor = NaN"

**Comment by scherepanov** [comment]
Looks like some API calls have been removed from GTK...
For version error, have you checkout and install latest master?
It should be fixed in last commit.
I did not really test new piece of code as I have a current version with all numeric.

**Comment by sgallagher** [comment]
I checked and the contents of the extension.js in my .local folder contains your new code as well, which is perplexing.

It's possible a log out and back in was insufficient to apply it, so I'm rebooting and will try again.

**Comment by sgallagher** [comment]
OK, that was it. Apparently I needed a full reboot. It works now (though the extension options view is still unusable).

Also the upstream master lists its version at 35, while the latest published release is 42, so it's prompting me to upgrade to the non-working version again.

**Comment by sgallagher** [comment]
> Also the upstream master lists its version at 35, while the latest published release is 42, so it's prompting me to upgrade to the non-working version again.

And it applied that "upgrade" automatically so that after another reboot, I'm back on the incompatible version. Whee.
