### ISSUE TITLE
Support for screen Rotation

### ISSUE THREAD

**Issue by adgaudio** [gTile/gTile#19]
Hello!

gTile is awesome.  Thank you for maintaining it!

Gnome lets me perform a screen rotation when I tilt my laptop

Currently, I can use alt+super+2 to fill a window into the bottom half of the screen.  If I rotate the screen, gTile keeps the original orientation and the window goes out of view.  Pressing alt+super+2 again does not work as expected.

My current workaround:  If I rotate the screen, I can use the gnome tweak tool to toggle gTile off and then on.  After that, gTile has the correct orientation.

Is there any way for gTile to automatically notice screen rotations and swap x / y positions accordingly?

**Comment by scherepanov** [comment]
I never thought about screen orientation change.
Should not be hard to fix, need to subscribe to corresponding event and re-init.
Will do after investigation what is event name.

**Comment by adgaudio** [comment]
Cool!  I'm happy to help or test.  I don't know how to develop gnome extensions, but let me know if you could benefit by my assistance :)  Thank you!

**Comment by scherepanov** [comment]
If you want to help, find me the name of screen rotation event in gnome shell. Still have trouble with it.
 I will issue a fix, and you will test it.

**Comment by adgaudio** [comment]
Hi!

By events, if you mean iio-sensor-proxy, I get the following events:  **normal, bottom-up, right-up, left-up**

```
 $ monitor-sensor
    Waiting for iio-sensor-proxy to appear
+++ iio-sensor-proxy appeared
=== Has accelerometer (orientation: normal)
   [...Truncated log lines between these values...]
    Accelerometer orientation changed: right-up
    Accelerometer orientation changed: bottom-up
    Accelerometer orientation changed: right-up
    Accelerometer orientation changed: left-up
    Accelerometer orientation changed: normal
```

Since I'm not sure if this is what you wanted, I also found another extension refers "Rotation" here:  
https://github.com/bodedejavu/gnome-shell-extensions/blob/16b56e995f3c553e2b0d81d4a79534bbcae623af/display-profile-manager%40bodedejavu.github.com/newer.js#L282
they explicitly reference "Rotation" as a label in the file [prefs.js](https://github.com/bodedejavu/gnome-shell-extensions/blob/16b56e995f3c553e2b0d81d4a79534bbcae623af/display-profile-manager%40bodedejavu.github.com/prefs.js)

Also, this extension might be helpful:  https://github.com/gcampax/gnome-shell-extensions/blob/199ad878654fbd1cb01fec6aa8927b936fb98072/extensions/xrandr-indicator/extension.js

Finally, xrandr man pages has a **--rotate** option 
```
       --rotate rotation
              Rotation can be one of 'normal', 'left', 'right' or 'inverted'. This causes the output contents to be rotated  in  the
              specified  direction.  'right'  specifies a clockwise rotation of the picture and 'left' specifies a counter-clockwise
              rotation.
```

Hope that is helpful.

**Comment by scherepanov** [comment]
Looks like it will be enough to implement fix.
I will try.

**Comment by adgaudio** [comment]
Hello @scherepanov !  Thank you again for trying to add support for screen rotation.  Have you made any progress or do you need any further help?  I do not know how to develop gnome extensions, but I may be able to help further if you need assistance.  Cheers, Alex

**Comment by adgaudio** [comment]
bump.  Hello?

**Comment by scherepanov** [comment]
You are not forgotten. Just not enough time, very busy at office.
Hopefully will be able to look on it this weekend.

**Comment by adgaudio** [comment]
Thank you very much!  This will be a very useful feature!

**Comment by scherepanov** [comment]
I just made commit in my branch scherepanov/gTile that should address issue. Please install and let me know how it works.
It definitely will fix for use with keyboard shortcuts.
For use of mouse, and use of keyboard control for resize/move, may be it needs more work.
I put some debug logs to troubleshoot.
Please enable debug in Tweaks->Extensions->gTile->Preferences, then disable/enable gTile
See log messages:
journalctl /usr/bin/gnome-shell -f

I am interested if you will get messages about event monitor-changed when you rotate screen. Apparently you are unique user who have hardware which supports screen rotation.

**Comment by adgaudio** [comment]
Hi @scherepanov 

Thank you so much! I tested your code, and it works!  But also has one issue:  on rotation, the window orientation is not applied correctly.  Below are some screenshots explaining.

I can use gTile to tile my windows (in normal orientation)
![screenshot from 2018-01-17 17-33-31](https://user-images.githubusercontent.com/860369/35071137-b9d7a91e-fbad-11e7-9650-4e010e7a85e0.png)

But when I rotate the screen, the window positioning is not correct
![screenshot from 2018-01-17 17-33-41](https://user-images.githubusercontent.com/860369/35071177-cfde1cb6-fbad-11e7-9828-eb861f8f0982.png)

If I return to original orientation I used to gTile in, the correct window positioning is restored

The above screenshots demonstrate this from normal orientation to rotated orientation.  This issue also appears from rotated orientation to normal orientation.

I enabled logging as you described, monitored via journalctl, and did not see any log messages appear on rotation.

---

As is, this is certainly a huge improvement for me.  Thank you so much!!!  I am very grateful to you for your help here.

If you are inclined to fix the remaining issue, I would do the following:

- Remember the window positioning last used in that particular orientation.  (Or a variation on this: if a positioning is defined in one orientation, give same window positioning on rotation).
    - Reasoning:  It would be nice to define some way to give "normal" orientation one preset window configuration (vertical split) and allow "right-up" orientation to have a different preset configuration (horizontal split).

Cheers!

**Comment by scherepanov** [comment]
There is a good news and bad news.
Good news:
It appears I am correctly doing grid recalculation on each call (or keyboard shortcut).
Bad news:
1) It is not gTile who changes window position/size on screen rotation. It is done by code somewhere in Gnome that handles screen rotation. 
2) It appears that signal OnMonitorChange is not being generated during screen rotation. Based on your feedback - you do not see any logging of messages about caught signal "OnMonitorChange".
It means gTile is not being invoked during screen rotation, and have no way to know that screen rotation happens. Hence, nothing out of what you are asking for can be implemented.

I will try to find correct signal that is being generated by screen rotation, but so far it does not look promissing.

If I will not be able to find it, I will remove existing debug log entries about OnMonitorChange.

Looks like current state is as much as you can get from gTile.

Of course, you can file request to gnome-shell mailing list and ask about better window reorganization during monitor rotation. That would be probably your best bet.
