### ISSUE TITLE
gnome-shell 40 - No property margin on GtkGrid

### ISSUE THREAD

**Issue by scherepanov** [gTile/gTile#190]
Apparently some changes to GTK should be addressed

**Comment by scherepanov** [comment]
Error: No property margin on GtkGrid

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:63:40
  basics_tab@/home/sgallagh/.local/share/gnome-shell/extensions/gTile@vibou/prefs.js:221:19
  buildPrefsWidget@/home/sgallagh/.local/share/gnome-shell/extensions/gTile@vibou/prefs.js:348:15
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by apollo13** [comment]
Hi @scherepanov, I am running into this with other extensions and could find where this was fixed in gTile. Can you tell me how to fix this or link me to the relevant docs? Thank you!

**Comment by ijuma** [comment]
I am getting the same stacktrace wiith Gnome 40 and the latest gTile from master.

**Comment by scherepanov** [comment]
There was no fixes for this issue. After some Fedora update, it just start working properly.
I am on gnome-shell 3.38.2, works fine.
I strongly suspect it is a bug in gnome-shell, because gnome-shell update fixed it.
I think same true for gnome-shell v 40, though I have no proof

**Comment by ijuma** [comment]
Not sure, there is an extensions porting guide for Gnome 40:

https://blogs.gnome.org/shell-dev/2021/03/20/extensions-rebooted-porting-your-existing-extensions-to-gnome-40/
