### ISSUE TITLE
Grid sizes are no longer configurable

### ISSUE THREAD

**Issue by danetrata** [gTile/gTile#195]
The configurable grid sizes no longer appear inside the floating widget.

I checked this out on e7030f6, but I'm not attributing any blame.

See image.

![image](https://user-images.githubusercontent.com/4830810/109442186-158a3d00-79fd-11eb-910f-2f9349b03ce2.png)

**Comment by scherepanov** [comment]
hmmm... will look what happens...

**Comment by scherepanov** [comment]
Works just fine for me... I am using Fedora 33 just updated, gnome-shell v 3.38.3
Changes in preferences are reflected in gTile popup on next invocation. No need to login/logout or reboot.
Yes, there is a lost functionality, active grid used to be highlighted, no more. But switch to next grid size with space or mouse works fine.
Not sure why it does not work for you.
Can you re-check with gTile code from master, and at least same version of gnome-shell?
I kinda start hating gnome-shell, I had bug in gTile that I cannot debug/troubleshoot despite several attempts, and at some point after gnome-shell update bugs disappears. That makes me think that it is not really gTile bug but gnme-shell... very hard to prove.

**Comment by scherepanov** [comment]
Confirmed, it is a recently introduced bug into gTile.
@gonzojive Can you look on this?
It appears that tilespec.ts does not have a listener for grid size changes, making it impossible to change grid sizes.
