### ISSUE TITLE
Need a more visible icon when GNOME in light-mode

### ISSUE THREAD

**Issue by jvonhoff** [gTile/gTile#203]
When GNOME is in dark mode, I have no issues with the icon.  It's not as bright as other extension icons, but it's usable.
![image](https://user-images.githubusercontent.com/8107932/112189755-ee70f680-8bc9-11eb-98e5-a7e19fdbe228.png)

However, when switching to light-mode, the icon disappears, and tends to just look like a large spacer on the bar:
![image](https://user-images.githubusercontent.com/8107932/112189863-0f394c00-8bca-11eb-817a-26ee7e555849.png)

Using the command
`sudo mogrify -fill black -colorize 50% /usr/share/gnome-shell/extensions/gTile@vibou/images/launcher_16.png` gets me a usable icon again
![image](https://user-images.githubusercontent.com/8107932/112190190-62ab9a00-8bca-11eb-97b1-b857f4d48cbc.png)

but I have to do this every time the extension is upgraded.  Any way to either check for dark-mode or light-mode, or possibly use a GNOME widget that automatically changes with the theme?  I know Argos does this, as my Argos icons switch perfectly.

**Comment by scherepanov** [comment]
Hmmmm... never look on themes...
Can you do investigation?
My guess, you need a separate set of icons for light theme. Seems to be, you can define icon for apps in theme. This is just an educated guess...
It would be nice if you will find how it works, do some coding and add there support to gTile.
I will gladly accept your PR.

**Comment by scherepanov** [comment]
Done in #227
