### ISSUE TITLE
Support GNOME 40

### ISSUE THREAD

**Issue by loximann** [gTile/gTile#208]
gTile is not compatible with GNOME 40.

**Comment by loximann** [comment]
I added this issue since I could not find any plans to update. I figured other users who sorely miss gTile after upgrading to GNOME 40 could find this and know if something is coming or they should look for an alternative.

**Comment by floriankisser** [comment]
See #205, support is on master, release is pending review, according to last comment.

**Comment by loximann** [comment]
Oh no! I did not notice it was under the closed issues. Sorry for wasting your time!

**Comment by scherepanov** [comment]
Thanks for comment!
Yes, gTile have full support of gnome-shell v40.0, committed to master.
Release is pending review on EGO.
I will keep this ticket open, in case some users will be looking.

**Comment by scherepanov** [comment]
Release is out.
