### ISSUE TITLE
Shortcut customization does not work on gnome 40

### ISSUE THREAD

**Issue by fguerout** [gTile/gTile#209]
Hi, thx for highly useful extension !

On gnome 40, shortcut does not work anymore.
I can correctly assign new shortcuts for "Preset resize 1" to "Super+KP_1" but binding does not work.
I've also tried to configure back to default ("Super+Alt+KP_1") but default binding does not work anymore.

Possibly an issue on key binding with gnome 40 ?

Br,

**Comment by fguerout** [comment]
Additional remark: customized shortcuts seem to only work when "gtile" popup is displayed.

**Comment by scherepanov** [comment]
Yes, it is a feature.
Not to pollute global keyboard shortcuts.
gTile define way too many shortcuts, attempts to squeeze them into Gnome shortcuts were unsuccessful.
There are global shortcuts that works without gTile window displayed, try them.

**Comment by lsgiorello** [comment]
Hi all,

Is there a way to manually disable this feature?
It's pretty frustrating to have every quadrant working perfectly smoothly and get stuck with one specific quadrant you can't have access to because of this.

Otherwise, the app is life saver!
