### ISSUE TITLE
Gradually slowing down while using global expand and contract edges (v.43 only)

### ISSUE THREAD

**Issue by slabko** [gTile/gTile#212]
I use heavily global expand and contract edges without using gTile's pop up window, but after updating to the version 43, I noticed that every next time I expand or contract a window the whole system freezes before resizing that window. It freezes longer and longer every time I expand or contract.

After about 10 such expanding and contacting it freezes for more that 30 seconds before resizing the window and it also utilizes 100% of CPU during that freezing period. The whole system just become unresponsive.

That happens on both Ubuntu 20.04 (Gnome 3.36 on X11) and Fedora 34 (Gnome 40, tried on both X11 or Wayland). Fedora was installed from scratch just to reproduce this bug, no additional configuration or tweaks

I made short recording of the behavior where I try to change the size of Firefox back and forth and you can see that the first about 8 times it resizes relatively quickly but then you can notice how the whole system freezes just by looking at the CPU utilization graph.

![gTile 43 gradual slow down](https://user-images.githubusercontent.com/5012202/117367656-c19b4900-aec2-11eb-8389-f98cce42d5d2.gif)
[The same recording with better quality on YouTube](https://www.youtube.com/watch?v=b77DTRqDmKg) 

A tried to assign different keys on Global contract button edge and Global expand bottom edge: Super+Up and Down, Control+Shift+J and K, Control+Shift+Up and Down, and I still was able to see this behavior.

Let me know if you need any additional information, I would be glad to help.

P.S.: I can't express enough how much I love gTile!

**Comment by scherepanov** [comment]
Can you confirm that slowdown is limited only to global keyboard shortcuts, and not present when you are using regular shortcuts (i.e. with gTile popup)

**Comment by slabko** [comment]
That's right, with the regular popup everything works just fine, even after 10 resizes with global shortcuts, the popup works just fine, including resizing or moving windows. It seems like that problem is only limited to global shortcuts.

**Comment by scherepanov** [comment]
I temporarily lost ability to troubleshoot and debug gTile problems (hopefully not for long).
You can wait till I will be able to look on it, or you can try to look by yourself.

**Comment by slabko** [comment]
Let me see what I can do, I have never worked with gnome plugins not even developed anything for GTK really, but I can try to debug it a bit. Maybe I'll be able to narrow it dawn to the change that brought this bug.

BTW, at the moment I run the version 42, which seem to work perfectly except the settings window in Gnome 40. In case anybody need a work around, you can configure the plugin in version 43 and then roll it back to 42 to avoid this freezing bug.

**Comment by slabko** [comment]
Just a quick update, git bisect suggests that bug appeared in https://github.com/gTile/gTile/commit/ff171094729f45b18a540f2d1bca49f09d1dc395

Will try to look into it, but it might take a while :(

**Comment by scherepanov** [comment]
Very good catch! Big thanks!
I will test and merge on Monday.
Meantime, may be you will have a minute to look on #200?

**Comment by slabko** [comment]
Glad to help! Thank you for taking care of such a good extension!

Will look into https://github.com/gTile/gTile/issues/200, seems a bit more complicated, but I'll try my best!

**Comment by scherepanov** [comment]
Tested your PR, looks good, merged.
This issue is severe enough to justify new release.
What are chances on you to look on #200? I can wait with release little bit if you are going to look on it.

**Comment by slabko** [comment]
I just had some time to reproduce it but unfortunately I haven't had a chance to really figure out what was going on.

Plan to do that by the end of the week, but not sure if I'll be able fix it properly, so I wouldn't hold my breath on getting a good fix this week from me :(

**Comment by scherepanov** [comment]
OK, I released v44 out with this fix.
Will wait for you to look on #200.

**Comment by scherepanov** [comment]
Never heard back, but I have not seen more complaints. Which is a good sign.
Closing this ticket as resolved.
