### ISSUE TITLE
Error installing via gnome extensions

### ISSUE THREAD

**Issue by scottwn** [gTile/gTile#215]
When attempting to install via gnome extensions, I get a ⚠, "Error loading extension", in tweaks -> extensions. Clicking on the ⚠ opens a window with the error' "Unable to find "gTile_vibou"".

**Comment by scherepanov** [comment]
Well... that would be too many reason for this to happen, all in gnome-shell and utilities.
Please try to troubleshoot by yourself.

**Comment by frygge** [comment]
I got the same error message. Not even a hint, how to debug / troubleshoot? Seems, I have to switch over to an alternative :(

**Comment by frygge** [comment]
I kind of found the reason: The new gnome does not support the Array.flatMap function (yet?). I am really no JS expert (or anything close to it), but I managed to read the code a little and build the following workaround:

In Line 376 of the `${HOME}/.local/share/gnome-shell/extensions/gTile@vibou/extension.js`, insert the definition for the Array.flat() function:

```
Object.defineProperty(Array.prototype, 'flat', {
    value: function(depth = 1) {
      return this.reduce(function (flat, toFlatten) {
        return flat.concat((Array.isArray(toFlatten) && (depth>1)) ? toFlatten.flat(depth-1) : toFlatten);
      }, []);
    }
});
```

Then, change the content of the `parseGridSizesIgnoringErrors` function to
```
function parseGridSizesIgnoringErrors(s) {
    return s.split(',').map((part) => {
        const size = parseGridSizeIgnoringErrors(part.trim());
        return size ? [size] : [];
    }).flat();
}
```
It basically replaces the flatMap function with a map(...) and then a flat(...). This works for me. I hope, it helps you as well. Also, I'd like this to be patched by some JS expert (who can actually find a better solution).

**Comment by frygge** [comment]
I just committed a fix. Please verify that it works on other systems as well. It basically applies the patch above in the `tilespec.ts`.

**Comment by scottwn** [comment]
I tried it on my system and I can enable the extension now, the `flatMap` issue is resolved, but when I click on the icon in the toolbar I get an error
```
May 17 17:56:42 li-b5ecb34c-3213-11b2-a85c-dea1703c3a9e.ibm.com gnome-shell[3470]: gTile _onButtonPress Click Toggle Status on system panel [0x55878afa8c60 Gjs_GTileStatusButton.panel-button tiling-icon:first-child last-child hover]
May 17 17:56:42 li-b5ecb34c-3213-11b2-a85c-dea1703c3a9e.ibm.com gnome-shell[3470]: gTile showTiling with fix
May 17 17:56:42 li-b5ecb34c-3213-11b2-a85c-dea1703c3a9e.ibm.com gnome-shell[3470]: gTile hideTiling
May 17 17:56:42 li-b5ecb34c-3213-11b2-a85c-dea1703c3a9e.ibm.com gnome-shell[3470]: gTile Grid hide immediate=false
May 17 17:56:42 li-b5ecb34c-3213-11b2-a85c-dea1703c3a9e.ibm.com gnome-shell[3470]: JS ERROR: TypeError: this.actor.ease is not a function
                                                                                   hide@/home/scott/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:2341:13
                                                                                   hideTiling@/home/scott/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:1159:13
                                                                                   showTiling@/home/scott/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:1063:9
                                                                                   toggleTiling@/home/scott/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:1174:13
                                                                                   _onButtonPress@/home/scott/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:1266:9
                                                                                   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
```

**Comment by scherepanov** [comment]
You cannot really edit master to make it work on older version of gnome-shell.
gnome-shell recently done disruptive changes, it makes practically not possible to have code that run on gnome-shell v 40 and 3.34.
Solution would be to install older version of gTile from extensions.gnome.org.

**Comment by frygge** [comment]
Hmm.. I tried every combination of gnome-shell version 40, 40.0, 3.34 and the corresponding existing extension versions, none of which worked for me. I guess I have to stick with my own patch until my OpenSUSE distribution updates to a new gnome version.
@scottwn: I don't get this message, so I cannot really fix it. Maybe you try the same approach as me: find out what the function does and replace it with your own code.
