### ISSUE TITLE
extension error on GNOME Shell 3.26.2

### ISSUE THREAD

**Issue by mtb-xt** [gTile/gTile#22]
Hello.

For some reason, after the latest update, the extension is broken:
```
Dec 12 11:08:36 shinkiro gnome-shell[1290]: Extension "gTile@vibou" had error: TypeError: format.split is not a function
```
gnome-shell --version
GNOME Shell 3.26.2, Wayland session
extra/gnome-shell 3.26.2+9+ga3736d3a3-1

Archlinux 4.13.12-1-ARCH x86_64

If you need any additional info, let me know.

**Comment by StuntsPT** [comment]
I can't reproduce the problem.
I too am running Arch Linux fully up-to-date, but gTile is working fine here.
What version of gTile are you using?

**Comment by mtb-xt** [comment]
@StuntsPT  latest version from gnome extensions, I've

**Comment by StuntsPT** [comment]
I have just updated to latest master and everything is still working.
Try to disable every other extension and check if the problem persists.
If it works after that, you will have to manually find which extension(s) are causing issues.

**Comment by scherepanov** [comment]
That can be that some configuration is passing null string as format for parsing.
It is either grid sizes, or keyboard presets.
There is bad format handling for keyboard presets that should prevent bad string to be passed, but seems to be it is incomplete. I cannot reproduce it.
Very interesting.
Can you enable debug messages, and post here messages that happens right before error?
Or spot-check your keyboard presets, some unusual wrong format? What are settings for grid sizes?

**Comment by GeeWee** [comment]
For anyone who finds this anicent thread - I had the same issue, but restarting the gnome shell manually solved it.

**Comment by GeeWee** [comment]
Actually that's not what was going on. See the following debug log

```
# parseTuple is called with valid grid
May 19 09:09:42 localhost.localdomain gnome-shell[2063]: parseTuple::: , 4x4, string, x

# parseTuple is called with a.. function called diff? That's not in the std library
May 19 09:09:42 localhost.localdomain gnome-shell[2063]: parseTuple::: , 4x4, string, x
May 19 09:09:42 localhost.localdomain gnome-shell[2063]: gss key:, diff, value, function (array) { return this.filter(i => array.indexOf(i) < 0) }
```

A little creative grepping showed the Extensions Sync library defined this method on the Array prototype..

We could probably avoid it here by using a hasOwnProperty check ala
```js
for(var key in arr) {
    if (arr.hasOwnProperty(key)) {
        ...
    }
}
```

**Comment by scherepanov** [comment]
That is cool
Is this code inside gTile?
If it is inside, can you submit PR?
