### ISSUE TITLE
First super+enter has a reduced name of the target window

### ISSUE THREAD

**Issue by giammi56** [gTile/gTile#223]
system: Ubuntu 20.04 LTS, gTile latest

As in the title. Clicking on another window fixes the problem. The gif explains the behaviour better.

https://user-images.githubusercontent.com/11757284/121818297-8db40000-cc86-11eb-902c-084e292812ce.mp4

**Comment by scherepanov** [comment]
It is a call to set window title. It is same for first click and all subsequent.
My guess, set title is applied to window before window get it size. This is deep inside gnome-shell.
My best guess it is a gnome-shell bug, not fixable on application (I.e. gTile) side. You can put workaround in gTile, which seems to be will be slightly complicated.
My opinion it is a bug in gnome-shell. Best approach would be to wait for a fix.

**Comment by scherepanov** [comment]
It is not reproducable on recent gnome-shell.
