### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by catpea** [gTile/gTile#226]
gTile represents a very unique and extremely important program that feels like an extension to the finger tips, and finally the noise of multiple windows and countless terminals across multiple workspaces can find some order.

Just in case people forget to thank you sometimes, let me be the one to say that all the users are extremely thankful for your program.

You are all brilliant, and beautiful (yes even you)

(I deeply apologize, for creating a non-code issue. But you all must be reminded of your brilliance.)

**Comment by scherepanov** [comment]
Thanks from gTile team!
