### ISSUE TITLE
Visual editor for presets

### ISSUE THREAD

**Issue by MichaelMure** [gTile/gTile#23]
First thing first, awesome extension. I just got a ultrawide screen and it's very helpful.

Random thought: it's rather difficult to edit the presets. `4x4 3:0 3:3` is a bit difficult to understand. Is it a starting point and a size ? Top left and bottom right corners ? Where is the zero, top left or bottom left ?

It would be quite nice to have a visual editor. Something very similar to the window that appear when you click when using `super + Enter`. In my head it would work like this:
- in the "Resize presets" tab, clic to focus on a input field
- the visual editor appear on the right of the same tab. You can still edit the text manually
- if you select an area in the visual editor, the text is replaced by the new configuration

Just a suggestion, feel free to close the issue if it's not wanted. Sadly I won't have time to contribute that ...

**Comment by scherepanov** [comment]
gTile do not have enough usage to justify developing a video editor. It is a very niche extension oriented on geeks. 
Of course if someone will ever decide to develop it he would be very welcome.
There are some words in help about preset config strings, explaining how it counts, from where starts and in what direction. But I agree it is not intuitive, and nowadays if you have to read instructions - it is bad.

**Comment by MichaelMure** [comment]
A simpler short term solution can be:
- more explicit explanation on top of the `resize preset` tab
- when a correct preset is entered, an overlay is displayed in the screen for a second to show the selected area. This shorten a lot the trial/error cycle because you don't have to move an actual window. 

Such an explanation could be like this:
> A preset configuration consist of:
>  - the size of the grid (height x width)
>  - the position of the top left corner of the window, starting at index 0
>  - the position of the bottom left corner of the window, starting at index 0
> Left upper corner is 0:0."

Btw, I think gTile could see more usage in the future because ultrawide monitor are starting to be a thing. That's why I started using it, as far as I know it's the best solution available for gnome.

**Comment by scherepanov** [comment]
Video editor is more involved
Preferences dialog is not related to extension itself and called indepenently. They communicate through "registry" - preferences modifies values, extension can read. 
Signaling between preferences dialog and extension - I do not know how to establish it.
And I do not know how to put handler on change of value in preferences. Flashing of rectangle on screen is also a big question how to implement.

I have no problems put more explanations on top of resize preset tab. Write one, or tell if above explanation is fine.

BTW presets are sorted now in preferences, check last commin on my branch scherepanov/gTile. That was very unobviousness why they were not sorted originally.

**Comment by MichaelMure** [comment]
> tell if above explanation is fine

It seems good to me, that's why i wrote it.

> BTW presets are sorted now in preferences, check last commin on my branch scherepanov/gTile

Awesome :)
