### ISSUE TITLE
Keybinding to center window with full height

### ISSUE THREAD

**Issue by ThanosDi** [gTile/gTile#230]
Is there a way to center a window but in full height?

Since I'm using an ultrawide 38" I'd like a window to be on the center of the screen(1/4, **2/4**, 1/4) but in full height.
But use it with a keyboard shortcut instead of the mouse option.

The closest I could find is to use **super+alt+numpad 5** but it feels like there should be a better way as this will not grow the window in height.

Thank you.

**Comment by scherepanov** [comment]
that is a feature of gTile, you can customize window position and size for each keyboard shortcut.
Got to Preferences, and set corresponding keyboard shortcut.
Read README.md on syntax how you set window size/position/grid size.

**Comment by ThanosDi** [comment]
Thank you very much!
For anyone looking to simulate a 3/9, 6/9, 3/9 column style (starting from 1 :see_no_evil: )  this is my implementation which works like a charm!

The first preset is to snap to the left as a 3/9.
The second preset is to snap to the middle as a 6/9.
The second preset is to snap to the right as a 3/9.

Preset number 4 and 5 is to cycle between these 3 which I bind it to super+alt+right arrow and left arrow 
![image](https://user-images.githubusercontent.com/6170355/132950683-bfef6c89-8441-4861-a5fc-bac0a78105e1.png)

_And as always, a few hours of trial and error can save you several minutes of reading the manual!_
