### ISSUE TITLE
Feature Request: Padding Around all tiled windows

### ISSUE THREAD

**Issue by mtbhuskies** [gTile/gTile#231]
Right now all tiled windows are touching. For nothing more that aesthetics, it would be nice to have a setting to adding a custom pixel padding around all edges of tiled windows.

**Comment by scherepanov** [comment]
That is an existing feature in gTile.
You can have space around all tiles, on screen borders. It is called insets.
Or, you can have padding between tiles.
Both are configurable in settings, and in effect without gTile restart.
