### ISSUE TITLE
Remove deprecated Lang

### ISSUE THREAD

**Issue by scherepanov** [gTile/gTile#233]
From EGO gTile review:

3. Lang is a deprecated module. Please remove it for the next version:
https://wiki.gnome.org/Projects/GnomeShell/Extensions/Review#General_Advice
Learn how to remove Lang from your code:
https://gjs.guide/guides/gjs/legacy-class-syntax.html

**Comment by extremegf** [comment]
I've transisioned the Lang using classes to GObject as they suggested in the tutorial.

Verified working:
- int and text fields
- widget status bar close button
- menubar icon
