### ISSUE TITLE
Error after upgrade

### ISSUE THREAD

**Issue by dorian-marchal** [gTile/gTile#235]
I tried to update this morning and got an error:

![2021-10-11_08-19](https://user-images.githubusercontent.com/6225979/136741913-75283866-75b8-4c0a-8a6a-40186c383eea.png)

```
$ gnome-shell --version
GNOME Shell 3.36.9
```

Notes:
- Someone has the same issue in the extension comments: https://extensions.gnome.org/extension/28/gtile/
- I reinstalled the 3.36/45 version (by following [this guide](https://linuxconfig.org/install-gnome-shell-extensions-from-zip-file-using-command-line-on-ubuntu-20-04-linux)) and it works correctly:
  ![2021-10-11_08-31](https://user-images.githubusercontent.com/6225979/136743112-6e4bd162-1b32-4b7e-9921-99917921f469.png)

**Comment by schnz** [comment]
Closing this issue because it is no longer relevant. for users.
