### ISSUE TITLE
Rounding errors in windows position on large grid sizes

### ISSUE THREAD

**Issue by Flajavin** [gTile/gTile#236]
I have a super-ultrawide monitor (5120x1440) and I use grid size of 25 x 1 in order to create some custom templates with the exact sizes that I need for work. 

I noticed that for this number (seems to work fine if I uses a smaller grid size) the last window on the right doesn't go all the way to the end of the monitor, a space is left there, it's size is about one 20-30px wide.  If I choose to add the taskbar on the left/right then that space is gone, but if I have the taskbar on the bottom/top then that space is left there.  Same if I configure the taskbar to autohide, then that space will still be there so I have to manually resize the last window to fit in place.

I'm on ubuntu 21.04 but I had the same problem on ubuntu 20.04 also.

![gtile](https://user-images.githubusercontent.com/1961646/136911502-0add8f03-ca99-4c52-aa4e-74431c14eb21.png)

**Comment by scherepanov** [comment]
Can you submit PR where rounding error will be fixed, windows do not overlap/no gaps between windows?

**Comment by scherepanov** [comment]
Tagging this issue as a bug - rounding errors on large grid sizes

**Comment by scherepanov** [comment]
Fixed in #266
