### ISSUE TITLE
gtile popup window is not shown properly

### ISSUE THREAD

**Issue by danleepw** [gTile/gTile#237]
![image](https://user-images.githubusercontent.com/10960592/136977174-05219333-88fe-40d6-8b90-f6ef0f71d1ba.png)

OS: Manjaro Linux, 21.1.5
gnome-shell: 1:40.5-1 
gTile: 47

**Comment by danleepw** [comment]
Classic theme is fine. Default, Minimal Dark and Minimal Light have that problem.

**Comment by scherepanov** [comment]
Not reproducable
