### ISSUE TITLE
Toolbar icon doesn't have enough padding

### ISSUE THREAD

**Issue by joulev** [gTile/gTile#238]
This is how it looks like with other icons in my toolbar (or top bar... I don't even know how it's called).

![image](https://user-images.githubusercontent.com/44609036/137127999-0129f73f-92b4-4d2f-9c3e-57929b6f8a8b.png)

All other icons have padding, so they are spaced evenly. However the gTile icon doesn't seem to have it... so it is a bit too close to adjacent icons.

Of course, the extension still works great, and the icon makes it very easy to use the tool, but still this spacing does attract my eyes a lot when I look at the top bar.

---

Distro: Ubuntu 20.04.3  
Gnome 3.36.8  
Theme: Default

**Comment by canerakdas** [comment]
sure, I can look this weekend @scherepanov

**Comment by joulev** [comment]
> Great! Thanks for quick fix! @joulev can you check that new code works properly on your install?
> 
> I am actually curious, why you need to hardcode icon padding as 13 in stylesheet.css, I would expect it to be some system property.

Thanks, can’t check right now but will test it asap tomorrow!

**Comment by canerakdas** [comment]
Thanks for the review @scherepanov ,

I agree about giving static padding. Did some more research and noticed that these paddings were added with the classes named 'system-status-icon' in the extensions I examined. Refactored the code like this.

Could not find a document on this subject that I can take as an example. I'm planning to do some more research or create a simple wiki.

Thanks,
