### ISSUE TITLE
Accelerator's config scrambled

### ISSUE THREAD

**Issue by MichaelMure** [gTile/gTile#24]
It would be less confusing if the series of preset's accelerator would be on proper alphabetic order.

This is what i get now:
![sans titre](https://user-images.githubusercontent.com/294669/34416657-c2b65f62-ebf4-11e7-91c2-2f140383dfc6.png)

**Comment by scherepanov** [comment]
Yes, I know about it, it does not look pretty and I do not like it too. Problem that I have not been able to find how to sort this container. Fix would be to add a line that do a sort on prepopulated container.

**Comment by StuntsPT** [comment]
If these are being read as text strings, a valid workaround would be to replace "resize 1" with "resize 01", etc.
Yes, it is ugly, but should do the trick.

**Comment by MichaelMure** [comment]
It's really weird because the first part retains the order that is in the source code. It's not the alphabetical order.

Only the series of preset is scrambled.
