### ISSUE TITLE
Add tooltip on hover for animation and auto-close icons

### ISSUE THREAD

**Issue by ElijahLynn** [gTile/gTile#240]
As a new user to gTile it took me a while to figure out what the animation and auto-close toggle icons actually did. I had to come back to the readme to figure out what they did. 

I think we should put a hover tooltip on the icons to self-document their functionality. 

![image](https://user-images.githubusercontent.com/1504756/137774820-d975dd75-cdb9-4c1c-9614-99f438a2d556.png)

**Comment by scherepanov** [comment]
Yes, go ahead, your PR will be accepted.
Code should be "reasonably good" and actually working, follow standard approaches etc. No outrageous requirements for code to be accepted.

**Comment by scherepanov** [comment]
Looks like gnome-shell discontinued built-in tooltips support.
Adding tooltips would be much more complicated than it should be.
