### ISSUE TITLE
Fix broken icons in [README.md](https://github.com/gTile/gTile#readme)

### ISSUE THREAD

**Issue by ElijahLynn** [gTile/gTile#242]
Friendly heads up that this PR broke the [README.md](https://github.com/gTile/gTile#readme) icon links > 
![image](https://user-images.githubusercontent.com/1504756/137774391-3f01f566-e2f6-4156-aa6e-06f9107cfea1.png)

They are looking for https://raw.githubusercontent.com/gTile/gTile/master/images/animation-icon-black.png and https://raw.githubusercontent.com/gTile/gTile/master/images/auto-close-icon-black.png.

_Originally posted by @ElijahLynn in https://github.com/gTile/gTile/issues/227#issuecomment-945968485_

**Comment by scherepanov** [comment]
@canerakdas looks like icons need to be fixed in one more place, can you take a look, when you will have a chance?
