### ISSUE TITLE
Feature Request: Individual Overlays per display

### ISSUE THREAD

**Issue by mtbhuskies** [gTile/gTile#243]
I love gTile. The new UI is AMAZING and the functionality is a must-have for Gnome. 

A feature I'd love to see is the ability to have default overlay templates per screen. Right now, it's just a click of a button to change between the two layouts I have, one for horizontal and one for my vertical. Be icing on the cake to be able to set a default per screen.

**Comment by scherepanov** [comment]
You can always submit PR that will implement this feature.
