### ISSUE TITLE
click on panel triggers tiling

### ISSUE THREAD

**Issue by mazerj** [gTile/gTile#245]
I can't reproduce this on demand, but occasionally when I click anywhere in the cinnamon panel all my windows retile following the last gTile mode used. I can't figure out for the life of me what's going on. And since there's no way to undo it, I have to manually restore the layout. I'm about 95% sure this is caused by gTile -- doesn't happen when I have gTile disabled. But because it's so infrequent, it's been impossible to nail down.

Config:
- gTile Version 1.0.0 (2021-09-24 09:44:02)
- pretty much stock Mint 2.0.2 Uma with Cinnamon DE.
- Linux beast 5.4.0-89-generic 100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Any ideas on how to better track this down?

**Comment by scherepanov** [comment]
Wait. Cinnamon is a separate DE and it is not compatible with gnome-shell extensions.
Someone ported gTile to Cinnamon. You are using different code base.
You should find Gtile Cinnamon project and post your question there.
