### ISSUE TITLE
dividing screen by 1/3's 

### ISSUE THREAD

**Issue by irateswami** [gTile/gTile#246]
I have a 49" ultrawide, and I like to divide my screen into 1/3's. The resize presets are not behaving as I would expect. Preset 1 works as expected, and I can change it to the settings of preset 2 or 3 and those work as expected, but preset 2 and 3 do not work on their own. What am I doing wrong? 

![Screenshot from 2021-10-30 07-48-09](https://user-images.githubusercontent.com/40923362/139533471-50b72b62-0722-4292-bc24-4ae9d86974dd.png)

**Comment by scherepanov** [comment]
Typical problem - keyboard shortcut is grabbed by something, and not propagated t gTile.
Preset is OK but not triggered by shortcut.
To check, enable debug logs, try to use keyboard shortcut and see if gTile is getting them.

**Comment by irateswami** [comment]
Okay, that makes sense. I'm fiddling with PopOS on a new System76 machine, some of the nitty-gritty stuff is just different enough from Ubuntu to be annoying.

**Comment by JamesBelchamber** [comment]
FWIW I have this working (same thing, thirds - and quarters - on a 49" super-ultrawide). On vanilla GNOME (Fedora), mind.

**Comment by irateswami** [comment]
> FWIW I have this working (same thing, thirds - and quarters - on a 49" super-ultrawide). On vanilla GNOME (Fedora), mind.

Are you using the same settings as I?

**Comment by JamesBelchamber** [comment]
The ones you've presented, yes. I use Win+Alt+Num1/2/3, works fine :+1:

**Comment by scherepanov** [comment]
Keyboard shortcut is being intercepted by some other system component, not reaching gTil to trigger action.
