### ISSUE TITLE
Please document & make the UI (more) discoverable

### ISSUE THREAD

**Issue by bentolor** [gTile/gTile#251]
Thank you for providing this polished tool to organize our screen real estate. 

One small but major please: Please make the UI (more) discoverably! Sorry – I mostly don't understand the UI at all! It seems to have changed, but that's not the issue. It's just that I don't understand most of the UI semantics and I wasn't even able to find the help! 

![grafik](https://user-images.githubusercontent.com/588260/142718732-0dd43c8a-3c7a-4089-9c0b-2765e7763335.png)

Only after navigating to the extension preferences I was able to access the preferences dialog with a help tab pointing to [`README.md`](https://github.com/gTile/gTile/blob/master/README.md) which unfortunately doesn't seem to help me with my issues.

#### My (constructive) questions based on the UI

1. How do I access the extension preferences?
2. How do I access help? No help-Button. The deskstop icon has no context menu. No menu. No F1. How?
2. What is This AAA-Button doing? i don't see any reaction
3. What is this (i)-Button doing. Or is it a power-Button? No tooltip either.
4. I didn't really understand the mechanics of the both buttons on the lower right; Naively I assumed it would vertical-expand the current window. After more tries I think I get what they are doing but wonder for what it is for.
5. The README doesn't explain anything from above, either.

I think this is really a rather small issue, but I think it's very important for the UX.

**Comment by scherepanov** [comment]
Well.
I kinda agree that it is never enough docs.
Looks like you have a very good list of things that are not clear from docs.
It places you into perfect spot - you know what is wrongs with docs, and you already have a plan how to fix it.
I would suggest that you will address problem. I am not inclined to significantly expands docs - it is already blown up more than I would like.
What about you will create video, or screen capture, where you will put explanations to all issues that you listed above.
We will add a link to this video at the end of docs, under sections - tutorial or something like that.
Go through all use cases in your video, make each feature clearly explained.
If you want, you can post a video on youtube.
FYI 
GUI look did change recently, but functionality remain same. It is merely a theme.
You can go to old GUI look by selecting CLASSIC theme in preferences. This is actually what I did.

**Comment by bentolor** [comment]
Dear, @scherepanov – I find you response &r reaction quite disappointing, to be honest. Given the amount of work which went into my two bug reports, i feel rather not appreciated. 

Regarding the issue: I'm not talking about expanding the documentation, but **_"make the UI more accessible"_ ** i.e., **by providing tooltips.**

Nevertheless: You wrote much text; but would you mind simply answering my questions?

I really DO NOT UNDERSTAND what they do!

**Comment by scherepanov** [comment]
Well.
This project is being run by community.
You see something wrong, or you have some nice idea how to make things better - you do some coding and submit PR.

Here are some answers to your questions:
1) In recent gnome-shell, there is a special software component called Extensions. You run it, it will show you list of installed extensions. go to gTile, click on settings button. You will get Preferences dialog.
2) No help (remember - this is not a commercial software. See my comment above - if you think absence of help is bad, do some coding, submit PR).
3) Aaa button turn on and off animation during window move.
4) i button is toggling GUI autoclose
5) yeah, there is no clear explanations what buttons are doing. One is placing current window to left half of screen, rest windows are stacked on left half. Second arrange all windows in two columns.
6) Yes, README is not very good.

Hopefully, this will help, and you will feel more appreciated :-)

Do not forget, gTile is not the only tiling extension available under gnome-shell. there are plenty more, and most of them by far more simple to use, and typically better documented/supported. I would recommend try other tiling extensions.

**Comment by bentolor** [comment]
Thanks for explaining the functionality in 3) and 4).  That helps. 

Regarding 2) I had nothing more in mind than just opening the Link to the website. 

1) Should be nothing more than a direct link to the settings dialog, i.e. via a cog-Button icon.

Unfortunately [Gnome Shell no longer has no native Tooltip implementation](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/d81958a07498f3076f19e95847345a24e18bdfdd). Which is a bummer to address the obscurity of the button semantics…

**Comment by bentolor** [comment]
I also don't understand where the `text` property is getting lost in [`function ToggleSettingsButton(text, property)`](https://github.com/gTile/gTile/blob/master/app.ts#L1876). This would already have helped in the first place.
