### ISSUE TITLE
gTile only displays 4 characters of window title ("Fir…"); full title after focus change

### ISSUE THREAD

**Issue by bentolor** [gTile/gTile#252]
Hi there! Thanks for creating gTile!

I have a really small issue: On opening gTile in the popup windo it only shows the first 4 character of the window title.

![Bildschirmfoto von 2021-11-20 08-54-01](https://user-images.githubusercontent.com/588260/142719067-c30c6de6-1764-4b22-8142-4cbd875e1c88.png)

Strange: After clicking back and forth to another window (focus change) the title appears fully. 

Something about the size calculation?

**Comment by scherepanov** [comment]
There is no calculations - code is calling function setTitle(<window title>).
What you see is clearly a bug in gnome-shell. 
Typically this kind of bugs will suddenly disappear after some system upgrade. Or, start behaving other, sometimes unpredictable, ways.
