### ISSUE TITLE
Request: name the default shortcuts

### ISSUE THREAD

**Issue by beck** [gTile/gTile#256]
**As is**

The README is super helpful because it provides a description of the default shortcuts.

When updating the defaults, it is not immediately clear these are referencing Preset resize 1-9.

When updating the defaults (in my use case, I'm new to gTile and I'm updating the keybinding to match muscle memory), it is easiest to keep the readme open to translate what each preset does (vs hopping between tabs and parsing the grid coords).

**Request**

Name Presets 1-9 using the "description" from README

**Comment by scherepanov** [comment]
Well.
If you think docs (i.e. README) is not clear on some aspects, go a head, edit it and submit a PR.

**Comment by scherepanov** [comment]
There are three things 
1) Name of accelerator as displayed on preferences screen
2) Keyboard shortcut that is assigned to accelerator (may be not assigned, i.e. disabled)
3) Action that accelerator is causing, like windows position and grid size.
I have impression, you are looking on descriptive name for action. That can be displayed next to accelerator, and configurable by user.
I should note, default keyboard binding serving more like  a demo what can be done by gTile. In no way it should be considered as something that you never change. We are encouraging users tp do their own configuration of presets.
Also, it is possible we will release saving and loading configuration to/from file. Potentially, you will see completely different presets configurations, depending on what config file you will load.

Preset names in preferences are hardcoded. Changing them to match default configuration would be very wrong.

I would suggest that adding descriptive name to actions in preferences dialog would nicely address your concerns.

Do some coding, submit PR. Your contribution will be appreciated by gTile user community.

**Comment by scherepanov** [comment]
Works as designed
