### ISSUE TITLE
Add support for Main in vertical screen... Thanks

### ISSUE THREAD

**Issue by fretelweb** [gTile/gTile#257]
I am working with code and invert the logic in case width i less than height in the workarea but I can make it work... I off and on the extension but nothing happens...

Please, please add this feature...

**Comment by fretelweb** [comment]
Never mind!! it works after reboot... but it would be interesting to add to the repository

**Comment by fretelweb** [comment]
function AutoTileMain() {
    let preset = "AutoTileMain";
    log("AutoTileMain");
    let window = getFocusApp();
    if (!window) {
        log("No focused window - ignoring keyboard shortcut AutoTileMain");
        return;
    }
    reset_window(window);
    let mind = window.get_monitor();
    let work_area = getWorkAreaByMonitorIdx(mind);
    const monitors = activeMonitors();
    let monitor = monitors[mind];
    let workArea = getWorkAreaByMonitor(monitor);
    let notFocusedwindows = getNotFocusedWindowsOfMonitor(monitor);
    if (Object.keys(notFocusedwindows).length === 0) {
        moveResizeWindowWithMargins(focusMetaWindow, workArea.x, workArea.y, workArea.width, workArea.height);
        return;
    }
    log("SETTINGS_MAIN_WINDOW_SIZES:" + mainWindowSizes);
    let ps_variants = mainWindowSizes;
    log("Main window sizes: " + ps_variants);
    // handle preset variants (if there are any)
    let variantCount = ps_variants.length;
    if (variantCount > 1) {
        if ((lastResizeInfo.lastCallTime.getTime() + gridSettings[SETTINGS_MAX_TIMEOUT]) > new Date().getTime() &&
            lastResizeInfo.presetName === preset.toString() &&
            lastResizeInfo.windowTitle == window.get_title()) {
            // within timeout (default: 2s), same preset & same window:
            // increase variant counter, but consider upper boundary
            lastResizeInfo.variantIndex = (lastResizeInfo.variantIndex + 1) % variantCount;
        }
        else {
            // timeout, new preset or new window:
            // update presetState.last_preset and reset variant counter
            lastResizeInfo.variantIndex = 0;
        }
    }
    else {
        lastResizeInfo.variantIndex = 0;
    }

    if(workArea.width > workArea.height)
    {
        let mainRatio = ps_variants[lastResizeInfo.variantIndex];
        let mainWidth = workArea.width * mainRatio;
        let minorWidth = workArea.width - mainWidth;
        moveResizeWindowWithMargins(focusMetaWindow, workArea.x, workArea.y, mainWidth, workArea.height);
        let winHeight = workArea.height / notFocusedwindows.length;
        let countWin = 0;
        log("AutoTileMain MonitorHeight: " + monitor.height + ":" + notFocusedwindows.length);
        for (let windowIdx in notFocusedwindows) {
            let metaWindow = notFocusedwindows[windowIdx].meta_window;
            let newOffset = workArea.y + (countWin * winHeight);
            reset_window(metaWindow);
            moveResizeWindowWithMargins(metaWindow, workArea.x + mainWidth, newOffset, minorWidth, winHeight);
            countWin++;
        }
        log("AutoTileMain done");
        lastResizeInfo.presetName = preset;
        lastResizeInfo.windowTitle = window.get_title();
        lastResizeInfo.lastCallTime = new Date();
        log("Resize preset last call: " + lastResizeInfo.lastCallTime);
    }else{
        let mainRatio = ps_variants[lastResizeInfo.variantIndex];
        let mainWidth = workArea.height * mainRatio;
        let minorWidth = workArea.height - mainWidth;
        moveResizeWindowWithMargins(focusMetaWindow, workArea.x, workArea.y,workArea.width, mainWidth);
        let winHeight = workArea.width / notFocusedwindows.length;
        let countWin = 0;
        log("AutoTileMain MonitorHeight: " + monitor.height + ":" + notFocusedwindows.length);
        for (let windowIdx in notFocusedwindows) {
            let metaWindow = notFocusedwindows[windowIdx].meta_window;
            let newOffset = workArea.x + (countWin * winHeight);
            reset_window(metaWindow);
            moveResizeWindowWithMargins(metaWindow,newOffset, workArea.y + mainWidth,  winHeight, minorWidth);
            countWin++;
        }
        log("AutoTileMain done");
        lastResizeInfo.presetName = preset;
        lastResizeInfo.windowTitle = window.get_title();
        lastResizeInfo.lastCallTime = new Date();
        log("Resize preset last call: " + lastResizeInfo.lastCallTime);
    }
}

**Comment by scherepanov** [comment]
I am not very sure what you were trying to achieve.
If you want to modify gTile behavior, submit PR!
You will need to add settings in Preferences, to enable modified behavior, default disabled.
