### ISSUE TITLE
Remember app windows locations on logout, start all apps and put windows to corresponding position on login

### ISSUE THREAD

**Issue by scherepanov** [gTile/gTile#258]
This is request from user on EGO.
My immediate reaction was - this is way out of gTile scope.
But, after some thinking, this is exactly what I am doing every time after login. I am starting all apps that I am using every day, and I place app windows into same position they are always present. 

Soooo....

Why not?

**Comment by pikiou** [comment]
I'm doing the same every day, and so are millions of users I'm sure.
It'd encourage people to shut down their computers rather than put them to sleep, which would overall save a lot of power and pollution.

**Comment by scherepanov** [comment]
Surprisingly, latest Fedora that I am running on my desktop, does nto have this feature - save all windows and their positions/sizes on logout, and start on login.
Search on internet show - that was a feature in a past. Seems to be, did not work up to expectations, and was removed.

Thinking more about it .... feature is clearly outside of scope of gTile. If gnome-shell does not provide it, should be done in separate gnome-shell extension.

For login/logout every night, for purpose of being greener. Correct solution is to suspend your PC (called hibernate on Windows). In this mode, dump of memory is being written to a file, and PC shutdown. On PC start, memory dump is restore, system continue from savepoint, including all apps, along with open windows/their positions.

Suspend is greener than PC shutdown/startup, as procedure is completely automatic and does not require manual actions. IT is greener because automated procedure plain faster than manual key pressing and mouse moving.

If you really want world to be greener, encourage people to suspend and never logout.
