### ISSUE TITLE
How to stack all windows and auto tile without hot keys?

### ISSUE THREAD

**Issue by narkeeso** [gTile/gTile#259]
I was trying to create a preset that stacks all windows in the workspace, is it possible? I tried setting 2x2 0:0 1:1 but that just stacks one window. I also tried doing it with the Main auto tiler and setting the ratio to 1 or 1.0 and that also only makes 1 window take up the entire grid.

Also is it possible to toggle a mode where the tiling is done without any user intervention or hot keys?

**Comment by scherepanov** [comment]
gTile by concept is a user-driven tiling assistant. It will not be able to do tiling on it's own, without user input.
There is an autotiling function to arrange all windows on monitor in n columns or n rows, where n between 1 and 10. This autotiling is working only by keyboard shortcuts, no GUI.
