### ISSUE TITLE
Allow auto tile shortcut to be global like with the presets

### ISSUE THREAD

**Issue by asteinba** [gTile/gTile#263]
Hey,
I couldn't find a issue which already asked for that so I thought I will open a new one. I really love the auto tiling and the resize presets shortcuts feature and I use both of them a ton. One thing that bothers me a bit is that I have to bring up gtile to use the auto tiling shortcuts while I am able to use the resize preset shortcuts directly/globally because I activated the "Global resize presets" option.

I think a  "Global auto tiling shortcuts" option would be really handy :).

**Comment by scherepanov** [comment]
Good idea.
Do some coding, submit PR. It is not much work.

**Comment by asteinba** [comment]
Great that you are open to it! Never did gnome extension development but always wanted to try it. Will do it in the next few days, when I have some spare time.

**Comment by scherepanov** [comment]
Thanks! Will check.
