### ISSUE TITLE
New window size not retained anymore

### ISSUE THREAD

**Issue by agners** [gTile/gTile#267]
Since a few days windows resized with gTile started to act weird: Resizing them to a particular size works fine, but when changing the window they jump back to the previous size.

I did not update gTile, but I did a system upgrade (which presumably updated other Gnome components). I am using Gnome 41.3 with Wayland windowing system on Arch LInux.

After the behavior started, I did update gTile to latest version 48 as well as master branch, but the issue remains in both versions.

Could that be a local setting/configuration (I don't remember changing anything though) or is something broken with latest Gnome components?

**Comment by derekkraan** [comment]
I have the same issue, upgraded this morning (arch) and I am finding that the window size / location goes back to the previous when another window gets focus.

**Comment by scherepanov** [comment]
Well. Latest gTile release V48 on EGO is more than month old. If you are having issues with installing V48, it points to problems with gnome-shell.
In past, I found that attempts to address problems in gnome-shell on gTile level are unsuccessfull. Then, after new gnome-shell release, suddenly everything works fine.
Though, I would encourage you to try to find workaround in code.
FYI I do not have any problems you are describing, though I am on latest Fedora and have not upgraded for month or so.

**Comment by agners** [comment]
Thanks for the insight.

From my logs my ArchLinux system upgraded `gnome-shell` from `41.2-2` to `41.3-1` on 2022-01-12, and on `41.1-1` -> `41.2-2` on 2021-12-27. I am pretty sure that it worked fine earlier this year, so I'd guess it must have been `41.3-1`. I am a bit hesitant to install older gnome packages, but might give it a try later today.

**Comment by DenagaKomadina** [comment]
41.2 seem to work on both x11 and wayland (if i remember correctly)

41.3 works ok on x11, but does not on wayland

**Comment by ebudan** [comment]
Just upgraded Fedora 34 -> 35, which updated to Gnome 41.3 (Wayland). 
Observing the same as others above.

**Comment by Leleat** [comment]
This is a mutter bug. There is already an issue open for it. Try thumbing it up. It might get some attention there.

https://gitlab.gnome.org/GNOME/mutter/-/issues/2091

**Comment by lamarios** [comment]
i made a PR for the changes on the wintile extension. by just calling the method twice...

https://github.com/Fmstrat/wintile/pull/75

Maybe you guys ca give t a try for gtile too

**Comment by Leleat** [comment]
> i made a PR for the changes on the wintile extension. by just calling the method twice...

I think it works for some windows (for some reason 😂)... but not for all. For example, gnome-text-editor or the extension's prefs get restored again if another window is focused... Maybe try tiling different windows and see if you can reproduce the issue again.

**Comment by lamarios** [comment]
hmm, you're right. Looks like it doesn't work for GTK4 apps, Video Trimmer and Extension Manager

**Comment by hermidalc** [comment]
I am also getting this issue on Fedora 35, since the last batch of Fedora updates that came last night. Updates to `kernel-5.15.14`, `gnome-desktop3`, 'gnome-shell`, `mesa-*`, `mutter`, etc. gTile was working perfectly before this.

**Comment by scherepanov** [comment]
gTile code move all windows ins same way. Should be no difference in moving/resizing  GTK4 apps on an other.

We had bug in past, when window sometimes does not react properly on keyboard shortcut. Workaround was to call move function twice, in different way. That works fine for everybody until now.

I do not have access to PC with latest gnome-shell yet.
Can we have a volunteer who will play with code and will find working solution.

There are 3 places in code where window is actually being moved, search for move_frame.
There is an additional call to move_frame each time, to address issue.

Example would be function moveWindowToRect (app.ts, line 1402)

function moveWindowToRect(window: any, rect: tilespec.Rect) {
    // The move_frame line is a workaround for a bug affecting gnome terminal
    // windows. See https://github.com/gTile/gTile/issues/176#issue-751198339.
    window.move_frame(true, rect.origin.x, rect.origin.y);
    window.move_resize_frame(
        true,
        rect.origin.x,
        rect.origin.y,
        rect.size.width,
        rect.size.height);
}

It is possible that workaround mentioned above - double call to window placement - will actually work.
Please post results of your investigation here.

**Comment by alexfouche** [comment]
On Fedora 35, i did not have to downgrade `gnome-shell`. I only downgraded `mutter` to `dnf downgrade mutter 41.0`

**Comment by scherepanov** [comment]
Great! This is exactly as I expected.
Bug is in mutter for GTK4.0 apps. Downgrading mutter to 41.0 fix problem.
I highly doubt anything can be done on gTile side to address issue. Just sit and wait till it will be fixed.
It will help if everybody will bump up underlying gnome-shell issue.

**Comment by Leleat** [comment]
There is also a mutter MR to introduce a workaround (which hasn't been merged yet); see https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2238

It's already fixed in GTK for GTK4; see https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4394.

**Comment by derekkraan** [comment]
I upgraded mutter just now on Arch and this is working again!

**Comment by agners** [comment]
I can confirm, on Arch Linux, with the update of `mutter` to package version `41.4-1`, the problem is gone.

I assume for other distribution the update to 41.4 will resolve the problem as well.

Thanks, I think this issue can be considered closed here.

**Comment by hermidalc** [comment]
While the issue wrt to mutter has been resolved, there seems to have been a change in the way gTile processes resize preset dimensions? Here's one of my presets:

96x64 0:0 44:33, 45:0 95:33, 0:34 44:63, 45:34 95:63

Before the mutter issue this used to make 4 gnome-terminals that would fill my desktop without any gaps except for a very small one between the top left and top right terminals (requiring only a small manual adjustment on the left side of the top right terminal, but this is understandable given how gnome-terminal has to size relevant to the terminal font and your screen resolution)

But now the bottom two terminals, which used to tile perfectly without any gaps, are now quite a bit off:

![Screenshot from 2022-02-20 09-53-05](https://user-images.githubusercontent.com/461066/154848612-67f540f1-bfa5-4185-bc51-0adaf771d5e6.png)

**Comment by hermidalc** [comment]
And if I take for example a non gnome-terminal app, e.g. gedit, and use the size presets if fills better without gaps except the bottom, which before the mutter issue and update used to fill without gaps:

![Screenshot from 2022-02-20 09-58-01](https://user-images.githubusercontent.com/461066/154848827-b78315e2-4bff-4bf5-9343-6e6e952de73e.png)

**Comment by scherepanov** [comment]
Please open new ticket about gaps.
