### ISSUE TITLE
Incorrect resizing when top bar is hidden

### ISSUE THREAD

**Issue by rcywongaa** [gTile/gTile#28]
When using gTile with extensions that hide top bar, e.g. https://extensions.gnome.org/extension/545/hide-top-bar/, gTile does not take into account the extra desktop space from the hidden top bar.

**Comment by scherepanov** [comment]
My bet, you are using stock gTile available from extensions.gnome.org.
Current master on github contains fix for this issue. New version of gTile with fix is pending review on extensions.gnome.org. Review is taking forever, already sitting for month and half without moving there, and I have no way to speed it up.
Please check if gTile from master branch is fixing this issue (it should). 
I will keep this issue open till you will confirm if it is fixed or not.

**Comment by JasoonS** [comment]
I'm getting an error when installing gtile from GitHub:
![image](https://user-images.githubusercontent.com/6032276/36585765-de7300c4-1887-11e8-89e7-c225424e6f3b.png)

It works fine if I install from gnome.

I would be happy to tell you the error if you explain how to access it.

**Comment by scherepanov** [comment]
To see log of errors
Start new Gnome session
sudo journalctl
You will see a bunch of log entries. Get strings that have gTile in them:
sudo journalctl | grep gTile
Remove all entries with timestamp before last login (i.e. from current session only)
Post here, will check what is wrong.

**Comment by JasoonS** [comment]
Reboot fixed it, thank you for your help @scherepanov !

**Comment by rcywongaa** [comment]
@scherepanov You are correct, gTile from master branch fixed the issue.  Thanks for your time!
