### ISSUE TITLE
User-defined shortcuts does not work after upgrade

### ISSUE THREAD

**Issue by scherepanov** [gTile/gTile#280]
New version of gTile code introduce breaking change.
We are numbering tiles starting from 1, instead of 0.
Numbering tiles from 1 allow to distinguish between 1 and -1 (tile number from opposite side).
User-defined shortcuts will stop working if definition contain 0, for example 0:2.
Rest of user-defined shortcut will be shifted by 1 to the left/up.
You need to change your custom shortcut, increase by 1 all coordinates.
For example, 4x4 0:1 2:2 need to be changed to 4x4 1:2 3:3.
Predefined shortcuts will continue to work correctly.

**Comment by okoponen** [comment]
Maybe good idea to implement a migration process for this? Defaults can be recognized and migrated automatically (or seen, if these are not user-presents. Others, pretty much search and replace
s/(\d+):(\d+)/$1+1:$2+1/g

Would make life just that much easier...

**Comment by scherepanov** [comment]
Well… migration is not hat easy.
You cannot guarantee it to run once.
And what to do if upgrade jump over versions.
After some considerations, migration never attempted.

**Comment by okoponen** [comment]
if (migrationNotDone) {
  // migration
  migrationNotDone = false
}

If automation proves difficult, a button to do this manually would have been great. Now, the system just fell apart for no obvious reason

**Comment by scherepanov** [comment]
Probably, you are right.

**Comment by tvannahl** [comment]
Thank you for opening this issue, It did help me to quickly migrate. I don't know anything about the way gTile is storing persistent data, maybe it is a good idea to introduce versioning for the way gTile persists configuration? This would help to maintain migrations in the future.

**Comment by scherepanov** [comment]
I think this breaking change is clearly mismanaged, definitely should be done better.
In future, will be no changes that require migration.

**Comment by ltshb** [comment]
I'm using gTile for about 6 month and was very happy with it where I could easily manage my windows on my big wide screen. For my needs I created my custom preset which is why I used gtile because I could defined my presets. I felt very disappointed this morning after upgrading that it wasn't working anymore until I found this issue here.
Now I have to changes all my presets, again quite disappointing not have any automated way to migrate them. Doing manually is error prone and annoying, especially that I took for a little while ago quite some time to configure them as I wanted and now I need to changes all my 30 presets again.
In software breaking changes should be always avoided and when not should be better communicated without having to search on Internet. E.g. a Warning message in the gtile preset settings with a migrate button would have been great !

**Comment by TheReincarnator** [comment]
As a suggestion for the future: Keep a flag or version number inside your config, so you know what migrations are still pending. This is a well-established process and covers all of the above cases, fully automatic.

Something like this, where "version" is that hidden number in the config.

```
if (version < 2) {
  migrateTo2();
  version = 2;
}
if (version < 3) {
  migrateTo3();
  version = 3;
}

```

**Comment by antonio24073** [comment]
Hi,
I can't to do the search and replace because my 
./.local/share/gnome-shell/extensions/gTile@vibou/schemas/org.gnome.shell.extensions.gtile.gschema.xml 
isn't the same than my resize presets (kept the old preset even thought reinstall or delete the "gTile@vibou" folder)

**Comment by antonio24073** [comment]
Thank you @okoponen.
I'm sharing my conf. I've been using it for a long time and it's been very productive for me.
`[/]
action-contract-bottom=['Pause']
change-grid-size=['space']
debug=true
grid-sizes='4x4, 6x4, 6x6'
preset-resize-10=['<Shift><Super>KP_Divide']
preset-resize-20=['<Shift><Super>KP_Multiply']
preset-resize-30=['<Shift><Super>KP_Subtract']
resize-down-vi=['<Shift>j']
resize-left-vi=['<Shift>h']
resize-right-vi=['<Shift>l']
resize-up-vi=['<Shift>k']
resize1='4x4 1:3 2:4, 1:3 1:4, 1:3 3:4,  1:2 3:4'
resize10=''
resize11='3x2 1:2 1:2, 1:2 2:2'
resize12='3x2 2:2 2:2, 1:2 3:2'
resize13='3x2 3:2 3:2, 2:2 3:2'
resize14='3x2 1:1 1:2, 1:1 2:2'
resize15='3x2 2:1 2:2, 1:1 3:2'
resize16='3x2 3:1 3:2, 2:1 3:2'
resize17='3x2 1:1 1:1, 1:1 2:1'
resize18='3x2 2:1 2:1, 1:1 3:1'
resize19='3x2 3:1 3:1, 2:1 3:1'
resize2='4x4 1:3 4:4,2:3 3:4,2:3 2:4,3:3 3:4'
resize20=''
resize21='3x3 1:3 1:3,1:2 1:3,1:3 2:3, 1:2 2:3'
resize22='3x3 2:3 2:3, 2:2 2:3, 1:3 3:3, 1:2 3:3'
resize23='3x3 3:3 3:3, 3:2 3:3, 2:3 3:3, 2:2 3:3'
resize24='3x3 1:2 1:2, 1:1 1:3, 1:2 2:2,1:1 2:3'
resize25='3x3 2:2 2:2, 2:1 2:3,1:2 3:2, 1:1 3:3'
resize26='3x3 3:2 3:2, 3:1 3:3, 2:2 3:2, 2:1 3:3'
resize27='3x3 1:1 1:1, 1:1 1:2, 1:1 2:1, 1:1 2:2'
resize28='3x3 2:1 2:1,2:1 2:2,1:1 3:1,1:1 3:2'
resize29='3x3 3:1 3:1, 3:1 3:2,2:1 3:1, 2:1 3:2'
resize3='4x4 3:3 4:4,4:3 4:4, 2:3 4:4,2:2 4:4'
resize30=''
resize4='4x4 1:1 2:4,1:1 1:4,1:1 3:4'
resize5='8x8 1:1 8:8, 3:1 6:8, 3:1 4:8, 5:1 6:8'
resize6='4x4 3:1 4:4,4:1 4:4,2:1 4:4'
resize7='4x4 1:1 2:2, 1:1 1:2, 1:1 3:2, 1:1 3:3'
resize8='4x4 1:1 4:2,2:1 3:2,2:1 2:2,3:1 3:2'
resize9='4x4 3:1 4:2, 4:1 4:2, 2:1 4:2, 2:1 4:3'
set-tiling=['Return']
theme='Minimal Dark'`

**Comment by brettbatie** [comment]
Based on the above comments here is the one-liner I ran to upgrade my config file.

```bash
dconf dump /org/gnome/shell/extensions/gtile/ | perl -p -e "s/(\d+):(\d+)/(\$1+1).':'.(\$2+1)/ge" | dconf load /org/gnome/shell/extensions/gtile/
```

**Comment by ca-scribner** [comment]
I don't know where to better publicise this, but I suggest a way be found.  It is both a really unexpected change and also silent - took me a while of searching about dead shortcuts before accidentally finding this page.  I'd guess there's plenty of others in the same situation.  

Might be worth a large banner at the top of the main github readme tbh.

**Comment by scherepanov** [comment]
Good idea. Added to README.md reference to this thread..

**Comment by snrkl** [comment]
Agreed on the breaking and undocumented nature of this change taking me totally by surprise.. I discovered it while on a video conference and screen sharing, when my window control from macropad stopped working..  😛

That being said, I also don't believe in complaining with FOSS - thank you @scherepanov @gonzojive @canerakdas and all the other contributors for an awesome app.. 

I for one know I totally appreciate it!

**Comment by ca-scribner** [comment]
Oh yeah totally - this tool is greatly appreciated.  thanks!!

**Comment by mopore** [comment]
Unfortunately, @brettbatie's one-liner did not work for migrating my configuration. Though dumping, manually editing, and reloading did the job.
Here we have a use case for <Ctrl+A> in VIM to increase the number under the current cursor by 1 (if not caught by global keybinding  :smirk: )

**Comment by mehaase** [comment]
> Well… migration is not hat easy.

Maybe if any preset contains zero (which is invalid after this change, right?) then you could display an alert and link to this page?? I haven't used my Linux machine very much recently and I thought I had _forgotten_ my accelerator shortcuts because they weren't working. Took me quite a while to trace it down to this GitHub issue.

Like @snrkl said, I'm not complaining, :heart: gTile, thank you @scherepanov!

**Comment by scherepanov** [comment]
I agree migration to new version has been mismanaged.
Yes, that would be great to implement - display warning on preset containing zero.
As well, it would be great to implement other features. I believe it is quite possible to make gTile by far more useful.
In next life, I will do it all.
