### ISSUE TITLE
Gtile broken after update: requires PackageKit??

### ISSUE THREAD

**Issue by oreinert** [gTile/gTile#283]
After upgrading gTile to the latest version, the extension can no longer be enabled. Instead, I get this error message:

    Error calling StartServiceByName for org.freedesktop.PackageKit:
    Unit packagekit.service is masked

Yes, I have masked packagekit on my system, because I really don't want to do upgrades that way. However, the real question is, why does gTile care that PackageKit is running now?

GNOME: v3.34.5
gTile: v48

**Comment by scherepanov** [comment]
Never heard about package kit...
Only place where external dependency listed is in yarn.lock, required by bazel build.
And, it is not there.
Also... very first thing gTile is doing on enable call is to print "gTile enable" in log. Enable debug, check logs, my bet you will not see it. That points to problem before even calling gTile code.
My opinion is that dependency on PackageKit is dragged by gnome-shell itself.
