### ISSUE TITLE
Windows tile under ubuntu dock if placed left or right

### ISSUE THREAD

**Issue by pmarshallase** [gTile/gTile#29]
So far I'm very impressed with this!
The only remaining niggle for me is that windows tile under the dock if it is placed vertically left or right. If it is bottom-aligned, then it seems to work ok.

**Comment by JMurph2015** [comment]
Potentially try using the insets panel to tweak the margins around the screen.  I know it isn't ideal, but I don't think we've fully come up with a strategy to dynamically sense other extensions/panels and their locations.  However, I will probably make an issue to make left and right panel quick settings.

**Comment by pmarshallase** [comment]
That probably works well enough for me for now. I had messed with that setting but without effect - but hadn't done the "Alt-F2  r". Thanks!

**Comment by Zeka13** [comment]
@JMurph2015 your solution with static margins will not work correctly on second monitor with no dash to dock panel, right?

**Comment by scherepanov** [comment]
That should be working automatically on primary and secondary monitors with code from master branch. Margins not needed to make it work.
Can you install from master and tell me if it works properly.
gTile with new code is pending approval to be on extensions.gnome.org, as soon as approved you will be able to install straight from there.

**Comment by Zeka13** [comment]
@scherepanov AWESOME, rly works! Much thx!

**Comment by scherepanov** [comment]
New version of gTile have been reviewed yesterday and now officially available from extensions.gnome.org.
It is current master branch. No need to directly install gTile any more, you can just upgrade. You will have to logout/login for new code to take effect.
