### ISSUE TITLE
Make the window decoration to use square corners if they tiled by gTile

### ISSUE THREAD

**Issue by hron** [gTile/gTile#291]
Gnome 42 allows to tile two windows by dragging a window to a screen edge. When it does that the window decoration is changed from rounded corners to square ones. I think it makes sense for gTile to change the window decoration of a window which is tiled the same way.

Before screen-edge tiling:
![image](https://user-images.githubusercontent.com/39293/164682803-c62eb16b-0060-4485-85c0-a64d27d0619a.png)

After:
![image](https://user-images.githubusercontent.com/39293/164682825-108d9211-dccd-4d93-924a-772104252a13.png)

**Comment by scherepanov** [comment]
I am not sure why you would want to change window decorations for tiled windows.
But I do understand that people are different can can have personal preferences.
Why not.
Write some code, submit PR. 
Keep current behavior as default, add one more settings to Preferences that will turn on new behavior.

**Comment by hron** [comment]
Well, this is something Gnome ships by default, so I think I'm not alone who finds this type of decoration for tiled windows preferable. ;]

Anyway, I would love to help, but my knowledge about Gnome APIs is basically zero. I have tried to find some API call I can use to toggle the window property related to decorators, but without any luck. I was trying to search here: https://gjs-docs.gnome.org/meta5~5_api/meta.window#property-decorated

I wonder if you can provide any references to the docs of Gnome APIs I could use?

**Comment by scherepanov** [comment]
I used to look for Gnome API, and it was very hard to find answers.
It should be better now.
Just look on internet for gnome-shell extension development.

**Comment by scherepanov** [comment]
Closed due to lack of activity.

**Comment by fourclever** [comment]
The lack of square corners and, as a consequence, the ability to dock one window to another without gaps forced me to eventually switch to a manager that was less convenient to manage. The terminal built into GNOME is very rarely placed evenly and equally - leaving a gap sometimes smaller, sometimes larger. The background is visible in the spaces - sometimes this is distracting.

**Comment by schnz** [comment]
> The lack of square corners and, as a consequence, the ability to dock one window to another without gaps forced me to eventually switch to a manager that was less convenient to manage. The terminal built into GNOME is very rarely placed evenly and equally - leaving a gap sometimes smaller, sometimes larger. The background is visible in the spaces - sometimes this is distracting.

This was discussed a while ago in #336. See https://github.com/gTile/gTile/issues/336#issuecomment-1836116641 for an explanation on why this wasn't implemented in gTile. The discussion starts with this comment, in case you want to read the whole conversation: https://github.com/gTile/gTile/issues/336#issuecomment-1805308235

The TL;DR; is that if you want to maximize windows vertically, use the Gnome build-in shortcuts <kbd>&lt;Super&gt;+&lt;Arrow&gt;</kbd>
