### ISSUE TITLE
Can this be ported to MacOS?

### ISSUE THREAD

**Issue by MikeyBeez** [gTile/gTile#292]
I miss this fantastic tiling add-on in MacOS.  Would it be tough to port?  Where might one start?

**Comment by scherepanov** [comment]
Yes it can be ported to MacOS!
You probably need to start from scratch, as nothing in gTile codebase is possible to port to MacOS.
What you can port is an idea how it works, and this arguably most important part.
How tough it will be? Depends how handy you are with MazOS!
