### ISSUE TITLE
May Cause System Crash When Hangup on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by FinleyGe** [gTile/gTile#296]
I installed gTile on extension.gnome.org.
And when my laptop is going to hangup, the system crashed. (Which is means can not hangup, and I must force shutdown)
Version: 50
The system I use: Ubuntu 22.04 LTS 
Desktop Environment: X11

**Comment by scherepanov** [comment]
That would be very hard to troubleshoot remotely.
Unless you will find something in logs.
You pretty much on your own.
