### ISSUE TITLE
Gaps around windows similar to i3 etc

### ISSUE THREAD

**Issue by Heclalava** [gTile/gTile#299]
Is there any way to get gaps around windows similar to i3 etc? Can this be modified by changing a config file? If not is this a feature that can be built in?

**Comment by scherepanov** [comment]
There are gaps around windows, size of gaps are controlled in Preferences.
Also, you can set border around screen, separately for prime monitor and for other monitors. Again, in Preferences.

**Comment by Heclalava** [comment]
> There are gaps around windows, size of gaps are controlled in Preferences. Also, you can set border around screen, separately for prime monitor and for other monitors. Again, in Preferences.

Ok unfortunately the way it's implemented in Linux Mint there's no settings for gaps. That's why I was asking. 

I ended up switching from Cinnamon back to XFCE in the end to apply a theme with window gaps.
