### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by StuntsPT** [gTile/gTile#3]
Since we are at this, I would recommend adding automated unit tests.
This will on the one hand ensure that code works as intended and on the other hand, allow for an extra automated checking on PRs.
At least for starting I'd recommend linting all the code with "standard.js" and setting up TravisCI with an automated testing. This is just a linter, but later on other unit tests can be added.
I would gladly volunteer to do this - at least implementing the linter and TravisCI integration. I'm not proficient enough in JS to make "real" unit tests.

**Comment by StuntsPT** [comment]
So, after some testing, it seems that "standard.js" is not adequate for GS extensions, since a lot of "undeclared" code is used (eg. "imports").
Anyone got any more suggestions for a uniform style?
The linter has even pick up a lot of places where tabs and spaces are mixed up...

**Comment by jwarkentin** [comment]
I use eslint at work. I'll have to try and set something up. The code definitely needs some cleanup though. Also, I 100% agree we need automated testing. Most of my experience with unit tests in JS is with Jasmine but I'm open to whatever testing framework we decide on. I know Mocha + Chai has traditionally been a pretty popular option too. I just want good mocking support.

**Comment by ColinHarrington** [comment]
What does unit testing look like for a gnome-shell-extension?

**Comment by scherepanov** [comment]
Have no clue how to make unit tests for gnome shell extensions

**Comment by StuntsPT** [comment]
At least two things can be tested:
1. The return values of each function;
2. The code style (using an automated linter);
Since this is becoming a community project, both are very important to have.

**Comment by scherepanov** [comment]
As soon as pending PR will be applied, automated testing would be nice to implement.

**Comment by StuntsPT** [comment]
True, I'm just not sure how to work around some of the linter issues with gnome-shell integration.
Someone with a lot more JS experience than me will have to check that out.

**Comment by cwh1te** [comment]
We might need to go through and initialize variables for all the imports that the linter complains about. That way we can also hook in some better error handling in the process in case something in the Gnome API changes (which is a common complaint I've seen among extension developers).

**Comment by StuntsPT** [comment]
@cwh1te won't doing that actually mask any errors due to an API change?
But I suppose the only alternative to that is to run GS on the CI test server. =-)
Does Gnome provide some form of stub framework for extension testing?

**Comment by JMurph2015** [comment]
Just looking around at this conversation, maybe we try to section off the core parts of the extension, like calculating window placement, and such, into functions that work independently of gnome-shell.  Then refactor out a layer that interfaces with gnome-shell.  That way we could easily unit test at least some of the code.
