### ISSUE TITLE
Is there anyway to have snap to corner functionality?

### ISSUE THREAD

**Issue by ericcurtin** [gTile/gTile#301]
Gnome 3 by default allows you to snap left and right of screen. But other DE's like XFCE or Windows (like MS Windows), let you snap to corners, particularly useful on like 4k screens. Can gtile do this by placing a window in the corner?

**Comment by scherepanov** [comment]
gTile comes with pre-configured keyboard shortcuts, almost all of them are placing window in one of corners.
That serves a way to snap windows to corner.
You can configure shortcut to cycle window through several sizes, while staying snapped to corner, there is one example that is showing how to do it.

**Comment by ericcurtin** [comment]
Sorry I should have clarified, I meant in a https://extensions.gnome.org/extension/3733/tiling-assistant/ style, like that the plugin would detect when close to corner?

**Comment by scherepanov** [comment]
gTile is not intended to be used with dragging windows by mouse.
It is oriented for use with keyboard, with some functionality for window placement with help of mouse.
You need to use other tiling extensions, like tiling assistant, to get what you want.
