### ISSUE TITLE
Terminal window not moving in Linux Mint 21

### ISSUE THREAD

**Issue by david-it** [gTile/gTile#302]
On Linux Mint 21 Vanessa the gTile extension works very well, except for the terminal windows.

Terminal windows get resized but they do not move.

![Peek 2022-09-05 09-52](https://user-images.githubusercontent.com/11480070/188397408-42c71b7a-932a-4a29-880e-2c0ba8eee66e.gif)

I do not notice this behavior with any other application at the moment.

I've used for a short period Linux Mint 20.3 and I didn't notice this behavior. I've fresh installed Linux Mint 21 (did not upgrade).

Some system information via `inxi`:

```log
System:
  Kernel: 5.15.0-47-generic x86_64 bits: 64 compiler: gcc v: 11.2.0
    Desktop: Cinnamon 5.4.11 tk: GTK 3.24.33 wm: Mutter vt: 7
    dm: LightDM 1.30.0 Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Graphics:
  Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
    vendor: XFX Pine driver: amdgpu v: kernel pcie: speed: 16 GT/s lanes: 16
    ports: active: DP-2 empty: DP-1,DP-3,HDMI-A-1 bus-ID: 28:00.0
    chip-ID: 1002:731f class-ID: 0300
  Device-2: Microsoft LifeCam HD-3000 type: USB
    driver: snd-usb-audio,uvcvideo bus-ID: 3-2.1.4:12 chip-ID: 045e:0779
    class-ID: 0102
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,radeon,vesa gpu: amdgpu display-ID: :0
    screens: 1
  Screen-1: 0 s-res: 5120x1440 s-dpi: 96 s-size: 1354x381mm (53.3x15.0")
    s-diag: 1407mm (55.4")
  Monitor-1: DisplayPort-1 mapped: DP-2 model: Samsung LC49G95T
    serial: <filter> res: 5120x1440 hz: 120 dpi: 109
    size: 1190x340mm (46.9x13.4") diag: 1239mm (48.8") modes: max: 5120x1440
    min: 720x400
  OpenGL: renderer: AMD Radeon RX 5700 XT (navi10 LLVM 13.0.1 DRM 3.42
  5.15.0-47-generic)
    v: 4.6 Mesa 22.0.5 direct render: Yes
```

**Comment by scherepanov** [comment]
From what I know, linux Mint is running Cinnamon desktop, and gTile there has a different codebase maintened by different people in different repo.
Problem is that extension on Cinnamon also named gTile, which makes for big confusion.
You need to find correct repo where to post your quesiton.

**Comment by david-it** [comment]
Thanks, I didn't know. The right repository is [cinnamon-spices-extensions](https://github.com/linuxmint/cinnamon-spices-extensions/tree/master/gTile%40shuairan).
