### ISSUE TITLE
Global "Autotile Main" shortcut not working when gTile window is not open

### ISSUE THREAD

**Issue by enisb00** [gTile/gTile#305]
Hello, I've been having trouble trying to use a global shortcut for the "Autotile Main" function however "Autotile main" works fine if the gTile window is opened and the other "Autotile N cols" functions work as global shortcuts when bound.

It seems as though the shortcut is captured but nothing happens and no windows are tiled/moved.

After enabling debugging I can see the following in `journalctl` upon trying to use a global shortcut for "Autotile Main":
```
Sep 26 00:07:20 user gnome-shell[1501]: gTile AutoTileMain
Sep 26 00:07:20 user gnome-shell[1501]: gTile SETTINGS_MAIN_WINDOW_SIZES:0.5,0.625,0.75
Sep 26 00:07:20 user gnome-shell[1501]: gTile Main window sizes: 0.5,0.625,0.75
Sep 26 00:07:20 user gnome-shell[1501]: JS ERROR: TypeError: metaWindow is null
                                                _getInvisibleBorderPadding@/usr/share/gnome-shell/extensions/gTile@vibou/extension.js:1611:21
                                                moveResizeWindowWithMargins@/usr/share/gnome-shell/extensions/gTile@vibou/extension.js:1640:56
                                                AutoTileMain@/usr/share/gnome-shell/extensions/gTile@vibou/extension.js:2185:32
                                                key_bindings_auto_tiling<@/usr/share/gnome-shell/extensions/gTile@vibou/extension.js:985:31
```

I assume this is not intended behaviour as the other "Autotile" shortcuts work as intended?

For extra info I'm running Gnome 42.5 and gnome-shell-extension-gtile-git from the AUR.

**Comment by scherepanov** [comment]
That is definitely a bug.
I am on ancient gnome-shell 3.36, and it works fine on me.
If you have time, you can trace what is going on.

**Comment by enisb00** [comment]
Ah ok, good to confirm. I'll see if I can make sense of the problem (no guarantees though having never touched a gnome extension).

For extra general info this issue occurs in both X11 or Wayland environments.

**Comment by scherepanov** [comment]
On second though, it is a bug in logic.
metaWindow is an obscure name for handler to gTile popup. It is absolutely should not be used when popup (i.e. gTile window) is not open. during keyboard shortcut.
It used to work properly, not sure when this bug was introduced.

**Comment by notpeelz** [comment]
I'm also hitting this problem on GNOME 43 (Arch).

I'm not familiar with the codebase at all, but after a bit of fiddling, I managed to get it in some working state. I have no idea what's going on with the global variables or what they're used for, but this seems to "work":
```diff
--- extension.js	2023-02-24 15:44:40.201659678 -0500
+++ extension.js.patched	2023-02-24 15:45:03.038552543 -0500
@@ -2141,16 +2141,17 @@
 function AutoTileMain() {
     let preset = "AutoTileMain";
     log("AutoTileMain");
     let window = getFocusApp();
     if (!window) {
         log("No focused window - ignoring keyboard shortcut AutoTileMain");
         return;
     }
+    focusMetaWindow = window;
     reset_window(window);
     let mind = window.get_monitor();
     let work_area = getWorkAreaByMonitorIdx(mind);
     const monitors = activeMonitors();
     let monitor = monitors[mind];
     let workArea = getWorkAreaByMonitor(monitor);
     let notFocusedwindows = getNotFocusedWindowsOfMonitor(monitor);
     if (Object.keys(notFocusedwindows).length === 0) {
```

**Comment by yllekz** [comment]
Yep same problem. "Super + G" either gets stuck, freaks out, or straight up does not work unless the Extensions window is open.

**Comment by scherepanov** [comment]
Will check

**Comment by scherepanov** [comment]
Please check latest code.
Let me know if it works.

**Comment by enisb00** [comment]
Seems to work now, thanks for the fix!
