### ISSUE TITLE
Option for overlapping window margins

### ISSUE THREAD

**Issue by zzzachzzz** [gTile/gTile#306]
It would appear that with window margins, adjacent windows utilize the margin of each window. Meaning that with a window margin of 25, the actual gap between two adjacent windows is 50.

Below is a screenshot with that configuration; no margins set aside from a window margin value of 25. The result is that the gap between two adjacent windows is greater than the gap between a window and the edge of the desktop.

I understand this is intended behavior. This is simply a feature request to enable window margins to "overlap" one another, rather than "double up".

![Screenshot from 2022-10-02 14-53-37](https://user-images.githubusercontent.com/14324200/193476123-85def563-6d56-4797-8fa7-aa1d89f66173.png)

**Comment by scherepanov** [comment]
Left-right-top-bottom margins on "margins"  tab in preferences are serving exactly this purpose - add margins to the border of screen.
You should be able to get margins the way you like.

**Comment by zzzachzzz** [comment]
My goal is not to remove the margins between windows, rather it is to make the margins between windows *the same* as the margins around the border of the screen. To be more specific, I want the gap between two windows to be "shared".

Right now the behavior is:
Left window with margin on its right side + Right window with margin on its left side = the two margin widths combined

**Comment by scherepanov** [comment]
There are two settings - margin between windows, and margins around screen edge.
Combining margins around screen edge with margin between windows will make it look the way you want.

**Comment by zzzachzzz** [comment]
Ahh yes, you are right. After setting those all to the same value it does look correct. Thank you!

Would you be open to a PR adding documentation to the readme on margins, with this configuration included for achieving equal gaps?
