### ISSUE TITLE
GNOME 43 "The extension is incompatible with the current GNOME version" fix.

### ISSUE THREAD

**Issue by InnocentZero** [gTile/gTile#307]
When updating to gnome 43, gnome's extension manager displays `The extension is incompatible with the current GNOME version`. To fix this, navigate to `~/.local/share/gnome-shell/extensions/gTile@vibou/metadata.json` and add 43 in the list of shell versions.
```json
"shell-version": [
    "3.36",
    "3.38",
    "40",
    "41",
    "42",
    "43"
  ],
  ```
This fixes the compatibility issue and the extension works as intended.

**Comment by scherepanov** [comment]
Yes, should put new version on EGO.
Will do later tonight. Thanks for reminder!
