### ISSUE TITLE
Work flawless on Wayland but has some bugs on x11

### ISSUE THREAD

**Issue by KnightKrusty** [gTile/gTile#309]
I switched to x11 because there were multiple issues with wayland, the extension work without any issue on wayland but on x11, when i select the grid item it does not select the grid and mouse click trigger element of application in the backgroud... if i am resizing the browser window it will click some button on webpage instead of the grid on the extension window, which make it unusable on x11..

**Comment by scherepanov** [comment]
That is a gnome-shell bug.
Try upgrade gnome-shell, problems can be gone.

**Comment by KnightKrusty** [comment]
I am on fedora 36, everything is updated to latest available.

**Comment by scherepanov** [comment]
We had similar problems in past.
Gnome-shell api should be working same way on x11 and wayland. Apparently it is not.
Typically there is no direct way to fix this kind of problems on gTile side. You can find workaround those bugs. And then suddenly on next gnome-shell version it works fine.
I am not a big fan of trying to troubleshoot gnome-shell

**Comment by KnightKrusty** [comment]
ohh, i just bought an ultra-wide monitor and  your extension is really awesome for partitioning on big display...

**Comment by scherepanov** [comment]
Yes, gTile is very well suited for large monitors.
Use wayland!
