### ISSUE TITLE
Save position

### ISSUE THREAD

**Issue by sojjan1337** [gTile/gTile#319]
Be able to save windows position.

When lock my computer and login again the window positions sometimes changes.

It Would be great if there was a feature where you could save a state and then restore all the windows with a short-key command.

Found something similar but this is old:
https://extensions.gnome.org/extension/4833/all-windows-saverestore-window-positions/

**Comment by scherepanov** [comment]
Looks like that functionality is outside gTile.
It is better be implemented as separate extension, similar to what you mention.
