### ISSUE TITLE
Add shortcut for AutoTile

### ISSUE THREAD

**Issue by Algram** [gTile/gTile#32]
Hi, thanks for the great extension!

I would really like to use a keyboard shortcut for the AutoTile feature, is that possible or does it already exist?

Thanks!

**Comment by scherepanov** [comment]
mmm... I do not believe autoTile is very useful. Do you really using it? Results of autotiling usually a big mess on a screen.

**Comment by Algram** [comment]
Yes, in fact it is the only feature I use from gTile.

**Comment by scherepanov** [comment]
Well, all people are different.
I will look on making autotile configurable from user side, and add keyboard shortcuts.
Hopefully I will be able to make something usable.

**Comment by deconvolutional** [comment]
Just wanted to add another vote for this feature.  For many users coming from a dynamic tiling window manager, automatic window layout is most natural way to manage windows, and is sadly missed in Gnome Shell.  I use gTile entirely for this feature, but without a keybinding it is a little awkward to use; adding it would be awesome ;-).

**Comment by scherepanov** [comment]
I added keybindings for AutoTile - <Super>1 - 0 (total 10 presets).
They are active only when gTile window is active, i.e.visible.
First two keybindings are mapped to two autotiling buttons, rest of keybindings are same as second button, only have more columns.
For example, if you managed to open 64 terminals on screen, pressing <Super>KP_Enter and then <Super>8 will make huge nicely arranged matrix of 8x8 terminals.
I do not want to spoil global keybinding space, and keybinding works only when gTile activated by clicking onicon, or calling gTile keyboard shortcut <Super>KP_Enter

**Comment by deathtrap512** [comment]
__ 1581593053800
