### ISSUE TITLE
Clicking problem in X11

### ISSUE THREAD

**Issue by ali-safapour** [gTile/gTile#320]
The gTile window's buttons are not clickable. If I click on them, It does not affect the gTile window. Instead the click happens on the window behind the gTile window. This problem only occurs when I am using X11. When I use Wayland, everything is OK.

System Specifications:
Ubuntu: 22.10
GNOME: 43
The gTile Version: 51

https://user-images.githubusercontent.com/91371249/214433182-8363c15c-920a-4446-a85d-c7542d0f380c.mp4

**Comment by scherepanov** [comment]
That, unfortunately, a gnome-shell problem.
Usually this kind of problem appear in some version of gnome-shell, then disappear.
I tried in past to troubleshoot similar problem, spent a lot of time to nothing, only to find it works properly after some OS updates.

**Comment by scherepanov** [comment]
Not a gTile bug
