### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by poddus** [gTile/gTile#321]
I use this extension every day and it makes my life much easier. I've made it my goal this year to reach out to the smaller projects whose OSS I use regularly, because I think you deserve more acknowledgement than you may receive.
If you have a paypal or opencollective or similar, I'd be happy to make a donation. Barring that, I'd appreciate if you would recommend some other project that you think has earned a donation in your stead.

and for what it's worth: thank you very much for what you do

**Comment by scherepanov** [comment]
Thanks for a nice words!
