### ISSUE TITLE
Question: How could I backup my gTile keyboard accelerator configuration settings?

### ISSUE THREAD

**Issue by debajit** [gTile/gTile#322]
I've set up several keyboard accelerators for gTile, and I'd like to be able to use this on my other machines. 

1. Is there a way I could backup or export my existing gTile settings?
2. Where is the current configuration stored? (I looked in ~/.config but could not find any gTile references there)

**Comment by scherepanov** [comment]
See #121 
There is  a workaround described there, you can export gTile settings in gnome-shell. This is one of reasons why settings export-import never been implemented.
