### ISSUE TITLE
Gnome 44 support

### ISSUE THREAD

**Issue by fossrob** [gTile/gTile#323]
Hi!

FWIW I've been the current release (after disabling extension version validation) for a couple of days on Gnome 44 RC via Fedora 38 Beta and so far it's been fine for me 👍🏻 

❤️ the extension thank you!

**Comment by ijuma** [comment]
Do you plan to release a new version with this change?

**Comment by scherepanov** [comment]
If Fedora 38 out?

**Comment by ijuma** [comment]
@scherepanov Fedora 38 is in the release candidate stage, but Gnome 44 was already released (https://release.gnome.org/44/).

**Comment by lucabotti** [comment]
released yesterday.

**Comment by scherepanov** [comment]
New gTile v 52 published to EGO yesterday.
