### ISSUE TITLE
gTile basically crashes and disables multiple keys becoming borderline malware.

### ISSUE THREAD

**Issue by ShayneWilliams** [gTile/gTile#325]
I'm running linux mint 21.1, with cinnamon version 5.6.8. As the title says, every once in a while when using the keyboard shortcut for gTile to open it, it won't open, and it will basically permanently disable the keys 1-4, the spacebar, and even the enter key(as well as some others most likely). I'm assuming this is any key that works directly with this app. Because the enter key is basically disabled, it basically becomes a form of wildly effective malware, because you can't even write commands into your terminal at that point. Not even the virtual onscreen keyboard will work when it comes to those keys. Interestingly enough (this is probably specific to my OS) but it seems that you can still type all of the keys into the menu panel that you open with super key. I guess this is to allow you to find your "system monitor" or something, and then there technically I'm sure you could kill the app if you even knew the pid for it (though I don't).

**Comment by scherepanov** [comment]
This is wrong place for this bug report - Cinnamon gTile is a separate codebase derived from this project.
Sorry I cannot point you to Cinnamon gTile project.
