### ISSUE TITLE
[Feature request] Move/resize/position window between monitors using Super-G without mouse

### ISSUE THREAD

**Issue by KaKi87** [gTile/gTile#326]
Hello,

It is possible to :
- **move** a window **between** monitors using Super-Shift **without** mouse ;
- **resize/position** a window on the **same** monitor using Super-G **without** mouse ;
- **move/resize/position** a window **between** monitors using Super-G **with** mouse ;

But it is not possible to : **move/resize/position** a window **between** monitors using Super-G **without** mouse.

e.g., using 2×2 grids, if the top-right area is focused, then pressing Arrow Right, will focus then top-left area of the next monitor.

Therefore, I am hereby requesting this.

Thanks

**Comment by scherepanov** [comment]
You need to use two shortcuts - move window to dest monitor, then resize.
I am doing it all the time on multi-monitor setup, works with or without mouse.

**Comment by KaKi87** [comment]
I know and I mentioned it. But, with that feature, only **one** shortcut would be needed.
