### ISSUE TITLE
Gnome 44 Release

### ISSUE THREAD

**Issue by JamesBelchamber** [gTile/gTile#327]
Hey, could we get a release that includes commit 6087d6c? I don't see any open issues/PRs referencing Gnome 44 so I assume it's just not been released yet? Thanks :)

**Comment by yktoo** [comment]
A workaround for the impatient: edit the file `~/.local/share/gnome-shell/extensions/gTile@vibou/metadata.json` and add `"44"` to the list:

```json
```
  "shell-version": [
    "3.36",
    "3.38",
    "40",
    "41",
    "42",
    "43",
    "44"
  ],
...
```

Then restart the shell (Alt+F2 → r → Enter on Xorg) or the session.

**Comment by scherepanov** [comment]
Released.
extensions.gnome.org now reports total number of download per extension, gTile at moment of releasing v 52 had 516596 downloads.
It is interesting to see how many downloads will be in a week, that will allow to estimate gTile user base - my best guesstimate is that number of downloads is around half of actual gTile installations.
