### ISSUE TITLE
Configuration is (partially) lost in gnome 3.28

### ISSUE THREAD

**Issue by illywo** [gTile/gTile#33]
Hi there,

just noticed that the configuration of "Presets" and "Grid sizes" is lost after closing the configuration dialog in gnome 3.28. The "AccIelerators" work just fine, however. Is there another way to set those configurations directly in a config file, maybe. I swept through them but could not find anything obvious.

Cheers

**Comment by scherepanov** [comment]
Looks like it works properly in gnome-shell 3.26
May be, it is a bug in 3.28.
You can manually edit configuration by editing schemas/org.gnome.shell.extensions.gtile.gschema.xml
Next you need to compile schema glib-compile-schema schemas
Disable/enable gTile should pick up new settings, but may be you will need to relogin or even restart. There is a cache for schema on system level and I do not know how it works and how to clean it correctly.

**Comment by JMurph2015** [comment]
@illywo, I'm going to need some more help reproducing your issue.  So far I tried grabbing a fresh installation of gTile from this repo, then attempting to change the settings you mentioned (in particular the grid sizes setting).  Then I restarted gnome-shell (as almost all of our config changes require), and the new settings were reflected as expected.  Thus without further details, I'd say it works as expected with Gnome 3.28.0 (my current version).  Let me know if there is anything else I should try to reproduce this with.

**Comment by illywo** [comment]
Thanks for the follow up. I dont seem to be able to reproduce this myself. There must have been some kind of weird behavior for some reason. My initial workaround was to close the configuration dialog and - before opening the dialog again - disabling and enabling the extension which seems to work fine. 

But now it is just working fine and as expected.
