### ISSUE TITLE
Set keyboard shortcuts?

### ISSUE THREAD

**Issue by switzel** [gTile/gTile#334]
This seems a silly question but: is it possible to manually reconfigure the keyboard shortcuts (using the GUI)?

The readme seems to suggest "yes" using the "Accelerators" tab while the tabs are called "Hotkeys", "Behavior" and "Layout". I'm assuming "Hotkeys" used to be called "Accelerators" and the keyboard shortcuts used to be configurable but are not in the current version?

**Comment by scherepanov** [comment]
Accelerators tab still there, no Hotkeys or Behavior or Layout.
I suspect you are using some fork of gTile that has same name. May be Cinnamon?
