### ISSUE TITLE
When I use multiple monitors, the tiling often only works on one monitor.

### ISSUE THREAD

**Issue by kongty** [gTile/gTile#335]
When I use multiple monitors, the tiling often only works on one monitor.
If that happens, opening gtile again doesn't resolve the issue.
The only solution is to tile window on the monitor that works, and tile it again to the monitor that I want.

I am using Ubuntu 22.04, gTile v52.
I haven't tested it with other OSes, so I am not sure if it only occurs on Ubuntu 22.04 or not.

Thanks.

**Comment by scherepanov** [comment]
That most likely a bug in gnome-shell.
Usually after some upgrade everything start working.
