### ISSUE TITLE
Adding limit to grid size

### ISSUE THREAD

**Issue by K4R7IK** [gTile/gTile#337]
So while tinkering around with the settings, I found the following bug. 

## BUG

- Set grid size to a very large number. (for my case: 1920x1080)

## Effects

1. This cause gnome-shell to crash and not respond.
2. After restarting, one isn't able to log back in.

## FIX
- open a TTY session, then delete the extension. 
- After removing the extension, open dconf editor and change the schema value back to default, as deleting the extension doesn't remove some settings changes.

**Therefore, it would be great if a limit is place over what grid size user can define.**

---

**Some extra information**: Only deleting the extension will not fix the system. It will be usable but when user will redownload the extension it will set its grid size back to the give value (1920x1080). This result in going and resetting/deleting the preference of gtile via dconf.

**Comment by scherepanov** [comment]
Yes, it is known problem.
gTile GUI dynamically creates and destroys two grids of windows, one for pop-up and one for full screen. For grid 100 x 100, it will be 2000 windows. This is as much as gnome-shell can handle. Larger grid sizes renders gnome-shell very lagging, and finally on very large size most likely it runs out of memory and crashes.
Practically usable grids are up to 30 x 30.
There is a limit of 100 x 100 for grid size on reading settings. Not sure how you were able to set more granular grid. Will check.

**Comment by scherepanov** [comment]
That is right, limit on grid size during settings parse has been lost on class refactoring.
Will issue a fix.
