### ISSUE TITLE
Merge major changes in bazelify branch?

### ISSUE THREAD

**Issue by gonzojive** [gTile/gTile#34]
I have some fairly significant changes in a the [bazelify branch of my fork](https://github.com/gonzojive/gTile/tree/bazelify). Would the gTile maintainers be interested in a pull request? I could also fork the project.

Non-user-visible changes:
1) Conversion to TypeScript
2) Introduction of a Bazel-based build
3) Unit tests and a [Travis project](https://travis-ci.org/gonzojive/gTile)

User-visible changes:
1) A cycling capability. Hitting a resize preset is now defined by a list, like "`2x2 0:0 1:0,1x3 0:0 0:0, 1x3 0:0 0:1, 1x4 0:0 0:2`". The current window is matched against the "tile specs" of the list, and the next spec is used to move the window.
2) If a window is resized that shares an edge with another window, the other window is also resized.
```
 ____________
|     |      |
|  A  |  B   |
|     |      |
|_____|______|

Expanding A also expands B, as in
 ____________
|       |    |
|  A    | B  |
|       |    |
|_______|____|
```
3) A command to move a window to the next monitor. (I couldn't find a good built-in way to do that.)

**Comment by scherepanov** [comment]
Looking on your branch, no doubts pull request is welcome.
I have reservation about adding new functionality. gTile should not suddenly change how window move/resize works.
I suggest that you changes for 2 would be incremental for users. By default gTile will have current behavior. If "cooperative resize" is enabled, that your additional functionality will be working.
If you still think that your implementation of moving widows between screens still needed, do same - by default disabled, and have setting that enables it. Or, leave keyboard shortcut for moving window between screens unassigned by default, and suggest in README to assign some shortcut to enable.
I send you invite to gTile team. You will be owner as soon as your branch will be merged into master.
Another suggestion would be to use different shortcut for "cooperative resize". Right now, arrows move window, shift-arrows resize. What about control-arrows do "cooperative resize", alt-arrows do "cooperative move"? That would keep existing functionality intact, and smoothly add your new "cooperative" actions.
Looking forward to see your pull request.

**Comment by JMurph2015** [comment]
I really appreciate that you added tests.  That's something this org has been "meaning to do" for a while now, but most of us got busy with work and school, so it's been a challenge to give this codebase the TLC it needs beyond bugfixes and tracking Gnome compatibility.  I'll try to take a look at your branch when I get a chance, and the main concern I have is managing the Git history of such a large transition (not sure how you migrated to TypeScript, but props for doing it).

**Comment by JMurph2015** [comment]
Also, I'm going to go ahead and proactively "pull the pull request", so we can move the discussion there.

**Comment by gonzojive** [comment]
Thanks for the replies. I will try to get to the pull request in the next few weeks. I'm glad we can merge these things together instead of maintaining forks.

I'm happy to move some features to new branches or add configuration options.

I'd also like to split some of the new TyepScript code into its own mini library with an Apache 2 or MIT license. A lightweight way to do that is creating a new directory in the project with a separate license. Perhaps that's too messy. Do either of you have thoughts?

**Comment by scherepanov** [comment]
fmueller pointed out that Gnome is GPL v2, and extension should be same.
To upload extension to extensions.gnome.org, you need to accept statement that code is released under GPL v2.
We had a big discussion about licensing when gTile project setup. It appears with Gnome you do not have much of a choice.
Not sure how it will work with library being released under different license.
