### ISSUE TITLE
Please participate in beta-testing for gnome-shell v45

### ISSUE THREAD

**Issue by scherepanov** [gTile/gTile#342]
We did a full rewrite for new version of gTile for gnome-shell v 45.
Please participate in beta-testing.
Install gTile from #341 . Installation instructions in PR.
Submit positive test results in this ticket. Only positive, no bugs!
Submit bug reports to #336 - bug reports only!
We are interested in testing on gnome-shell v < 45, please let us know how it works. New code should be mostly compatible with some old versions of gnome-shell.

**Comment by marinierb** [comment]
Awesome! Installing it now!

**Comment by commarla** [comment]
I am using it for a few hours and it works fine for me. My usage is <Super>+Enter and resize the windows with arrows / Shift.

Thanks for the work :+1:

**Comment by phineas42** [comment]
Works great for me. I was initially bit by the "some windows resize but don't move" bug, but you've already fixed it. Thanks!
My usage is strictly hotkey-snapping, mostly gnome terminal, to grid locations.

**Comment by marinierb** [comment]
BUG?
There are two preset actions that are not working as expected for me. Not sure what their names are but in **dconf**, the keys are labeled **action-autotile-main** and **action-autotile-main-inverted**.
When only two windows are open these actions should put the windows side by side, each at full height of the screen. Instead, I get one window full height, and the other half-height as if there was a third phantom window present.

**Comment by scherepanov** [comment]
Please submit bug report to #336

**Comment by marinierb** [comment]
Created issue https://github.com/gTile/gTile/issues/343
Phantom window for "action-autotile-main" and "action-autotile-main-inverted"

**Comment by nostra83** [comment]
Just installed it, and looks good so far. I'm using mainly the default shortcuts with Alt+CMD+Numpad Numbers (or something similar, I am using keyboard macros :smile: )

Thanks for the work. :clap:

**Comment by axkg** [comment]
Finally my Numpad works again 😌 Thanks a bunch!

Note that I had to 
`export XDG_CACHE_HOME=~/.cache`
before installing the extension as my cache was set to a tmpfs by default and there is a [known issue with gnome-shell](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2821) when the cache and installation directories are on separate filesystems.

**Comment by ji-cerny** [comment]
Works very well. Thanks.

**Comment by mopore** [comment]
Works with the full functionality I used before (insets missing but already known)

**Comment by kamil-karkus** [comment]
Works well on ubuntu 23.10. Thank you for amazing work.

**Comment by schnz** [comment]
@kamil-karkus : According to my mail box you experienced some issues, yet I cannot find that comment anymore (only in my mailbox). Turned out to be something else?

> 1. When I activate super + enter the grid doesn't close automatically.
> 2. Phantom window on clean ubuntu 23.10 when I press super + enter right after unlocking. You can also reproduce this after minimize all the apps.
> 3. I'm almost sure I could use modifier like alt or shift for super + enter to increase/decrease windows size.

**Comment by kamil-karkus** [comment]
> @kamil-karkus : I am curious. According to my mail box you experienced some issues, yet I cannot find that comment anymore (only in my mailbox). Turned out to be something else?
> 
> 
> 
> > 1. When I activate super + enter the grid doesn't close automatically.
> 
> > 2. Phantom window on clean ubuntu 23.10 when I press super + enter right after unlocking. You can also reproduce this after minimize all the apps.
> 
> > 3. I'm almost sure I could use modifier like alt or shift for super + enter to increase/decrease windows size.
> 
> 
For 1st issue I found setting in preferences.
2nd was caused by desktop icons ng extension.
3rd I have no idea but after reboot it works just fine. So I decided to delete the original comment because there's no real issue on Ubuntu 23.10.

**Comment by SteveGoodenough** [comment]
Working well for me so far on 23.10, ultrawide screen (so this plugin is invaluable for my normal 25% (slack) 50% (dev) 25% (terminal etc) or 50% (dev) 50% (web) layouts. Keyboard only use seems perfect. You folk are the biz!

**Comment by enricojonas** [comment]
Just tested - works fine for me as well on ultrawide screen. It has kept the old config, perfect!

**Comment by JulianDabbert** [comment]
Just successfully tested backwards-compatibility of beta on Debian12 (Gnome 44), no problems observed. Good job!
