### ISSUE TITLE
Spacing between windows is `2 * window-spacing`

### ISSUE THREAD

**Issue by luksa** [gTile/gTile#347]
When I set `window-spacing` to `20`, the spacing between two windows ends up being `40` pixels. 

Here's an example where both `insets.top` and `window-spacing` are set to `20`. The horizontal spacing is twice as large as the insets.
![Screenshot from 2023-11-16 13-21-05](https://github.com/gTile/gTile/assets/823581/378be870-a2ce-44f2-91c5-2f11f7e5e135)

**Comment by schnz** [comment]
Yes, spacing is additive. I kept the behavior from the original extension here (where it was called "margin", as you know). 

Do you have a suggestion on how to implement spacing non-additive? In particular, how to deal with odd-values spacing values? Spacing is added on an individual per-window basis without the context of a grid or tiles or relative window position/size. So the current implementation wouldn't work for odd-values spacing values (e.g. 1px spacing would cause a window to be offset -0.5px to the left which doesn't work). All other implementations that I can think of would make cause complications, more coupling, and add complexity.

**Comment by scherepanov** [comment]
Old gTile address issue by having additional separately managed margin around screen edges.
You set screen margin and window spacing to same value, and you go same size spaces between screen edge and windows.

**Comment by schnz** [comment]
In the rewrite, window spacing (formally window margin) does no longer apply towards screen edges. See #345  for the discussion. The idea from @luksa was to have a configuration scheme like this:

 ![](https://user-images.githubusercontent.com/3457747/282776703-b2ea5e69-9a0a-481c-ba03-307d562a34d7.png)

Its (almost) implemented that way - but the spacing is still additive (_that_ hasn't changed from the original extension). So if you would want to have equal spacing across all windows and screen edges you would have to set your window `spacing` to half the value of your `inset`.

**Comment by scherepanov** [comment]
To be correct, insert should be set to double value of spacing. That avoids fractional division problem.

**Comment by luksa** [comment]
I disagree. As a user, when I set `window-spacing` to `20`, I expect the spacing between windows to be exactly `20`, not `40`. The way this is implemented right now makes it confusing to users. They think they are setting the spacing, but they are actually setting some type of window margin (but even this is confusing, since this margin is not applied on all sides of the window). The term "spacing" is thus incorrect. The graphic in the README is also incorrect. 

As for the division problem: gTile could simply round down `window-spacing` to the nearest even number. I don't think any user that sets `window-spacing` to an odd number would notice (or care) that the spacing ends up being 1px smaller.

**Comment by schnz** [comment]
I tend to agree, yet silently rounding down the user-supplied value to the nearest even number isn't exactly what I had in mind to fix the problem.

I'd rather be transparent about the (agreeably not intuitive) behavior. Do you think mentioning this in the settings dialog would be a compromise you could live with?

![Bildschirmfoto vom 2023-11-17 11-48-10](https://github.com/gTile/gTile/assets/3457747/79282878-406b-460c-a39e-a49a3d12e0e2)
