### ISSUE TITLE
Question: how to get notified when v53 lands on extensions.gnome.org?

### ISSUE THREAD

**Issue by alexanderadam** [gTile/gTile#350]
I'd love to know how to get notified when v53 lands on extensions.gnome.org?

Thank you so much for your work! :raised_hands:

**Comment by scherepanov** [comment]
Gnome will show notice about new version of gTile available.
gTile should be available on EGO in two days, may be earlier.

**Comment by alexanderadam** [comment]
Thank you for your response. I'm still waiting.

**Comment by stephane-klein** [comment]
> Thank you for your response. I'm still waiting.

@alexanderadam What is the reason for the delay in availability on EGO? Is there a human moderation process?

**Comment by alexanderadam** [comment]
> @alexanderadam What is the reason for the delay in availability on EGO? Is there a human moderation process?

Did you mention me intentionally?
I don't know otherwise I wouldn't have opened this issue. 😄

**Comment by scherepanov** [comment]
Extension.gnome.org reviewer rejected new version of gTile, posting several issues.
We are working on issues here:
https://github.com/gTile/gTile/pull/356
I think new version of gTile will finally show up on EGO over weekend.

**Comment by scherepanov** [comment]
gTile V55 is available on EGO
