### ISSUE TITLE
Need help to create nice gTile icon for extensions.gnome.org

### ISSUE THREAD

**Issue by scherepanov** [gTile/gTile#351]
Looking at extensions.gnome.org.... just noticed that gTile icon is ugly and by far lower level of art comparing to other popular extensions:

https://extensions.gnome.org/extension/28/gtile/

I confess this gTile icon is as good as I can do...

If you have some spare time and you are inspiring artist, please help to create nice icon for gTile on extensions.gnome.org.

Would be appreciated if you will suggest nice screenshot as well.

**Comment by lensaffair** [comment]
Are there any specifications regarding size, aspect ratio, resolution, transparency...?

**Comment by scherepanov** [comment]
You can look on
https://extensions.gnome.org/extension/28/gtile/
Icon is in left top corner next to gTile name, screenshot below next.
As far as I remember, I created black and white png file and uploaded and it works. I was very proud of it, it was a very first (and still the only one) image I created :-)

**Comment by tsnieman** [comment]
I'm interested in creating a gTile icon.

If others are also interested in taking a stab at it, I have gathered some resources on GNOME icons:
- Designing an icon for your app: https://blogs.gnome.org/tbernard/2019/12/30/designing-an-icon-for-your-app/
- App icons (full color, larger size): https://developer.gnome.org/hig/guidelines/app-icons.html
- UI icons aka symbolic icons (smaller, monochrome): https://developer.gnome.org/hig/guidelines/ui-icons.html
- Color palette: https://developer.gnome.org/hig/reference/palette.html
- App Icon Preview (generates a template + previews the icon at different sizes): https://gitlab.gnome.org/World/design/app-icon-preview

Also worth highlighting that the [Designing an icon for your app](https://blogs.gnome.org/tbernard/2019/12/30/designing-an-icon-for-your-app/#use-the-source) article linked above says:

> There are lots of apps with icons in the GNOME style out there, and they’re all free software. If there’s something you like about another app’s icon you can get the source from [GNOME Gitlab](https://gitlab.gnome.org/explore) or Github, look at how a certain object is drawn, or just take (parts of) other icons and adapt them to your needs.

One that stands out to me is the [Sudoku app's icons](https://gitlab.gnome.org/GNOME/gnome-sudoku/-/blob/master/data/icons/hicolor/scalable/org.gnome.Sudoku.svg?ref_type=heads):

![image](https://github.com/gTile/gTile/assets/595711/1fc6e8ee-df29-4191-94ce-6e1d03cfcc47)

**Comment by tsnieman** [comment]
I modified the template that [App Icon Preview](https://gitlab.gnome.org/World/design/app-icon-preview) generates - added the aforementioned Sodoku app's icons for inspiration, renamed some layers, added the official GNOME color palette.

[download the template](https://github.com/gTile/gTile/assets/595711/a5b1decd-436d-41f0-a5cf-cb30f297cf1b) - should open fine in Inkscape, as that is what I used to make it.

In the template, I also modified the Sodoku app icon and symbolic icon to have a "g" instead. Note the use of the `Source Code Pro` and `Cantarell` typefaces that i believe GNOME uses as its defaults. Example of the template being previewed via App Icon Preview:

![image](https://github.com/gTile/gTile/assets/595711/fe94c369-c56f-446b-84bc-f12f908158f5)

Adapting the Sudoku icon leaves something to be desired still, but it serves as a decent starting place / example.

**Comment by JMurph2015** [comment]
That's definitely a start!  What if you added a blue square with heavily radius'ed (even better if you can figure out how to match the radius being used on the icon corner) edges around the edge of the board?

(I can also try doing that, but I am very much an Inkscape novice)

**Comment by scherepanov** [comment]
Well. Looking at suggested icon, you would never figure out that it is a window placement manager. Yes it does nicely resembles Sudoku.
What I am looking for is to keep style of existing gTile icons. gTile do have around 30 000 - 50 000 users, they used to gTile branding and I do not want to change it.

I want gTile icon for EGO web site that is similar to what it is there now. Or similar to default gTile icon you see on toolbar.

Yes, @tsnieman artwork is very nice and very professional. I suggest you will submit one more gTile theme, complete with new icons and colors etc. I would gladly accept additional theme. 

I do understand that there is no absolute truth what artwork is better or worse. It is all just personal opinion.
Here, I want icon that looks familiar to gTile users and look nice and professional.

**Comment by scherepanov** [comment]
![image](https://github.com/gTile/gTile/assets/11700042/fc82d6eb-97cf-4163-adff-63bfcd4020e8)

**Comment by tsnieman** [comment]
@scherepanov Thank you, helpful to know we want something close to the original to maintain familiarity.

How's this? :arrow_heading_down: Kept the general layout identical, just applied some of the GNOME icon HIGs to them.

![image](https://github.com/gTile/gTile/assets/595711/47351bf6-f15a-4b8c-a862-9447688963a7)

![image](https://github.com/gTile/gTile/assets/595711/d139a5c9-859e-4cb7-88cc-c326c31bb17b)

![image](https://github.com/gTile/gTile/assets/595711/6a817fe9-d0ed-4801-9fbc-bdb62f7b3d33)

**Comment by scherepanov** [comment]
That is a very nice icon, big thanks @tsnieman !
I will update icon on EGO later today when I will have a chance.
I will commit this icon to gTile repo, it will be under same license as gTile. Let me know if it is OK.
Alternatively, you can submit PR by yourself - create one more dir and put your icon there.

**Comment by schnz** [comment]
I also like it. It looks more modern than before, yet minimalistic. 

I suggest to also replace the current logo of the GitHub gTile organization with it.

**Comment by tsnieman** [comment]
Glad you all like it!

You're free to use it as you'd like.

I am happy to submit a PR, but it would probably be a few days (next week).

I won't be offended if you're eager to put something together before I have the time, so here's the SVG files (exported from App Icon Preview) -

[regular](https://github.com/gTile/gTile/assets/595711/610b499b-821e-499b-8fe5-42e88719270f) svg
![com github gTile](https://github.com/gTile/gTile/assets/595711/610b499b-821e-499b-8fe5-42e88719270f)

[symbolic](https://github.com/gTile/gTile/assets/595711/acf538e5-91ff-484a-b5e0-5873e9853ba0) svg
![com github gTile-symbolic](https://github.com/gTile/gTile/assets/595711/acf538e5-91ff-484a-b5e0-5873e9853ba0)

[bonus nightly/developer version](https://github.com/gTile/gTile/assets/595711/4ebbb610-fe1f-4240-b2c9-029e1f28d4af) svg
![com github gTile Devel](https://github.com/gTile/gTile/assets/595711/4ebbb610-fe1f-4240-b2c9-029e1f28d4af)

Additionally, here's the App Icon Preview template I designed the icon in using Inkscape - [`com.github.gTile.Source.svg`](https://github.com/gTile/gTile/assets/595711/3a0b2802-4db5-4b16-8b36-5a7e7dd87f84)

**Comment by scherepanov** [comment]
New icon set for gTile EGO and github
Looks very nice, big thanks!
