### ISSUE TITLE
SyntaxError: import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by scherepanov** [gTile/gTile#357]
Error:
SyntaxError: import declarations may only appear at top level of a module

Problem:
New Gnome 45 version of gTile was installed over old version, and old version has not been properly removed.

Solution:
Remove gTile dir ~/.local/share/gnome-shell/extensions/gTile@vibou
Logout/login
Re-install gTile.
Problem also happens when you are installing gTile v >= 55 on gnome-shell v < 45, like Ubuntu 22.4

**Comment by dexpota** [comment]
The solution does not work in my case, I am in Manjaro with Gnome version 45.1.

**Comment by schnz** [comment]
Can you provide us with the log messages & the stack trace @dexpota ?

Double-check that the extension is uninstalled both in the local home directory (`~/.local/share/gnome-shell/extensions`) and in the system directory (`/usr/share/gnome-shell/extensions`)  in case you had installed an AUR package.
