### ISSUE TITLE
Add gonzojive to gTile maintainers

### ISSUE THREAD

**Issue by JMurph2015** [gTile/gTile#358]
I was just noticing on one of the Gnome 45 bugs that gonzojive isn't a member of the gTile organization.  They have the second highest contribution stats (as a naive metric) on this repository so I think it's reasonable that they should be a member of the org.

(@scherepanov for visibility)

PS: I can add them, I just was giving notice for posterity.

**Comment by scherepanov** [comment]
Invitation send.
