### ISSUE TITLE
gtile interaction with firefox fails to relocate tooltips

### ISSUE THREAD

**Issue by afreiberger** [gTile/gTile#36]
When using gtile to move a firefox window, it appears that the tooltips popups emanate from the prior location of the window until you manually move the window with the mouse.  You can witness this by starting firefox and putting the window manually in the lower-right quadrant of your screen, then typing in a url.  It should show the drop-down of suggestions in the correct location just under the URL bar, however, if you then use gTile to move it to the upper right of your screen and then enter data into the URL bar, the suggestion drop-down will come from the window's prior location.  You then have to wiggle the window with the mouse out of and back into place in the new location to get tooltips to re-home to the new window location.

**Comment by scherepanov** [comment]
Yes you describe rather strange behavior
I am trying to reproduce on my PC at home, Fedora 27
I manually moved Firefox window to lower corner.
I can display dropdown list of firefox suggestions to URL. If I move firefox window with gTile shortcut, dropdown list stays in place. But, after firefox window drawn in new position, it disappear. New dropdown URL suggestions appear in right place.
It does not look like reproducable.
For window move, gTile is using frameResizeMove. Whatever happens behind scene I have no clue. There are no docs, and tons of undocumented code that you have to dig to find how it works.
Built-in Gnome window move (left half of screen - right half of screen, Super-left/right) appears to signal firefox to remove tooltip first, and then moving window. No idea how they are doing it. Guys from gnome-shell mailing list are not very inclined to answer this kind of questions.
Doubt it is possible to address.

**Comment by scherepanov** [comment]
Sems to be issues was with old version.
