### ISSUE TITLE
moving to different monitor should have an option to auto resize/fit

### ISSUE THREAD

**Issue by jirikolar** [gTile/gTile#360]
When you have 2 monitors of different sizes (I guess thats very common) and you move window to the monitor 2 it preserves the geometry from  monitor 1.  This is not handy because on different monitor you usually want different size and placement as well. Therefore it would be good to have setting to an auto-fit of the window to the layout on the monitor 2. I see following solutions:

- Combine "move to next monitor"+"auto-tile layout/ resize perset" into one shortcut.  
- Persistent auto-tile on a monitor which would apply auto-tile when a new window arrive to a monitor would be a good idea (Xmonad-like approach)
- resize perset shortcut let you define not just geometry of the window  but also the monitor where the geometry is being applied. (such way you can use a key to move window to a screen and apply desired perset at the same time)

**Comment by scherepanov** [comment]
Moving window between monitors is a Gnome built-in, shortcut Super-Shift - arrows (I am using it a lot).
Moving window between monitors do preserve window geometry, i.e. width/height in pixels.
That is a default behaviour for all major WM, from what I know.
I have a feeling this is a very natural behaviour and it is what expected by users.
You can have desired behaviour now by using two shortcuts - first to move window between monitors, second is gTile shortcut to place window.
Though, I would not object if you will do coding and submit PR with this functionality. By default, gTile should have old behaviour, some settings in Preferences should enable new behaviour.

**Comment by jirikolar** [comment]
yes, but your shortcut "move to next monitor" is mapped by extension(very handy, you need just one shorcut for all moves) works different. if the window is maximized (or snapped to the side/gnome behaivour) on monitor1, it will not appear maximized on monitor2. Also when monitors have different sizes, the placement changes time to time. Therefore  "move to next monitor" is not consistent with built in  "Super-Shift - arrows". However the important part of my previous comment was the "persistent autotiling" I believe that is something that most of TilingWM users are used to.. I do some coding but no TS, so unfortunately I wont contribute ATM..
