### ISSUE TITLE
problem when settings up <Super> as first key

### ISSUE THREAD

**Issue by adrien-barret** [gTile/gTile#363]
just installed a new machine (manjaro), with gnome 45 and gtile

when I try to set Super + shift + f gtile does not reconize <Super> as a key.  I checked if it was already took in gnome but nothing is using it. 

I also tried others set of key containing <super> , same problem.
It only work if I remove Super in the key combinaison 

tried lg to find some log but just saying "no errors"

any ideas?

```
 π ~ ❯ gsettings list-recursively org.gnome.desktop.wm.keybindings | grep Super
org.gnome.desktop.wm.keybindings close ['<Shift><Super>q']
org.gnome.desktop.wm.keybindings maximize ['<Super>Up']
org.gnome.desktop.wm.keybindings move-to-monitor-down ['<Super><Shift>Down']
org.gnome.desktop.wm.keybindings move-to-monitor-left ['<Super><Shift>Left']
org.gnome.desktop.wm.keybindings move-to-monitor-right ['<Super><Shift>Right']
org.gnome.desktop.wm.keybindings move-to-monitor-up ['<Super><Shift>Up']
org.gnome.desktop.wm.keybindings move-to-workspace-10 ['<Shift><Super>0']
org.gnome.desktop.wm.keybindings move-to-workspace-5 ['<Shift><Super>5']
org.gnome.desktop.wm.keybindings move-to-workspace-6 ['<Shift><Super>6']
org.gnome.desktop.wm.keybindings move-to-workspace-7 ['<Shift><Super>7']
org.gnome.desktop.wm.keybindings move-to-workspace-8 ['<Shift><Super>8']
org.gnome.desktop.wm.keybindings move-to-workspace-9 ['<Shift><Super>9']
org.gnome.desktop.wm.keybindings switch-applications ['<Super>Tab', '<Alt>Tab']
org.gnome.desktop.wm.keybindings switch-applications-backward ['<Shift><Super>Tab', '<Shift><Alt>Tab']
org.gnome.desktop.wm.keybindings switch-group ['<Super>Above_Tab', '<Alt>Above_Tab']
org.gnome.desktop.wm.keybindings switch-group-backward ['<Shift><Super>Above_Tab', '<Shift><Alt>Above_Tab']
org.gnome.desktop.wm.keybindings switch-input-source ['<Super>space', 'XF86Keyboard']
org.gnome.desktop.wm.keybindings switch-input-source-backward ['<Shift><Super>space', '<Shift>XF86Keyboard']
org.gnome.desktop.wm.keybindings switch-to-workspace-10 ['<Super>0']
org.gnome.desktop.wm.keybindings switch-to-workspace-5 ['<Super>5']
org.gnome.desktop.wm.keybindings switch-to-workspace-6 ['<Super>6']
org.gnome.desktop.wm.keybindings switch-to-workspace-7 ['<Super>7']
org.gnome.desktop.wm.keybindings switch-to-workspace-8 ['<Super>8']
org.gnome.desktop.wm.keybindings switch-to-workspace-9 ['<Super>9']
org.gnome.desktop.wm.keybindings unmaximize ['<Super>Down', '<Alt>F5']
 π ~ ❯
```

**Comment by schnz** [comment]
I suppose I  don't have a solution for you here. I just only assume that it is something system-specific. I just tried the shortcut on my system and it is recognized in the prefs dialog correctly as <kbd>\<Shift\>\<Super\>f</kbd>. I am on a Arch Linux installation which usually behaves the same as a Manjaro installation.

Are you using X11 or Wayland?

**Comment by adrien-barret** [comment]
I use X11
```
 π ~ ❯ echo "$XDG_SESSION_TYPE"
x11
```

And yes I tried keeping only gtile as extension

**Comment by schnz** [comment]
Okay, I see. We had a [report](https://github.com/gTile/gTile/pull/356#issuecomment-1836568533) in the past which might relate to your experience but we weren't able to figure out a way to reproduce it. 

Could you monitor the following log output in a dedicated terminal window while you try to set the shortcut in the extension preferences? That would help in figuring out whether it's related to the referenced report.

```
journalctl -f /usr/bin/gjs /usr/bin/gnome-shell
```

**Comment by adrien-barret** [comment]
sure , here is the log ! 

```
# journalctl -f /usr/bin/gjs /usr/bin/gnome-shell

Jan 16 10:14:36 hk-lw gjs[31591]: g_task_return_error: assertion '!task->ever_returned' failed
Jan 16 10:14:39 hk-lw gnome-character[31227]: JS LOG: Characters Application exiting
Jan 16 10:14:40 hk-lw gnome-shell[1801]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x6c0000e
Jan 16 10:14:41 hk-lw gjs[31607]: JS ERROR: Error: 0x4000041 is not a valid value for flags argument modifiers
                                  #onRebindKey/<@file:///home/hk/.local/share/gnome-shell/extensions/gTile@vibou/prefs.js:441:22
                                  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

```

**Comment by schnz** [comment]
Thanks. It looks very much like the referenced report. Last time I couldn't reproduce it (on Fedora) and I still can't figure out why it is happening. Maybe this time around I can reproduce it.

You said its a new machine (manjaro), with gnome 45 and gtile. I will setup up a VM when I find the time and try to reproduce it. If you are using any non-default configuration that might be related to this error, please leave a comment, so that I can setup it in the same way.

**Comment by adrien-barret** [comment]
atm, I'm using a qwerty US layout and language is English Canada with formats Canada 

I just tested on my laptop which is a brand new manjaro on qwerty and same log. You'll probably have opportunity to reproduce it too on a vm

**Comment by adrien-barret** [comment]
perfect, I'll use the j for the moment and waiting update of this bug. In any case, thanks for all your job and support !

**Comment by schnz** [comment]
@adrien-barret : I've created a PR with a fix in #365. I tested it on the Manjaro Live system. But I would appreciate if you could double-check that it is working for your system as well, if you find the time.

You can use the provided zip file, attached to this post. After downloading, simple install it via

```bash
gnome-extensions install -f ~/Downloads/gtile.dist.zip
```

You may need to restart your gnome-session in order for the changes to become effective (i.e. logout and login again).

Thank you!

---

[gtile.dist.zip](https://github.com/gTile/gTile/files/14076830/gtile.dist.zip)

**Comment by adrien-barret** [comment]
Hello ! Thanks for the update :)
I tried removing the extension installed, install the zip and reboot juste to be sure. 
Sadly it's not working but here is the log:

```
Jan 28 20:55:46 xlp gjs[2058]: JS ERROR: Error: 0x40 is not a valid value for flags argument state
                               #normalizeKeyvalAndMask@file:///home/hk/.local/share/gnome-shell/extensions/gTile@vibou/prefs.js:483:44
                               #onRebindKey/<@file:///home/hk/.local/share/gnome-shell/extensions/gTile@vibou/prefs.js:440:70
                               _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


```

**Comment by schnz** [comment]
Thanks for the test - I can reproduce the error. The Live installation seemed to have switched to a regular Gnome (Wayland) session after logout + login and I had to explicitly select a Gnome Xorg session during the login. That's why the problem hasn't manifested in my testings.

However, I couldn't narrow down the issue and why it is happening on X11 only. I'll continue to debug and fix the problem when I find the time and keep this issue up-to-date.

**Comment by adrien-barret** [comment]
so it work for you on x11 if I understand correctly. 

I use x11 as I don't like wayland so much and my log come from x11 so

```
└─(20:09:37)──> loginctl show-session 3 -p Type                                         ──(Mon,Jan29)─┘

Type=x11
└─(20:10:17)──> echo $XDG_SESSION_TYPE                                                  ──(Mon,Jan29)─┘
x11


```

**Comment by schnz** [comment]
Nono, It didn't worked on x11 for me. When I tested the fix, I was under the __impression__ that I use X11.  However, this was a mistake on my end because the system automatically switched from X11 to Wayland after logout/login without me realizing it.

Your debug log caused me to double check and thus made me realize my mistake :+1: !

**Comment by schnz** [comment]
@adrien-barret I eventually found the time to debug the problem properly. The fix will be contained in the next release.

If you like, you can try the attached build - although I am pretty confident it will work this time :).

Thanks for the report and the valuable error logs.

----

[gtile.dist.zip](https://github.com/gTile/gTile/files/14280615/gtile.dist.zip)

**Comment by adrien-barret** [comment]
It work !

![image](https://github.com/gTile/gTile/assets/25575104/6bb6f2ca-5aab-4340-bf6b-8ae55a29a0ae)
 

Thank for all your work done on this issue but on the extension too ! it save gnome from....you know, gnome. ;)

**Comment by schnz** [comment]
An on [official release](https://github.com/gTile/gTile/releases/tag/V57) is now available and will be distributed through extensions.gnome.org in the upcoming days.
