### ISSUE TITLE
Inconsistent behavior at screen edge

### ISSUE THREAD

**Issue by JMPMarshall** [gTile/gTile#364]
The new version of gTile when moving a window to the right screen edge allows the window to extend past the right screen edge.  The previous version would continue to move the window further to the right while resizing the window to stay on the screen.

**Comment by schnz** [comment]
Hey @JMPMarshall,

this is a known regression which was also [reported](https://github.com/gTile/gTile/pull/341#issuecomment-1803663698) during the beta. The extension was completely rewritten to be compatible with Gnome 45. As such, it also has a few behavioral changes that felt more natural/intuitive and allowed for a cleaner data- and code structure. The behavior that you are reporting is amongst those changes.

While I won't consider to implement the old behavior, you are more than welcome to add this feature to the extension, preferably allow it to be turned on/off, and submit a PR.
