### ISSUE TITLE
[Question] Create custom shortcut

### ISSUE THREAD

**Issue by Fink-Git** [gTile/gTile#366]
Hello !
Congratulations for this really useful extension.

I have some questions : 
- Is there a native way to create shortcut for windows size and location (like in divvy) ? i.e set shortcut to resize Presets 
- If not can i do this ? by config ? by code ?

Thanks for your time

**Comment by schnz** [comment]
Hey @Fink-Git ,

yes you can set custom shortcuts for resize presets in the extension settings dialog:
![Screenshot from 2024-02-02 16-44-44](https://github.com/gTile/gTile/assets/3457747/a49ab219-3a15-4b3c-b42e-95d49c1892d3)

You can check the [`README.md`](https://github.com/gTile/gTile?tab=readme-ov-file#configuration) on how to open the extension preferences dialog.

**Comment by Fink-Git** [comment]
Sorry, i didn't notice there were tabs ...
My bad ! Many thanks
