### ISSUE TITLE
Hide gtile icon indicator from application bar

### ISSUE THREAD

**Issue by Zeka13** [gTile/gTile#37]
![2018-05-16 13-01-46](https://user-images.githubusercontent.com/13749031/40110678-4d82a368-5909-11e8-8ad6-73fad156121c.png)

Rly do not need it there, how to remove?

thx for awesome extension

**Comment by scherepanov** [comment]
OK, that sounds like a reasonable request.
Will be done (eventually)

**Comment by jdamboeck** [comment]
An option to disable the Icon would be great.
