### ISSUE TITLE
Gnome 46 Support Please

### ISSUE THREAD

**Issue by pavangayakwad** [gTile/gTile#376]
I am on openSUSE and received Gnome 46 update as my rolling update just now however and I find gTile is disabled and not supported!!

![image](https://github.com/gTile/gTile/assets/1834890/330feb21-bc80-47cb-8473-d03a9b23c1d2)

Request to offer the support

**Comment by schnz** [comment]
Hey @pavangayakwad ,

I use Arch Linux as my daily driver and I assume Gnome 46 is still a few weeks away for this distro. However, [I don't see any breaking changes](https://gjs.guide/extensions/upgrading/gnome-shell-46.html with regard to gTile that would require any code changes.

Could you test if the extension is working on Gnome 46? 

1. Download the extension distribution from here: https://github.com/gTile/gTile/releases/download/V58/gtile.dist.zip (or the [`tar.gz`](https://github.com/gTile/gTile/releases/download/V58/gtile.dist.tgz) version if that is more convinient)
2. Unpack the archive and adapt the [`/dist/metadata.json`](https://github.com/gTile/gTile/blob/master/dist/metadata.json) file as needed (i.e., replace the `shell-version` with ` "shell-version": ["45","46"],`)
3. Re-pack the archive (with the same structure! Either as .zip or as .tgz)
4. Upgrade the extension via `gnome-extensions install -f ~/your-modified-gTile-archive.zip`
5. Restart the shell session (i.e. logout/login)
6. Check if you can enable the extension now

Should you approve that its working, I could publish a new release. But I am too lazy to download/boot into a Fedora system to test it myself.

**Comment by pavangayakwad** [comment]
Followed your steps and yes!! it is working on Gnome 46 without any problems. Thanks.

**Comment by schnz** [comment]
Nice, I take your word for it :+1: 

Just pushed/released a version with support for Gnome 46.


@scherepanov : Can you publish it on EGO?

**Comment by scherepanov** [comment]
Sorry for delay, published.
EGO review queue is not long, gTile is no 8. May be will be reviewed even today.

**Comment by schnz** [comment]
> Sorry for delay, published.

No worries. It was already published :)

**Comment by scherepanov** [comment]
Amazing... new version has been reviewed less than 5 min after being published.
gTile made friends in Gnome core team!

**Comment by schnz** [comment]
I suppose the more likely explanation is the very manageable diff between this and the last version :D 

```diff
@@ -2,8 +2,8 @@
  "uuid": "gTile@vibou",
  "name": "gTile",
  "description": "Tile windows on a grid",
-  "shell-version": ["45"],
+  "shell-version": ["45", "46"],
  "url": "https://github.com/gTile",
  "settings-schema": "org.gnome.shell.extensions.gtile",
-  "version": 58
+  "version": 59
}
```
