### ISSUE TITLE
Feature:Auto tile Keybindings

### ISSUE THREAD

**Issue by Carlos12001** [gTile/gTile#378]
### Extension name and maintainer

adjacent-windows@klangman @klangman

### What would you like to see?

![image](https://github.com/linuxmint/cinnamon-spices-extensions/assets/62664256/c72572e0-6ae3-41d2-acad-2f69c6628bb8)

I would like to use "auto tile main and list" and "auto tile two list" with a keybiding. I believe could be easier to use quickly.

**Comment by schnz** [comment]
Try "m" and "2" while the UI popup is opened

**Comment by schnz** [comment]
I am closing this issue for the reasons stated above. Feel free to object if I misinterpreted your inquiry.
