### ISSUE TITLE
Binding number key in 'Resize Presets' prevents using number keys in the dialogue

### ISSUE THREAD

**Issue by rommeswi** [gTile/gTile#380]
On vanilla gtile on Gnome 46, bind the regular "1" key to 'Resize Preset 1'. Then try to edit 'Preset resize 1 settings' and press "1". Nothing happens. What's worse, you cannot even type "1" in Firefox. Unbind 'Resize Preset 1' and you can type "1" again in the dialogue. This is independent of the setting 'Allow preset shortcut usage when the gTiles UI is not visible'.

**Comment by rommeswi** [comment]
Perhaps the behavior is a bit more nuanced than I thought. Ex-post the "Allow preset shortcut usage when gtile ui is not visible" does not do anything but deactivating it beforehand does not create the issue?

**Comment by schnz** [comment]
Hey, same as in #379. I would think of this as "working as expected".

Note: As stated in the settings menu (under "General"), _most settings become effective after toggling the gTile UI_. In particular, this includes key bindings that were reassigned. That means, that if you bound a shortcut to "1", you may continue to use "1" regularly until you open the gTile overlay.

Once the shortcut is bound successfully, it is intercepted by Gnome. So it is expected that "1" cannot be used as a regular key anymore.

**Comment by schnz** [comment]
I am closing this for now. I suppose users need to be cautious of the key bindings that they set. The settings dialog already contains a warning about this is in the `Autotiling` section.
