### ISSUE TITLE
SyntaxError: import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by cecoppola** [gTile/gTile#382]
When attempting to configure the extension for the first time, I get the error:

> SyntaxError: import declarations may only appear at top level of a module
> 
> Stack trace:
>   _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
>   ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
>   OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
>   asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
>   run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
>   main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
>   run@resource:///org/gnome/gjs/modules/script/package.js:206:19
>   start@resource:///org/gnome/gjs/modules/script/package.js:190:8
>   @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by schnz** [comment]
Hey @cecoppola ,

its very likely that you tried to install the most recent version of this extension in a legacy Gnome environment. If you are on a Gnome version 44 or below, you need to install an older version of this extension. Check https://extensions.gnome.org/extension/28/gtile/ which extension versions are compatible with which Gnome versions.

Cheers!

**Comment by schnz** [comment]
@cecoppola , please let us know if this helped you, so we can close this issue (if that's the case).

**Comment by schnz** [comment]
Closing due to lack of feedback.
