### ISSUE TITLE
Improve README content and formatting

### ISSUE THREAD

**Issue by JMurph2015** [gTile/gTile#4]
Since the README is essentially all of our documentation at this moment, we should probably give it some TLC to make it useful.  #2 starts to address this by moving the changelog, but there's plenty where that came from.

**Comment by severoraz** [comment]
Did #15 perhaps take care of this?

**Comment by JMurph2015** [comment]
#15 Looks like it covered most of the issue for the moment, further improvements should probably get more specific issues.
