### ISSUE TITLE
Vertical maximization?

### ISSUE THREAD

**Issue by cfergeau** [gTile/gTile#401]
Before using gtile, I had a keyboard shorcut mapped to 'vertically maximize'.
With gtile, I'd like to be able to get the same behaviour when I set a window to use the full height: moving the window with the mouse and the window key held will let me move it horizontally, but not vertically.
I cannot get this 'locked' behaviour with gtile.

**Comment by schnz** [comment]
Hey @cfergeau, that is correct - I've explained [here](https://github.com/gTile/gTile/issues/336#issuecomment-1836116641) why gTile, IMO, shouldn't have this ability.

Gnome already comes with this functionality out-of-the-box. Would these (native) Gnome shortcuts suffice? (<kbd>Super+↑</kbd>,<kbd>Super+→</kbd> <kbd>Super+←</kbd>)

**Comment by cfergeau** [comment]
> Gnome already comes with this functionality out-of-the-box. Would these (native) Gnome shortcuts suffice? (Super+↑,Super+→ Super+←)

I've set a native GNOME shortcut for this as the default 'super' shortcuts don't do what I want:
![image](https://github.com/user-attachments/assets/cd1c60af-22f4-4ded-a14f-787b296df4f1)

In general, I'd want any window which uses the entire height of the screen to be considered vertically maximized (note: vertically maximized does not mean they have to be stuck to the left or right edge of the screen, they can be anywhere on the screen, but their top and bottom reach to the top/bottom edges of the screen).

I understand this behaviour is probably not desirable for everyone, but having this optional would be great.

**Comment by schnz** [comment]
> vertically maximized does not mean they have to be stuck to the left or right edge of the screen, they can be anywhere on the screen, but their top and bottom reach to the top/bottom edges of the screen

Interesting: Until now, I was under the impression that this was the only mode that Gnome supports. 

---

> I understand this behaviour is probably not desirable for everyone, but having this optional would be great.

I am not opposing this change per-se. But I find it difficult (if not impossible) to integrate this together with the mechanics that are already in place. To me this raises alot of questions on how gTile should behave in certain situations (as outlined in the referenced comment from above).

Realistically, the only way that I see your request move forward is either (ideally) if you try to integrate it to gTile and make a PR, and/or provide a detailed concept on how it can be integrated to gTile without render existing mechanics dysfunctional (especially the `inset` feature).

**Comment by cfergeau** [comment]
I'll answer inline to your comment in the other issue:

> To be consistent, this feature would have have to be applied for all gTile operations, not just the "window placement through grid selection"-feature.
> There are also shortcuts to expand window edges towards an arbitrary direction. 

If the edges are moved up and down so that the window uses the full screen height, then it's not much different from a window which was vertically maximized using the custom shift+alt+f10 shortcut I showed in my previous screenshot

> There are shortcuts to move windows towards an arbitrary direction. And some more (such as autogrow). [...] Why would a window become maximized when I merely want to move it?

I don't know how hard it is to achieve, but I would only consider the window vertically maximized if its size == the size of a 'full height' window, and when movement ends, its upper or lower edge is aligned with with the top/bottom edge. I would not use these shortcuts, so I'm not the best to comment on the behaviour they should have :)

> All of these features (IMO) should be expected to put a window to full screen as soon as it touches the edge of the screen and takes the full height of the work area. IMO that would, again, be an inconsistent behavior. 

In the current issue, it's only about vertical maximization, I don't expect automatic fullscreening, or even an equivalent of Super+left arrow. Just "if window height == screen height, then vertically maximize it", which roughly means it can be moved left/right with window key + mouse, but not up and down


> If the user configured an inset larger than 0, it would practically (yet implicitly) prevent to have vertical fullscreen windows. So the behavior would be different depending on whether an inset is configured or not - which is not intuitive.
> Come to think of it, the vertical maximization thing could be thought of as an inset value of -1. This would keep mechanics consistent. I have to give this some more thought.

Inset is the slightly trickier bit, though if vertical maximisation is an option and not always enabled, the "top/bottom gap around border of screen" options would need to be disabled when  vertical maximization is on. Or a value of -1 could be used to enable this behaviour, but top and bottom would no longer be independant when set to -1.

**Comment by cfergeau** [comment]
Actually, for terminal windows and bottom inset == 0, vertical maximization is actually more correct than the current behaviour:
![image](https://github.com/user-attachments/assets/41c0cb26-b6d4-4d1c-92be-7af278599429)

This shows from left to right: 
- nautilus window set to use the full screen height using gtile - there are effectively 0 pixels between the edge of the window and the bottom of the screen
- gnome terminal window set to use the full screen height using gtile - there are a few pixels between the edge of the window and the bottom of the screen
- gnome terminal window set to use the full screen height using gtile, and then vertically maximized using my alt+shift+f10 shortcut - there are 0 pixels between the edge of the window and the bottom of the screen

However vertical maximization comes with different behaviour wrt to window movement, at least with the mouse.

**Comment by scherepanov** [comment]
Does not look like it will be a widely used functionality.
