### ISSUE TITLE
Update icons

### ISSUE THREAD

**Issue by usbkey9** [gTile/gTile#41]
Hi,

Thanks for your works.
It's not really an issue, more than an improvement : can you update your icons to looks like caffeine please ?

Best,

**Comment by scherepanov** [comment]
What is caffeine?

**Comment by usbkey9** [comment]
https://extensions.gnome.org/extension/517/caffeine/

**Comment by JMurph2015** [comment]
@usbkey9 Could you perhaps point us toward an icon set to better understand the styling that you propose?  If I am guessing correctly, do you mean that it would be better if we used solid colored white icons instead of our current gray?

**Comment by usbkey9** [comment]
Hi,

I don't have an icon set near me so.
But yes, like the caffeine's one, you better use a solid color.
Best

**Comment by scherepanov** [comment]
Realistically estimating my graphic design skills, any new icon made by me will be looking by far worse than current one.
Unless you @usbkey9 will come up with nice new set of icons, no changes will be done.
It does appear that you have some taste, as you dislike something that looks completely normal to me. I assume you can design new very beautiful icons.

**Comment by JMurph2015** [comment]
I potentially figure out a way to recolor the current ones since it seems to be just a transparency issue, but it's pretty low on my to-do list due to my inundation of software projects these days.

**Comment by usbkey9** [comment]
Hi,

Thanks Joseph, I don't have so much times

**Comment by scherepanov** [comment]
Looks like there are no volunteers to create updated set of icons.
