### ISSUE TITLE
stopped working with 2nd monitor

### ISSUE THREAD

**Issue by mbmilligan** [gTile/gTile#42]
I've been using gTile for some time with no problems. My setup involves two monitors, and I am using the "workspaces on primary display only" Gnome option. After upgrading to Ubuntu 18.04 (gnome-shell went from 3.26.2 to 3.28.1) gTile acts like it is only aware of the primary display. 

Specifically, the previous behavior was that the layout grid would pop up on the same monitor as the focused window, and would keep windows on their current monitor. The new behavior is that the layout grid always pops up on the primary monitor, and resizing a window using the grid will move the window onto the primary monitor. 

The new behavior is the same when activating it either via the keyboard shortcut or the toolbar icon.

Happy to provide additional info if you can let me know what would be helpful. Thanks!

**Comment by scherepanov** [comment]
I do not see this behavior. I am running Fedora 28 with 2 monitors. gnome-shell reports version 3.28.2.
gTile functioning properly, I do not see anything you describe.
If you want more to debug, enable debug in gTile preferences. Then in shell replace gnome-shell:
gnome-shell --replace
Now you should see all messages on screen.
You can filter by keyword gTile
You can post here gTile log entries for troubleshooting.

**Comment by mbmilligan** [comment]
To follow up, the behavior I described went away on its own, and after several reboots and monitor connect/disconnect cycles, I have not been able to reproduce the issue. If the issue crops up again I will use your suggestion to capture debugging information and reopen this ticket. Thanks!
