### ISSUE TITLE
Presets lost upon upgrade

### ISSUE THREAD

**Issue by mojason-81** [gTile/gTile#49]
Just wanted to report this so you'd know about it.  I upgraded gTile this morning and all my presets were lost.
Ubuntu 18.04
Gnome Shell 3.28.3

**Comment by scherepanov** [comment]
Gnome extension settings changes are saved on system level, outside extension.
Most likely Gnome, on upgrade, delete all settings and load new one that comes out with extension.
This makes sense, as for example I just removed one setting and added another. At least it prevents unused settings to accumulate on system level.
I want to point this is completely outside extension.
From other side, I do understand that you do want to keep your custom settings. In theory, tool like dconf-editor should be able to export key subtree, and import back. But it is not.
Looks like for saving settings, you have to write your own export. There is already standard Gnome import from XML schema definition, so exporting to same XML format makes sense.
I suggest you will write corresponding code, and submit PR.

**Comment by gonzojive** [comment]
FYI, here is how I keep my settings in a dotfiles git repository:

README.md

	# DConf preferences
	
	Save and load these with
	
	```~shell
	dconf dump /org/gnome/shell/ > gnome-shell.conf
	```
	
	```shell
	dconf load /org/gnome/shell/ < gnome-shell.conf
	```

gnome-shell.conf:

```
[extensions/gtile]
resize1='1x2 0:0 0:0, 1x4 0:0 0:2'
resize2='1x2 0:1 0:1, 1x4 0:1 0:3'
resize5='2x1 0:0 0:0, 3x1 0:0 1:0, 5x1 0:0 3:0, 3x1 0:0 0:0'
resize6='2x1 1:0 1:0, 3x1 1:0 2:0, 5x1 1:0 4:0, 3x1 2:0 2:0'
resize3='2x2 0:0 0:0, 2x5 0:0 0:3'
resize4='2x2 1:0 1:0, 2x5 1:0 1:3'
resize7='2x2 0:1 0:1, 2x5 0:1 0:4'
resize8='2x2 1:1 1:1, 2x5 1:1 1:4'
resize9='1x1 0:0 0:0'
preset-resize-1=['<Primary><Alt>1']
preset-resize-2=['<Primary><Alt>2']
preset-resize-3=['<Primary><Alt>3']
preset-resize-4=['<Primary><Alt>4']
preset-resize-5=['<Primary><Alt>q']
preset-resize-6=['<Primary><Alt>w']
preset-resize-7=['<Primary><Alt>e']
preset-resize-8=['<Primary><Alt>r']
preset-resize-9=['<Primary><Alt>equal']
preset-resize-30=['<Primary><Alt>5']
```
