### ISSUE TITLE
Feature Request: cycle on Accelerators

### ISSUE THREAD

**Issue by onlycparra** [gTile/gTile#54]
Hi,

This is the scenario: I use gTile with Accelerators in the numpad, for example:

```
Super+7 -> upper left corner (2x2 0:0 0:0)
Super+4 -> left half (2x1 0:0 0:0)
Super+6 -> right half (2x1 1:0 1:0)
Super+5 -> full screen (1x1 0:0 0:0)
```

Sometimes, "1/2 against 1/2" of the screen is not the right division, so I use "2/3 against 1/3"
```
Alt+Super+7 -> upper half, left 2/3 (3x2 0:0 1:0)
Alt+Super+4 -> left 2/3
Alt+Super+6 -> right 1/3
```

Sounds good, but the problem is that I run out of Accelerators very fast. I would like to suggest this: **If I assign the same accelerator to several presets, then, when I press the accelerator several times, the presets rotate on all the assigned to that particular accelerator.** In this way I can conveniently assign things like this:

```
Super+4 -> left 1/2
        -> left 3/8
        -> left 1/4
        -> left 1/8
```

That will provide almost all the possible flexibility with few, easy to remember, and intuitive strokes.

Thanks for your work, guys.

**Comment by scherepanov** [comment]
Interesting idea... yes you can define more than one setting for preset, and cycle through it.
Cycling through window location with one accelerator would be bad for general public, as it makes window placement unpredictable. But, we can release gTile with only one preset per accelerator. And it will continue to work as it works now. People who like adventures can additionally define more setting per accelerator and cycle.
Settings will look like this:
2x2 0:0 0:1 - single settings, same as now
(2x2 0:0 0:1, 2x2 0:0 1:1, 2x2 1:0 0:0, 2x2 1:1 1:1) - settings that allow cycling

Any comments? I think it is worth implementing

**Comment by onlycparra** [comment]
Are you saying with the first phrase that that is already possible? I tried it but it didn't work.
Thanks for taking the time for reading my idea.
Also, you can always define that the cycle always starts from the smallest number ID of preset. If you press the accelerator again in less than a second or two, triggers the next preset.

Thanks again

On September 21, 2018 10:09:14 PM UTC, scherepanov <notifications@github.com> wrote:

Interesting idea... yes you can define more than one setting for preset, and cycle through it.
Cycling through window location with one accelerator would be bad for general public, as it makes window placement unpredictable. But, we can release gTile with only one preset per accelerator. And it will continue to work as it works now. People who like adventures can additionally define more setting per accelerator and cycle.
Settings will look like this:
2x2 0:0 0:1 - single settings, same as now
(2x2 0:0 0:1, 2x2 0:0 1:1, 2x2 1:0 0:0, 2x2 1:1 1:1) - settings that allow cycling

Any comments? I think it is worth implementing

**Comment by scherepanov** [comment]
No, it is just a nice idea worse considering. Not yet done.

**Comment by WBTMagnum** [comment]
> Please modify your implementation - grid size is required for first entry in a list. For other entries it can be specified, if not will be using last specified grid size.

Sounds reasonable. I'll give it a go. I might not be able to finish it today though.

**Comment by scherepanov** [comment]
This feature should accompanied by corresponding change to default presets.
We have 3 sets of default presets, can be invoked with ALT-Super, Shift-SUPER, Ctrl-SUPER. There is 9 presets for each of them.
Each preset should be expanded - first is same as now (to keep functionality intact), plus 3 more that makes window smaller and then bigger and again decreasing. For example if preset is 2x2 0:0 0:0, it should be modified to
2x2 0:0 0:0, 8x6 0:0 1:1, 8x6 0:0 2:2, 8x6 0:0 3:3.
Repeatedly pressing same predefined preset should create impression of window changing it's size to much smaller to the corner, then bigger and bigger. Close to animation effects.

For window in center 3x3 1:1 1:1, cycle should be around center of screen, making window bigger.

Default presents should always do change of window size in one direction - make them bigger, and then jump from largest size to smallest. This will create feel of stability and predictability of operation.

And, if you have time, I have next feature to implement, with being swamped at office have no time. Let me know if you are interested.

**Comment by WBTMagnum** [comment]
While implementing the PR I identified some related points that could also be improved:
* Don't only check if it's the same preset, check if it's also the same window. This will prevent use of an unexpected preset on another window.
* Set maximum timeout for consecutive use of shortcuts. This will prevent accidental use of a possible unexpected preset.
* Settings: Validate presets on input via regex, indicating result via a validity indicator.
* Settings: Instead of plain text input, use a more structured input, e.g. [grid size] [upper right] [lower left].
* Settings: Add visual selector to define presets.

If you deem all or some points interesting, I can create separate tickets for them.

**Comment by scherepanov** [comment]
All of above are very welcome and very good.
Except first two which really should be together in one PR with this one.

**Comment by scherepanov** [comment]
Merged into master
