### ISSUE TITLE
Does not work on new Gnome 3.30 shell version

### ISSUE THREAD

**Issue by shierve** [gTile/gTile#56]
The extension was working fine until I upgraded gnome to 3.30. I love the extension and would love to be able to use it again soon.

**Comment by scherepanov** [comment]
Recent version on official extension.gnome.org should be handling 3.30
Can you try upgrading to most recent, and report here how it works.

**Comment by shierve** [comment]
I upgraded to the most recent version as you said, but the most recent version listed is for 3.28, and does not work.
![screenshot from 2018-09-27 07-41-06](https://user-images.githubusercontent.com/10463860/46125373-16658600-c229-11e8-93c4-1cb4138bfe7b.png)

**Comment by scherepanov** [comment]
New version of gTile have been approved day before yesterday
Installing new version of extension require login-logout for new code to take effect.
Can you try and tell if it is working/not working.
Yes version of gTile listed still 3.28.
@StuntsPT  can you submit new PR, adding v 3.30 to supported list in metadata.json? I do not have access to commit code from office. I will approve PR and merge into master, and will submit new version to EGO. Then it will officially support 3.30

**Comment by StuntsPT** [comment]
@scherepanov I already [submitted that PR](https://github.com/gTile/gTile/pull/52) and it was merged.
Current `master` has [v3.30 listed](https://github.com/gTile/gTile/blob/master/metadata.json#L15) in `metadata.json`.
Am I missing something here? 

@shierve Yes, you can clone the repository to `~/.local/share/gnome-shell/extensions/gTile@vibou` and it should work.

**Comment by StuntsPT** [comment]
I have just confirmed that gTile version 28 and 29 available on extensions.gnome.org still list v3.28 as the latest supported version.
I think it just needs to be re-uploaded from current master.

**Comment by shierve** [comment]
I can confirm that it works when installed manually. Thanks guys 👍

**Comment by thomashw** [comment]
Can also confirm installing manually fixes the issue.

**Comment by scherepanov** [comment]
@StuntsPT My bad I forget v3.30 already in master. Will submit this version to extensions.gnome.org. Currently EGO have same code, but metadata.json does not list 3.30.

That is very strange that gTile installed from EGO directly does not work. We need to trace it down. Can you guys do following procedure:
1) re-install gTile from EGO
2) Check that it does not work
3) enable debug in gTile preferences
4) login-logout
5) submit here outputfrom
journalctl | grep gTile

**Comment by shierve** [comment]
Weird, it seems to work now. What I did was:

```
$ rm -rf ~/.local/share/gnome-shell/extensions/gTile@vibou
- restart the computer
- go into EGO and install gTile
```

And now it works correctly. The page still shows 3.28 as the newest version, but when activated the extension works perfectly. I am not sure that I uninstalled the extension correctly by just removing the folder, or maybe it is solved already.

**Comment by scherepanov** [comment]
Can you restore non-woring config?
Steps:
1) disable gTile
2) remove gTile dir, 
3) download zip from EGO (you need v27), 
4)manually unpack zip and install
5) logout-login
6) Enable gTile
Now you should run previous version.
Now, got to EGO and upgrade gTile. Login-logout.
Check if it is failing.
If failing, enable debug in gTile preferences, login-logout, and post here output from
journalctl | grep gTile

**Comment by thomashw** [comment]
It's no longer failing after disabling/removing, installing 27 manually, logging out/in, upgrading to 28 through EGO, and logging out/in again.

**Comment by scherepanov** [comment]
EGO have cool feature - if the only change is gnome-shell version increment, it is auto-approved.
I just uploaded recent version from master, it immediately auto-approved. Now official version have 3.30 support.
Please check how it works, let me know.

**Comment by shierve** [comment]
I have updated to the new version and it works perfectly, thank you very much. i close the issue since it is resolved.

**Comment by thomashw** [comment]
New version is working for me as well.
