### ISSUE TITLE
Feature Request/Help  change autoscaler 

### ISSUE THREAD

**Issue by ChristofferNicklassonLenswayGroup** [gTile/gTile#62]
Hello.

In my normal job i have lots of terminals open and i would be happy if i could be able to autoscale them on 1x* as a run mutiple monitors and have lots of logging windows open.
it might be simple change to a js file or something but beyond my skills.
( using clusterssh )

**Comment by scherepanov** [comment]
There is a (poorly) documented feature - you can arrange multiple windows with one keyboard shortcut.
I do use it exactly for this - arranging many terminal windows on single screen into neat array, with 2 - 9  
columns
Keyboard shorcut called Autotile X, where X is nubmer of columns, you have 2 - 9 columns, You can see where it have been assigned in Tweaks->Extensions->gTile preferences->Keyboard shortcuts

**Comment by ChristofferNicklassonLenswayGroup** [comment]
Hello.

I havent got that to work with 1 column,

**Comment by scherepanov** [comment]
:-) yes 1 column is a special feature, it is equivalent on pressing second from right button in lower row in gTile window
It will move current window to the right, and arrange rest of windows on monitor in one column.
This is legacy function, left from original gTile implementation. Oddly enough, there are people who do use this feature.

**Comment by ChristofferNicklassonLenswayGroup** [comment]
Hello.

That is still 2columns as i count it ..
i want that one to move window to the top and arrange the rest below it.

**Comment by scherepanov** [comment]
Yes I do have an idea how to make it work... Not exactly what you are asking but you will be able to do what you want.
When I will have time I will try to implement.
