### ISSUE TITLE
Undesired behaviour if mouse happen to be over the gtile interface.

### ISSUE THREAD

**Issue by chrisjbillington** [gTile/gTile#67]
I'm using keyboard shortcuts to place windows with gtile, and when I tap super+enter, I can then use arrow keys or shift and arrow keys to move windows from their current position/size to a new position/size in the grid.

With good muscle memory I can execute the motions I want without thinking because I know where the window is and where I want it to be, so the keypresses I have to make are deterministic.

However, if when I press super+enter, the mouse happens to be on top of the mini-grid, then even if the mouse is not moving, the position of the mouse is used as the starting position for motion and resizing, rather than the current position of the window. 

This throws a spanner in the works for resizing/moving windows with deterministic keystrokes, as I have to look to see whether the mouse is over the mini-grid when it pops up, so I can't mentally "queue up" the keystrokes required to move the window until I check this. I have to press super+enter, wait for my brain to register where the mouse is, then queue up further keystrokes. For me this prevents using gtile from becoming completely internalised in my mind, I am still having to put thought into moving windows rather than it being automatic.

What would completely solve this issue is if the initial position of the mouse were ignored by gtile when the mini-grid pops up, and the mouse position only taken into account if the user moves or clicks the mouse. This would completely solve my problem, and would not interfere with mouse usage as the mouse position would be taken into account as soon as there was any mouse movement or clicking.

**Comment by scherepanov** [comment]
Thanks for comment.
Yes behavior is exactly as you described. I agree it is unintended consequences of mouse being over pop-up gTile window.
You can look into code and submit PR.
I will eventually do it, but no promises when I will have time.

**Comment by scherepanov** [comment]
I noticed that this is really an issue. It does create unexpected and undesired behaviour.
After some investigation, it happens due to animation at time of gTile window popup creation. With animation gTile popup is moving on screen first few moments, and it is being detected as mouse move over window.

**Comment by chrisjbillington** [comment]
Sweet, thanks so much for fixing this!
