### ISSUE TITLE
Cant use thumb button on MX Master 2 to Display gTile

### ISSUE THREAD

**Issue by SwankShire** [gTile/gTile#69]
It uses Ctrl + Alt + Tab and I guess its locked out from being used to display gTile?

**Comment by scherepanov** [comment]
That is the problem with key assignment in Preferences dialog... It uses some calls to API, and seems to be very old API that no longer functioning properly.
API restrict what you can put as key for binding. Some restrictions are justifying, some, like in your case, are not (in my opinion).
I tried to look for better API for keybinding. Complete absence of any docs on gnome-shell is amazing. Looking into other extensions code did not help.
If you can find replacement for keybinding API, that would be very nice.
To address issue on hands, you can do following.
You can directly edit gnome properties database with command-line utility. That will give immediate results.
Or, you can edit XML schema file with keybindings, compile it, login/logout.
