### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by StuntsPT** [gTile/gTile#7]
Discussion is growing in #1 about license issues.
I have opened a new issue here, specifically for that, and leave #1 for more general discussion.
Once this issue is closed, the result of the discussion can be added to #1.

**Comment by StuntsPT** [comment]
Current situation:

- [ ] There is only one reference to licensing in the code: [here](https://github.com/gTile/gTile/blob/cacd48f1fb32d667f0b92f7e836a69d3545c2873/schemas/org.gnome.shell.extensions.gtile.gschema.xml#L313-L314).
- [ ] There seems to be some community preference for [MIT](https://choosealicense.com/licenses/mit/) license.
- [ ] gnome-shell-extensions.org seems to require GPLv2+.

**Comment by StuntsPT** [comment]
List of open source license compatibility:
https://en.wikipedia.org/wiki/License_compatibility#Compatibility_of_FOSS_licenses

**Comment by scherepanov** [comment]
Based on what I saw in previous posts about licensing, gTile have GPLv2+
I have no preferences about MIT license. It appears that gTile was licensed as GPLv2+.
I see no way license can be changed from GPLv2+.
I will modify my PR to have GPLv2+ license over weekend.
For ownership of e.g.o. account to upload extension... as @maweki suggested, I sent email to gnome-shell distribution list, but it does not appear to be any attention to it. It will be next issue to tackle.

**Comment by gqmelo** [comment]
> Based on what I saw in previous posts about licensing, gTile have GPLv2+
I have no preferences about MIT license. It appears that gTile was licensed as GPLv2+.
I see no way license can be changed from GPLv2+.

So if that's the case I think it's good to copy gnome-shell wording and ```COPYING``` file:

```
GNOME Shell is distributed under the terms of the GNU General Public License,
version 2 or later. See the COPYING file for details.
```

https://github.com/GNOME/gnome-shell/blob/master/COPYING

**Comment by maweki** [comment]
@scherepanov your mail has not been forwarded to the list, as far as I remember.

**Comment by scherepanov** [comment]
@maweki That is weird. Checking gnome-shell-list-archives, my email is not there.
I do see email in Sent folder of my gmail account:

from: | Sergey Cherepanov <sergey@cherepanov.org>
-- | --
to: | gnome-shell-list@gnome.org
date: | Tue, Oct 17, 2017 at 11:53 PM
subject: | Please reassign ownership of gTile extention
mailed-by: | cherepanov.org

Most likely my email considered to be a spam and filtered out?
Do I need to be whitelisted to be allowed to sent email to this list?

**Comment by maweki** [comment]
Maybe subscribe to the list as well.

**Comment by gqmelo** [comment]
@scherepanov you may try to re-send the email as plain text. Some lists of open source projects don't accept html email. Normally you would get a response why it was rejected, but maybe it was considered spam as you said. You can send as plain text from gmail (not inbox by gmail).

**Comment by scherepanov** [comment]
@maweki You are right, you have to be subscribed to a list to post to it.
I subscribed to gnome-shell-extensions, there is warning can take a few days till moderator will approve .
And yes @gqmelo, it have to be a plain text.

**Comment by jwarkentin** [comment]
FTR, it seems that MIT is in fact GPL compatible from what I'm reading [here](https://softwareengineering.stackexchange.com/questions/204410/how-are-gpl-compatible-licenses-like-mit-usable-in-gpl-programs-without-being-su#204497) so it's not explicitly ruled out. That said, I have no issue moving forward under a GPL license. I'm more concerned about not having a CLA although in practice I doubt anyone will ever care. I still want to bring it up anyway though to see if anyone else is concerned about that.

**Comment by scherepanov** [comment]
Now I have impression that even change to compatible license is nearly impossible, because you need to get explicit agreement from every contributor.

**Comment by scherepanov** [comment]
@maweki I send 2 requests to join mailing list gnome-shell-extensions, 3 days ago and yesterday.
It appears you listed as moderator of this list. I can see you usually responding very fast. That makes me think that for some reason you do not see my requests to join mailing list.
Any idea why? It is just filing email field on web form, and clicking Join.

**Comment by maweki** [comment]
@scherepanov please use the shell-list, not the extension list.

**Comment by StuntsPT** [comment]
It seems like GPLv2 it is.
Closing away.
