### ISSUE TITLE
Ctrl+Super+Numpad_6 not working

### ISSUE THREAD

**Issue by jmooring** [gTile/gTile#73]
Accelerator: `Preset resize 16` is hard coded to Ctrl+Super+6
Resize presets: `Preset resize 16` is set to 2x3 1:1 1:1

I verified the preset resize value in dconf editor.
I disabled then enabled the extension.

Steps to reproduce:

1. Activate desired window and Press Ctrl+Super+Numpad_6
2. Expected behavior: windows moves to center right of screen on a 2x3 grid.
3. Actual behavior: nothing

All of the other Ctrl+Super+Numpad shortcuts are working as expected. The only one causing a problem is Ctrl+Super+Numpad_6.

Alt+Super+Numpad_6 works as expected.
Shift+Super+Numpad_6 works as expected.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

$ gnome-shell --version
GNOME Shell 3.28.3
```

**Comment by jmooring** [comment]
In debug mode, nothing is registered when pressing Ctrl+Super+Numpad_6. All other presets register as expected.

**Comment by jmooring** [comment]
Disregard. This is an OS problem. When running `sudo showkey` the Ctrl+Super+Numpad_6 combination registers Ctrl (keycode 29) and Super (keycode 125), but not Numpad_6 (77). Weird. All other Ctrl+Super+Numpad combinations register as expected.

**Comment by scherepanov** [comment]
Write a fix, submit it as PR.
