### ISSUE TITLE
Suggestion: Undecorate tiled windows

### ISSUE THREAD

**Issue by pokebadgerswithspoon** [gTile/gTile#76]
So save some space it could be worth to "undecorate" aligned windows.
Something what https://extensions.gnome.org/extension/1208/undecorate/ does.

**Comment by scherepanov** [comment]
What is the reason to integrate this functionality into gTile, if it is available in dedicated extension?
"Undecorate" can support a keyboard shortcut to do its work. Then you will get exactly what you want.

**Comment by pokebadgerswithspoon** [comment]
Idea is to undecorate only tiled windows making it take all the screen, while others that float remain decorated

**Comment by yeroca** [comment]
> What is the reason to integrate this functionality into gTile, if it is available in dedicated extension?
> "Undecorate" can support a keyboard shortcut to do its work. Then you will get exactly what you want.

Undecorate doesn't work with Wayland (yet).

**Comment by pokebadgerswithspoon** [comment]
Ah true, the link above depends on `xdotool`.
Anyway even tho having undecorate on tile not really possible for now. 
Here is a scrrenshot to illustrate why could this suggestion be of value.
Imagine a 3tile window setup in GTK theme with far title bars. Thanks to gTile this layout is one click easy to achieve. Howere these title bars, they take place .
Compare it withsecond scheenshot, its gnomes' split left/right layout.
![Screenshot from 2019-03-11 10-48-56](https://user-images.githubusercontent.com/6481705/54107841-5c836000-43eb-11e9-8fa3-c6b57e11d3e5.png)

## VS
note titile bars are gone

![Screenshot from 2019-03-11 10-57-12](https://user-images.githubusercontent.com/6481705/54108230-72ddeb80-43ec-11e9-9ec6-38028a5c756a.png)

**Comment by scherepanov** [comment]
Yes undecorate do save screen space.
If your window is undecorated, then it will be tiled by gTile as undecorated.
In my opinion, it is two different processes:
1) undecorate window
2) tile window
If you can assign undecorate operation to keyboard shortcut, workflow would be quite good - with first shorcut undecorate window, with second shortcut place window.
I still think that undecorate is better managed outside of gTile.

**Comment by pokebadgerswithspoon** [comment]
Well, the propose was an improvement to this routine: automate undecorating myltiple windows on tile (and decorate back on resize or move if that is even possible). May be expose hooks in Gtile ? =)
But now I'd agree - it is not worth the hussle not before undecorating under wayland works. For now it would be a bugful experience

**Comment by yeroca** [comment]
I've found that slimming the title bars helps a fair amount.  This can be done with a gtk.css file.
