### ISSUE TITLE
shortcut for predefined layout

### ISSUE THREAD

**Issue by henri9813** [gTile/gTile#77]
Hello,

I don't find in the shortcut, a one to achieve this layout ? 
( It's possible that I don't find it in the documentation )

There is one existing for that ?

![image](https://user-images.githubusercontent.com/4645967/54740726-7e839c00-4bbc-11e9-8d10-77aba6f33b6f.png)

Best regards

**Comment by scherepanov** [comment]
<Super>-[KP-Enter] (enter on keypad)
Then try <Super> - 1 - 9 (not on keypad)
ESC will exit
