### ISSUE TITLE
Keyboard shortcuts not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by con-f-use** [gTile/gTile#79]
I might have missed something, but on stock Ubuntu 18.04 (GNOME Shell 3.28.3) with freshly installed gtile, global keyboard shortcuts just do not work at all.

**Comment by csbc92** [comment]
I have the same problem with Global shortcuts. They do not activate. Shortcut works with non-global shortcuts, that is, when the gTile window has been activated prior to pressing the shortcut.

**Comment by scherepanov** [comment]
There is a settings in preferences for enabling global shortcuts - can you check if it is set?
Next, can you enable debug, logout/login, and try to use global shortcuts. Then, post here logs (how to get described in preferences->help)

**Comment by con-f-use** [comment]
Yes, I had enabled the global shortcuts and there were no debugging message.

However, I noticed, the problem is only with <kbd>ALT</kbd>+<kbd>Super</kbd>+<kbd>*ANY*</kbd> and plain <kbd>ALT</kbd>+<kbd>*ANY*</kbd> shortcuts, which might have a special meaning on Ubuntu?

**Comment by scherepanov** [comment]
Ontopic
It should be debug message stating that global shortcuts are enabled, on extension init. But, they should be enabled in corresponding setting is set in preferences. So, you will not find a smoking gun there.
Yes it is a very typical for some gnome-shell extension to grab several keys. In this case, extensions down the food chain will not see it.
For this reason I am trying not to pollute global shortcut space.
In your case, I think Ubuntu itself is grabbing some shortcuts. They are not making it to gTile. As reason lies outside of gTile, it is not fixable on our side.
ALT+ANY is not in default shortcuts, gTile is not handling them. Though you can assign ALT+ANY by yourself in preferences.
ALT+SUPER+[KP-number] is in default shortcuts, should be seen. If you do not see debug message on pressing them, it means someone grab them. Again, this is outside gTile.
You still should be able to assign your own shortcuts that are not intercepted.
Offtopic - your diagram is awesome.
Can you spend 20 minutes and submit PR, modifying README.md? Put your diagram somewhere in appropriate place closer to the end.

**Comment by con-f-use** [comment]
> ALT+ANY is not in default shortcuts, gTile is not handling them. Though you can assign ALT+ANY by yourself in preferences.
Copy&Paste error, I meant <kbd>Super</kbd>+<kbd>ANY</kbd>
