### ISSUE TITLE
Compatibility with status-area-horizontal-spacing

### ISSUE THREAD

**Issue by p91paul** [gTile/gTile#80]
Hi,
I'm the maintainer of the gnome-shell extension status-area-horizontal-spacing. It was reported (https://bitbucket.org/mathematicalcoffee/status-area-horizontal-spacing-gnome-shell-extension/issues/4/removes-gtiles-default-padding-doesnt) there is an issue with gTile space handling. I've tried, and seen quite strange things happen, from your extension getting 0 width to not behaving properly when changing width.

Other extension featuring status bar buttons, like Backslide, https://bitbucket.org/LukasKnuth/backslide/src, display the icon as a St.Icon *inside* the PanelMenu.Button, not by setting a background-image to the PanelMenu.Button itself. This is the main difference I'm seeing in gTile that might justify this behavior.

Do you think this can be fixed in gTile, or can you suggest a fix to be applied in status-area-horizontal-spacing?

**Comment by scherepanov** [comment]
That is very interesting... my box is Fedora 29, will try to reproduce and play with it.
My first impression is that should be no difference.
Can you submit PR that will use same approach for setting icon, as yours extension?
And, really, what is the correct way to set icon?

**Comment by p91paul** [comment]
I can't guarantee I will find the time to try and do this. As per the **correct** way, I honestly don't know :). Doesn't make any sense to me either.
