### ISSUE TITLE
Treat multiple screens as a single large one?

### ISSUE THREAD

**Issue by con-f-use** [gTile/gTile#84]
I'm not sure if this already works somehow and I'm just missing an option.

Currently, when you have multiple monitors and open the gTile pane, this is displayed on **each** monitor:

![image](https://user-images.githubusercontent.com/11145016/57570870-38ea8f00-7407-11e9-9b99-75da259780d8.png)

and tiling is done for each monitor separately. I.e. if you're on a **3x2 layout**, the tiling would be like this:

| monitor 1 | | | monitor2 | | |
|--------------|-|-|------------|-|-|
| 0:0 | 0:1| 0:2 |  0:0 | 0:1| 0:2 |  
| 1:0 | 1:1| 1:2 |  1:0 | 1:1| 1:2 |  

and to my knowledge, you cannot make a window span across monitors, e.g. have tiles `0:1 0:2 1:1 1:2` on monitor 1 and `0:0 1:0` on monitor 2. Correct?

Is there a way to either have a window span across monitors or have gTile treat the whole screen-area as a single monitor?

**Comment by scherepanov** [comment]
It is correct that gTile is limiting window movement to one monitor.
Your suggestion to allow gTile to use multiple monitors would be hard to implement in a way that will satisfy a lot of use cases.
For example, I have one horizontal 43'' in 4K and 2 smallish vertical 32' on sides, with slightly lower DPI. In my config, it is explicitly better to limit window to one monitor.
Most likely common use case would be when user have two identical monitors with identical configuration. It this case some users want to see window to span monitors.
I think your use case would be better addressed if you will have several monitors presented as one screen. Then OS will see everything as one huge screen. It is possible to do this config manually.

**Comment by con-f-use** [comment]
> I think your use case would be better addressed if you will have several monitors presented as one screen.

But that is not implemented at moment, and there is no plan to implement it?

**Comment by scherepanov** [comment]
Yes, it is possible to configure many monitors as a single screen.
If you are using nVidia of AMD graphic cards, there is a settings in Nvidia or Catalyst drivers for this, you can edit in GUI.
If you are using Intel graphic, your only option is Nuevau driver. In this case, you need to resort to manual XRandr config. It is not pretty but is a working configuration.

**Comment by scherepanov** [comment]
FYI
Once in process of addition some code to gTile, I had a moment when grid was spawning all monitors.
Exactly as you want.
Attempt to use was not pretty. In my configuration with 3 monitors of horizontal and vertical config, windows can be partially or completely out of sight, part of window on one monitor would have different DPI than on another etc.
Was not really possible to align window to monitor edge, as grid was not aligned. And so on.
Looks horrible.

**Comment by con-f-use** [comment]
Hmm... I'm coming to realize that what I really want, is to tell gTile which cells on which screens the window should occupy via a key-binding. It there a way to specify the monitor in gTile presets?

Like: <kbd>Alt</kbd>+<kbd>Alt</kbd>+<kbd>KP_6</kbd> = `left monitor 3x3 1:0 2:3`
Is there a syntax for that or would it be easily implemented?

**Comment by scherepanov** [comment]
I am using gTile on several monitors
First, I am moving window to desired monitor. Gnome have built-in shortcut <Super>-Arrows that will move focused window to adjancent monitor in direction of arrow.
Second, I am using gTile to position window in desired location.
Works fine for me.

**Comment by con-f-use** [comment]
Still would be one less key-combination to remember and press. I'd like that.

**Comment by scherepanov** [comment]
Sorry shortcut to move window between screens in Gnome-shell is shift-super-arrows

**Comment by scherepanov** [comment]
Seems to be best way to achieve desired result is to use proprietary driver from AMD or Nvidia. They allow to setup single screen that spawn multiple monitors.

**Comment by tiriana** [comment]
Another use case for this feature is when someone has an ultrawide monitor. I have such at work. It acts like 2 monitors. I would love to have an option to tile it so I have one big working space in the middle, and two on the sides.
