### ISSUE TITLE
Asymmetric gaps when tiling gnome terminal

### ISSUE THREAD

**Issue by vegabook** [gTile/gTile#88]
I have my window margin set to 4, but I think this happens even if it's at the default, zero. 

Gnome terminal does not "hug" the right hand side of the screen, nor does it properly go to the middle of the screen, when asked to do so by gTile. Herewith full screenshot:

![image](https://user-images.githubusercontent.com/3780883/61820023-213e7680-ae4c-11e9-8708-ea4d6b300551.png)

And zoomed in on the offending corner:

![image](https://user-images.githubusercontent.com/3780883/61820073-374c3700-ae4c-11e9-9bae-137b36254b51.png)

Here's what it looks like if I use Konsole on both halves of the screen:

![image](https://user-images.githubusercontent.com/3780883/61820139-5945b980-ae4c-11e9-8782-bd8fd1297cc4.png)

And zoomed:

![image](https://user-images.githubusercontent.com/3780883/61820166-695d9900-ae4c-11e9-944f-05bcaf45580e.png)

So as you can see, Konsole, like all other applications, behaves as one would expect with gTile. It goes all the way to the edge, both on the right hand side and bottom. Gnome terminal however seems to "round" things down to the nearest character or something. Funnily enough, gnome terminal does NOT do this if you use gnome's default "snap". 

I find it distracting, and gnome terminal is of course the default terminal in gnome. Ideally gTile would force gnome terminal to behave nicely like everything else, and it must be possible because of the default snap behaviour.

**Comment by scherepanov** [comment]
Yes, this is how it works. i am also using gnome-terminal, and there are almost always gaps between terminal windows.
Two days ago it was identical issue #86 
Window moving behaviour is modified by gnome-terminal.
gTile calculates windows position and size correctly, you can see it on example of other applications.

**Comment by vegabook** [comment]
Okay. Love gTile so I'm moving to Konsole which does not behave this way.
