### ISSUE TITLE
Stack-Trace hints to syntax error when loading gTile extension in Gnome 3.26.1

### ISSUE THREAD

**Issue by postgrep** [gTile/gTile#9]
Hi Team, i just installed the extension from here:
https://extensions.gnome.org/extension/28/gtile/
Onto this System:

OS Ubuntu 17.10
Gnome 3.26.1

Gnome Tweaks tells me there is an error loading the extension. 
When i try to open the preferences dialog of the extension i get this neat little stack-trace: 

SyntaxError: redeclaration of formal parameter iter

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
  @<main>:1:43

**Comment by scherepanov** [comment]
That was fixed a while ago, as well as other errors that pop up after this one fixed.
Fixes did not make it to master in any master repo yet, and not on extensions.gnome.org. Hopefully will be there sooner than later.
As of now, you can get a working code for Ubuntu 17.10 from scherepanov/gTile repo

**Comment by jwarkentin** [comment]
Sorry, we are still in the process of setting up this official replacement so things are a little bit slow getting off the ground. With any luck we should be able to push an update soon that will resolve issues for everyone.

**Comment by returntrip** [comment]
Was this https://github.com/gTile/gTile/pull/8 meant to fix this issue?

**Comment by garret-gunter** [comment]
Is there a way to get notified when the update has been pushed to Gnome Extensions?  

I'm fine with manually installing from the repo for now, but I prefer using the package manager for updates.  Thanks for maintaining the extension.

**Comment by scherepanov** [comment]
I am not sure, but most likely you will get regular notification about new version of gTile available on Gnome extensions web site.

**Comment by StuntsPT** [comment]
IIRC gnome-tweak-tool will show when an extension is out of date.

**Comment by JMurph2015** [comment]
I believe this should be fixed now that we have been able to update the extension on e.g.o,, so I am going to tentatively close this?
