### ISSUE TITLE
Default accelerators conflict with Super shortcuts in GNOME 3

### ISSUE THREAD

**Issue by wizonesolutions** [gTile/gTile#90]
Hi, I'm on Ubuntu 18.04 and GNOME 3.28.2. Super+1, Super+2, etc. are used to switch to applications in the Dock, so I can't actually use them for autotiling. Since this is a GNOME extension, it would probably be good to choose other shortcuts by default for the accelerators. Any suggestions? Maybe `Alt+Super+{Q,W,E,R,T,Y,U,I,O,P}` (just because the numbers are already taken by presets)?

**Comment by scherepanov** [comment]
That is very correct.
Default accelerators for autotiling are significantly overlap with gnome defaults, and some other extension defaults.
May be Alt-Super-1...0?

**Comment by wizonesolutions** [comment]
`Alt-Super` is possible, but already mapped to presets. So presets would also need new default keyboard shortcuts.

**Comment by scherepanov** [comment]
Resize presets Alt-Super-{1-9} are mapped on side keypad, not on regular numbers. 
And, I am thinking about adding new autotile option - tile all available windows on current grid, one window per tile. That require one more shortcut.
And more autotile options - leave focused window as-is, but autotile rest of windows around it, in 1..9 columns. Same way it is done now.
So... keyboard presets need rethinking, to make them usable, avoid conflicts with stock Gnome presets, and make easy for users to remember/use.

**Comment by scherepanov** [comment]
I am planning to do following changes to default keyboard shortcuts:
1) Added one more (or alternative) activation key Super-Return. It will do same action as current one Super-KP_Enter
2) When gTile active, autotile presets are Super-[0..9]. It conflicts with Gnome a lot. I am changing them to [0..9]. without Super.
