### ISSUE TITLE
Feature request: Move tiled windows between monitors

### ISSUE THREAD

**Issue by dtruitt-videon** [gTile/gTile#91]
I'm very much enjoying using this extension.

However, I think it'd be nice to be able to move a window from one monitor to another.

Note that this is different than closed issue #84, as it would not involve spanning windows across monitors.

Best regards,

Dan Truitt

**Comment by scherepanov** [comment]
There is a standard Gnome built-in for moving windows between monitors, Alt-Super-Arrows
It works just fine for me, I am using it extensively.
Let me know if this is what you want

**Comment by scherepanov** [comment]
Implemented at Gnome level
