### ISSUE TITLE
Tile over multiple grid cells

### ISSUE THREAD

**Issue by EiNSTeiN-** [gTile/gTile#92]
I have presets that split my display in thirds (3x1 cells), I can resize windows to fit in the individual cells (0:0, 1:0 and 2:0) however I have not found a way to resize a window to fit 2/3 of the screen so that it would cover 2 of the cells at once (either 0:0 and 1:0 or 1:0 and 2:0). Is this possible? Would there be interest in having that option available?

**Comment by scherepanov** [comment]
Having many cells for window preset is a basic gTile functionality that exists from the very beginning.
Check default presets, you will find window preset 0:0 1:1 on 3x3 grid, which cover 4 cells on 9-cell grid.

**Comment by EiNSTeiN-** [comment]
Thanks, I tried again and found the issue with the syntax I was using.
