### ISSUE TITLE
Windows not resizing properly...

### ISSUE THREAD

**Issue by darkermatter** [gTile/gTile#95]
Hello,

I have a simple grid set up as 30x4 to get the proportions I would like but it looks like the windows are not placing properly and also not respecting the window borders.

Is there some sort of rounding going on?

Screen resolution 3440 x 1440
Gnome 3.34
Fedora 31
Wayland

![Screenshot from 2019-09-25 19-03-22](https://user-images.githubusercontent.com/5037324/65623111-5c356580-dfc7-11e9-80da-3fbb2fae8106.png)

**Comment by scherepanov** [comment]
On your screenshot I can see you are trying to tile gnome terminal.
Gnome terminal is resisting correct exact window resize, and changing itself to sligtly smaller window size that exactly fit char width and height. As result, you can see gaps between gnome terminals. Sometimes gaps are as big as one char height/width.
Unfortunately there is no way to change gnome terminal behavior for window resize.
What you see is expected.
Regular applications are being resized properly, you can test it on calculator for example.
I did special investigation on rounding errors for gTile window border calculations. I had user who complained that two dark-theme terminals when placed adjacent have a bright line between them from background. It appears window edges were calculated correctly, bright line was an artefact of gnome fuzzy borders. I can tell as of now there are no rounding errors in gTile windows border calculations.
You can check rounding errors by yourself. Enable gTile logging, it will tell you window upper-left corner and width/height for each window resize. Please let me know if you will find rounding error.
BTW your resize presets looks correct and cool. If you have some spare time on your hands, submit PR - add to gTile ability to load new "theme" - set of presets. I am pretty sure it will be very useful feature.

**Comment by darkermatter** [comment]
All of those windows are gEdit

**Comment by darkermatter** [comment]
Hi @scherepanov 
I enabled logging and moved a window to the top right corner. Here are the results:
```
Sep 26 08:28:46 wopr gnome-shell[2650]: gTile presetResize window title: local
Sep 26 08:28:46 wopr gnome-shell[2650]: gTile Preset resize 3  is 30x4 21:0 29:1
Sep 26 08:28:46 wopr gnome-shell[2650]: JS WARNING: [/home/me/.local/share/gnome-shell/extensions/gTile@vibou/extension.js 1025]: assignment to undeclared variable ps_variant_count
Sep 26 08:28:46 wopr gnome-shell[2650]: gTile Parsed 30x4 21:0 29:1
Sep 26 08:28:46 wopr gnome-shell[2650]: gTile Parsed preset 3 30x4 21:0 29:1
Sep 26 08:28:46 wopr gnome-shell[2650]: gTile Resize preset 3 resizing to wx 2395 wy 1 ww 1026 wh 718
Sep 26 08:28:46 wopr gnome-shell[2650]: gTile move_resize_window_with_margins local 2395:1 - 1026:718 margin 1 borders invisible 26:23 visible 0:0
Sep 26 08:28:46 wopr gnome-shell[2650]: gTile After margins and visible border window is 2396:2 - 1024:716
Sep 26 08:28:46 wopr gnome-shell[2650]: gTile Resize preset last call: 1569479326966
Sep 26 08:28:46 wopr gnome-shell[2650]: gTile presetResize window title: local
Sep 26 08:28:46 wopr gnome-shell[2650]: gTile Preset resize 3  is 30x4 21:0 29:1
Sep 26 08:28:46 wopr gnome-shell[2650]: gTile Parsed 30x4 21:0 29:1
Sep 26 08:28:46 wopr gnome-shell[2650]: gTile Parsed preset 3 30x4 21:0 29:1
Sep 26 08:28:46 wopr gnome-shell[2650]: gTile Resize preset 3 resizing to wx 2395 wy 1 ww 1026 wh 718
Sep 26 08:28:46 wopr gnome-shell[2650]: gTile move_resize_window_with_margins local 2395:1 - 1026:718 margin 1 borders invisible 26:23 visible 0:0
Sep 26 08:28:46 wopr gnome-shell[2650]: gTile After margins and visible border window is 2396:2 - 1024:716
Sep 26 08:28:46 wopr gnome-shell[2650]: gTile Resize preset last call: 1569479326974
```

2396 + 1024 = 3420
The screen width is 3440. That explains the 20 pixel border to the right, so some weird rounding is happening.
Also, it appears that the operation ran twice.

**Comment by darkermatter** [comment]
I also created a test preset using the screen resolution and got this output:
```
Sep 26 08:40:23 wopr gnome-shell[2650]: gTile presetResize window title: GNOME Tweaks
Sep 26 08:40:23 wopr gnome-shell[2650]: gTile Preset resize 10  is 3440x1440 2395:1 1026:1436
Sep 26 08:40:23 wopr gnome-shell[2650]: gTile Bad format 3440x1440, delimiter x
Sep 26 08:40:23 wopr gnome-shell[2650]: gTile Bad format 2395:1, delimiter :
Sep 26 08:40:23 wopr gnome-shell[2650]: gTile Bad format 1026:1436, delimiter :
Sep 26 08:40:23 wopr gnome-shell[2650]: gTile Parsed -1x-1 -1:-1 -1:-1
Sep 26 08:40:23 wopr gnome-shell[2650]: gTile Bad preset 10 settings 3440x1440 2395:1 1026:1436
Sep 26 08:40:24 wopr gnome-shell[2650]: gTile presetResize window title: GNOME Tweaks
Sep 26 08:40:24 wopr gnome-shell[2650]: gTile Preset resize 10  is 3440x1440 2395:1 1026:1436
Sep 26 08:40:24 wopr gnome-shell[2650]: gTile Bad format 3440x1440, delimiter x
Sep 26 08:40:24 wopr gnome-shell[2650]: gTile Bad format 2395:1, delimiter :
Sep 26 08:40:24 wopr gnome-shell[2650]: gTile Bad format 1026:1436, delimiter :
Sep 26 08:40:24 wopr gnome-shell[2650]: gTile Parsed -1x-1 -1:-1 -1:-1
Sep 26 08:40:24 wopr gnome-shell[2650]: gTile Bad preset 10 settings 3440x1440 2395:1 1026:1436
```
Again, it looks like it tries to run the operation twice.
Are the preset resolutions limited to 2 digits?

Cheers!

**Comment by darkermatter** [comment]
Okay, I found the problem... You are rounding too early:
```
let grid_element_width = Math.floor(work_area.width / grid_format.X);
let grid_element_height = Math.floor(work_area.height / grid_format.Y);
```
You later go on to use these values:
```
let wx = work_area.x + luc.X * grid_element_width;
let wy = work_area.y + luc.Y * grid_element_height;
let ww = (rdc.X + 1 - luc.X) * grid_element_width;
let wh = (rdc.Y + 1 - luc.Y) * grid_element_height;
```

Rounding should always be done on the last calculation, thus:
```
let grid_element_width = work_area.width / grid_format.X;
let grid_element_height = work_area.height / grid_format.Y;
let wx = Math.floor(work_area.x + luc.X * grid_element_width);
let wy = Math.floor(work_area.y + luc.Y * grid_element_height);
let ww = Math.floor((rdc.X + 1 - luc.X) * grid_element_width);
let wh = Math.floor((rdc.Y + 1 - luc.Y) * grid_element_height);
```
Now windows are behaving as expected.

**Comment by darkermatter** [comment]
One last comment...
Perhaps using ```Math.round()``` would be preferable to ```Math.floor()```

**Comment by scherepanov** [comment]
OK, it is a very reasonable comment about rounding too early. Will put in next release.
And, I thin you are right about using Math.round() instead of Math.floor()

**Comment by scherepanov** [comment]
Yes, preset resolution is limited to two digits:
    if(gssk.length != 2
        || isNaN(gssk[0]) || gssk[0] < 0 || gssk[0] > 40
        || isNaN(gssk[1]) || gssk[1] < 0 || gssk[1] > 40) {
        log("Bad format " + format + ", delimiter " + delimiter);
        return {X: Number(-1), Y: Number(-1)};
I did it to make more fool-proof for user settings. Rows and columns should be in range 1..40.
Do you really have a case for more rows and columns?
Do you think that limiting row/col number to 40 is way too strict? What should be upper limit?

**Comment by scherepanov** [comment]
I cannot reproduce - operation run twice.
