### ISSUE TITLE
Resizing on secondary monitor is fine, but on main monitor causes glitch

### ISSUE THREAD

**Issue by vitutc** [gTile/gTile#98]
Hi~

On one of my monitors (the secondary), gTile works fine and it's great! Thank you for this! =D

However on my primary monitor it does not work and a glitch happens where the window gets pushed to the top of the screen and squeezed.

I will attach a GIF here so you can see what happens. If there is any way I can contribute to give more information, please let me know!

![gtile_glitch](https://user-images.githubusercontent.com/4968286/67914977-06129e00-fbd5-11e9-947d-74ef1ccaf6a8.gif)

**Comment by scherepanov** [comment]
Looks like gTile is not determining monitor size/position correctly
To find what is going on, can you enable debug in preferences, logout/login, and check logs and paste them here.
It will be log entry about screen size, I am pretty sure it was not determined correctly.
You can look on logs by yourself, it is self-explanatory

**Comment by vitutc** [comment]
Thank you for the quick reply!
I will check the logs and report here~

**Comment by vitutc** [comment]
Hi @scherepanov,

I have forgot to mention that I am running gTile on Cinnamon. In the preferences I could not find a `Debug` option. I have also searched through the extension code on my machine and could not find a variable setting for that.

Could you please point me in the right direction to enable debugging? ><

Thank you!

**Comment by scherepanov** [comment]
There is a preference dialog in gTile. It is accessible through tweaks->extensions->gTile, click "config" icon.
